### ISSUE TITLE
[Bug]: Changing the background color of the completion window but it does not work.

### ISSUE THREAD

**Issue by Ryutaku** [mallowigi/material-theme-issues#100]
### Describe the bug

When I select the dark theme such as materia atom one dark, I found that the default selected item in the completion window is not clearly to read. So, I try to change the background color of the completion window, but it doesn't work. And I also need to know that how to change the bg color of the selected item in the completion window.

### To Reproduce

settings>editor>color schema>general>popups and hint>completion,   change the background color

### Expected behavior

the background color of the completion window can be changed

### Material Theme Version

v6.14.1

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2021.3.2 (Ultimate Edition)
Build #IU-213.6777.52, built on January 28, 2022
Licensed to Administrator

Runtime version: 11.0.13+7-b1751.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
    ide.intellij.laf.enable.animation=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    com.intellij.plugins.eclipsekeymap (213.5744.3)
    MavenRunHelper (4.20.213.3714.1)
    org.jetbrains.kotlin (213-1.6.10-release-961-IJ6777.52)
    com.itangcent.idea.plugin.easy-yapi (2.3.3.183.0)
    com.chrisrm.idea.MaterialThemeUI (6.14.1)
    flowable-bpmn-visualizer (0.4.9.3)
    JRebelPlugin (2022.1.2.1)
    cn.yiiguxing.plugin.translate (3.2.2-213)
    com.ccnode.codegenerator.MyBatisCodeHelperPro (2.9.9-SNAPSHOT-183-204)

Kotlin: 213-1.6.10-release-961-IJ6777.52
```

### Logs/Screenshots
![image](https://user-images.githubusercontent.com/1673177/158506887-4bfb8170-daff-4172-9e44-ba385d7fbc6f.png)
![image](https://user-images.githubusercontent.com/1673177/158506940-6502a817-88d7-40a3-b426-7261e83c07a8.png)
![image](https://user-images.githubusercontent.com/1673177/158507221-018ea72c-582a-4904-a988-4b3065371022.png)

_No response_

**Comment by Ryutaku** [comment]
Now, I have the two problems:
* Changing the color but it's not be changed, Is it a bug or the way of my setting is not right?
* How to change the background color of the selected item in the completion window ?
* How to change the background color of the completion window?

**Comment by mallowigi** [comment]
I don't know what this "Completion" is for. I tried with the plugin disabled and it doesn't affect the menu you're referring to.

The completion you're talking about is set by the themes and is not modifiable, unless you use a custom theme. That being said, there is a setting named "Inverted Completion Color" in the Material Theme Settings; try to enable it and see if that does the job.

**Comment by Ryutaku** [comment]
![image](https://user-images.githubusercontent.com/1673177/159901399-ab9fecf2-7381-41c5-b88e-35b8b06e9bcb.png)

Well, I mean, how to change the background color of the selected item in the figure
