### ISSUE TITLE
[Feature]: The border of the window for finding files is not clear in dark theme

### ISSUE THREAD

**Issue by Ryutaku** [mallowigi/material-theme-issues#101]
### Describe the feature

As follow:

![image](https://user-images.githubusercontent.com/1673177/158529594-d923d849-2ffc-484e-9e86-c6eae6336474.png)

When i use dark theme, The border of the window for finding files is not clear

### Material Theme Version

v6.14.1

### IDE

IntelliJ IDEA

**Comment by mallowigi** [comment]
what do you mean the border?
