### ISSUE TITLE
[Bug]: Clickable area not incremented properly when Custom tree indent option is used

### ISSUE THREAD

**Issue by Azaret** [mallowigi/material-theme-issues#114]
### Describe the bug

Hi,

When the Custom Tree Indent option is used, the clickable area for the expand/reduce arrow is not indented as much as the arrow itself:

![screencast 2022-03-31 16-20-51](https://user-images.githubusercontent.com/1201743/161082100-db2a0813-c4f3-4af3-acea-07e14be8f12a.gif)

So, clicking the arrow itself does nothing, while clicking few pixel on the left of the arrow expand/reduce the folder as expected.

### To Reproduce

1. Go to the preferences "Preferences > Appearence & Behavior > Material Theme UI > Settings" 
2. Go to the "Project View" tab
3. Enable the "Custom Tree Indent" option
4. Set custom values, ie Left: 2, Right: 6
5. Click on the Apply button
6. Click on some folder arrow on the Project view.

### Expected behavior

Folder should expand or reduce with a single click.

### Material Theme Version

7.2.1

### IDE

PHPStorm

### System Info

```shell
PhpStorm 2022.1 EAP
Build #PS-221.5080.66, built on March 24, 2022
Licensed to PhpStorm EAP user: 
Expiration date: April 23, 2022
Runtime version: 11.0.14.1+1-b2043.17 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 12
Registry:
    run.processes.with.pty=TRUE
    ide.mac.transparentTitleBarAppearance=false
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    net.seesharpsoft.intellij.plugins.csv (2.18.2)
    ideanginx9 (0.1.9)
    com.paperetto.dash (3.3)
    com.intellij.ideolog (203.0.27.0)
    String Manipulation (9.4.0)
    mobi.hsz.idea.gitignore (4.4.0)
    de.espend.idea.php.annotation (8.0.0)
    com.kalessil.phpStorm.phpInspectionsEA (4.0.7.1)
    com.dmarcotte.handlebars (221.5080.56)
    com.chrisrm.idea.MaterialThemeUI (7.2.1)
    com.mallowigi (60.0.0)
```

**Comment by mallowigi** [comment]
Thanks, it looks like this bug was here for a looong time! Anyway it looks like the minimum for the left indent is 6, and past that limit there are some unwanted behavior such as the one here.

I'll reduce that limit at 6, sorry.
