### ISSUE TITLE
[Bug]: Selectors not shown on parents of nested menus.

### ISSUE THREAD

**Issue by tom-ricci** [mallowigi/material-theme-issues#117]
### Describe the bug

When in menus where there are nested items, the parent item of the menu does not change background color like other items do on Linux, but work fine on Windows. (See image)

### To Reproduce

1. Hover over any parent of a menu, even just the ones at the top like File, Edit, etc.

### Expected behavior

For the items to change background on hover.

### Material Theme Version

v6.16.1

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2021.3.3 (Ultimate Edition)
Build #IU-213.7172.25, built on March 15, 2022
Licensed to Thomas Ricci
Subscription is active until March 5, 2023.
For educational use only.
Runtime version: 11.0.14.1+1-b1751.46 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.13.0-37-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    net.antelle.intellij-xcode-dark-theme (1.2.4)
    com.vermouthx.xcode-theme (1.5.0)
    org.jetbrains.kotlin (213-1.6.10-release-961-IJ6777.52)
    com.github.tth05.minecraft-nbt-intellij-plugin (1.5.2)
    cn.yiiguxing.plugin.md.palette (1.4)
    mobi.hsz.idea.gitignore (4.4.0)
    com.demonwav.minecraft-dev (2021.3-1.5.18)
    com.intellij.tailwindcss (213.7172.5)
    com.chrisrm.idea.MaterialThemeUI (6.16.1)
    lermitage.intellij.extra.icons (2022.1.1)

Kotlin: 213-1.6.10-release-961-IJ6777.52
Current Desktop: GNOME
```

### Logs/Screenshots

What happens:
![Screenshot from 2022-04-03 03-05-43](https://user-images.githubusercontent.com/79022795/161416004-7b8fa452-e97e-4c2b-a0a6-43f78116f708.png)
![image](https://user-images.githubusercontent.com/79022795/161416026-b363d0cb-a090-431e-815b-c4b21d321ce0.png)

What should happen:
![image](https://user-images.githubusercontent.com/79022795/161416036-907b763e-f476-47c2-bbc3-dab972a79853.png)

...sorry for bombarding you with issues recently :sweat_smile:

**Comment by mallowigi** [comment]
It's ok, there has been a major redesign so of course there are issues.

I remember having checked this very recently and it looked it had been fixed, but maybe another update broke it :(

I'll try to check it once again whenever I can.

**Comment by mallowigi** [comment]
Hi, I finally got my hands on a Linux machine and unfortunately I couldn't manage to reproduce your problem.

Can you tell me if it is still the case in 7.3? And in that case, can you share your settings? Thanks.

**Comment by tom-ricci** [comment]
This is still the case in 7.3.2 for me. Here's my settings (the other settings menus are both set to default):

https://user-images.githubusercontent.com/79022795/165670443-cb6b70bc-89bb-440d-a548-b7d2b62351f6.mp4

**Comment by mallowigi** [comment]
I see, you're using the old legacy material design. The reason it is working now id because I had to refactor all components as part of the new UI, so if you're using the old UI the bug is still present.

I'm afraid there's little I can do. I could try to check if the change to the menus is small so I can export it to the old ui but I can't promise anything.

**Comment by tom-ricci** [comment]
Okay, that's fine. It's not a major issue or anything, just a bit annoying.
