### ISSUE TITLE
[Bug]: Missing "Redirect input", "Run with root privileges" fields in "CMake Application" run/debug configuration in CLion. 

### ISSUE THREAD

**Issue by Maririri** [mallowigi/material-theme-issues#119]
### Describe the bug

The "Redirect input", "Run with root privileges", Environment variables (issue #118) fields are missing
<img width="1038" alt="Screenshot 2022-04-04 at 17 34 44" src="https://user-images.githubusercontent.com/7041963/161580094-4ac841e1-2d5b-43fe-bf68-a6f62bae3500.png">

### To Reproduce

1. Launch CLion 
2. Enable Material plugin theme
3. Create/open a CMake Application run configuration

### Expected behavior

<img width="1043" alt="Screenshot 2022-04-04 at 17 35 46" src="https://user-images.githubusercontent.com/7041963/161580325-b42a954b-851e-471c-ad1c-94c857694218.png">

### Material Theme Version

v7.2.2

### IDE

Other (AppCode, CLion, GoLang...)

### System Info

```shell
CLion 2021.3.4, 2022.1
OS: Ubuntu 20.04, macOS 11.6
```

**Comment by AkideLiu** [comment]
Same behaviour on my end, Clion 2021.3.4, Material Theme Version 6.16.1, Linux version Ubuntu 20.04.

Problem temporarily solved, this strange behavior related to this plugin, current workaround is to rollback this plugin to previous version (6.15.0).

More details have submit to JetBrains your tracks, https://youtrack.jetbrains.com/issue/CPP-28803
