### ISSUE TITLE
[Bug]: New File dialog input area is too small 

### ISSUE THREAD

**Issue by dudong0726** [mallowigi/material-theme-issues#122]
### Describe the bug

New File dialog input area is too small 

### To Reproduce

1. new File or new Javaclass
2. dialog input area is too small

### Expected behavior

show normal

### Material Theme Version

6.16.2

### IDE

IntelliJ IDEA

**Comment by dudong0726** [comment]
![20220406095641](https://user-images.githubusercontent.com/1704803/161881150-f2686324-72c0-421c-9b24-27888466ab48.jpg)

**Comment by mallowigi** [comment]
One fix breaks another... I think I know what might cause it. If it's what I think I'll release yet another hotfix. Good thing I didn't deploy to 2022 yet...

**Comment by mallowigi** [comment]
Are you using compact fields ?

**Comment by dudong0726** [comment]
> Are you using compact fields ?

yes, i uncheck the compact fields, its fixed.

**Comment by mallowigi** [comment]
duplicate of 121
