### ISSUE TITLE
[Bug]: Title is not visible on database visualization tool

### ISSUE THREAD

**Issue by spycrabo** [mallowigi/material-theme-issues#131]
### Describe the bug

Title and background colors are the same on database visualization when using "Material Oceanic" theme.

Using "Material Oceanic":
![material-oceanic-bug](https://user-images.githubusercontent.com/30431331/162687680-3ca668d3-1f7a-4885-8954-6625d4527d45.png)

### To Reproduce

1. Select "Material Oceanic" theme
2. From "Database" tool select db and make visualization (right-click on db -> Diagrams -> Show visualiztion)
3. See the "blank" headers with table name

### Expected behavior

For example, select "Arc Dark" theme. Now table name in header is visible:
![arc-dark](https://user-images.githubusercontent.com/30431331/162688351-bfbc4636-e5e5-48b2-a6e8-c53eba49d2f1.png)

### Material Theme Version

v6.16.2

### IDE

PHPStorm, DataGrip

### System Info

```shell
PhpStorm 2021.3.3
Build #PS-213.7172.28, built on March 17, 2022

Runtime version: 11.0.14.1+1-b1751.46 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-107-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 8
Registry:
    run.processes.with.pty=TRUE
    ide.balloon.shadow.size=0
    ide.images.show.chessboard=true

Non-Bundled Plugins:
    com.chrisrm.idea.MaterialThemeUI (6.16.2)

Current Desktop: ubuntu:GNOME
```

### Logs/Screenshots

Provided above

**Comment by mallowigi** [comment]
![CleanShot 2022-05-03 at 21 59 12](https://user-images.githubusercontent.com/5015756/166523834-d6152da5-6b14-4a91-8488-939dffdfdb25.png)

I don't see the issue in my case. Please make sure you're using updated resetted color schemes (PS: Your Material Theme version is outdated)
