### ISSUE TITLE
[Bug]: Double line code folding

### ISSUE THREAD

**Issue by kkost9** [mallowigi/material-theme-issues#133]
### Describe the bug

<img width="131" alt="image" src="https://user-images.githubusercontent.com/15065130/162916936-4f5f965e-75be-4361-8257-ccfdf6b4e163.png">

### To Reproduce

1. Open Code editor

### Expected behavior

single line

### Material Theme Version

7.3.0

### IDE

WebStorm

**Comment by mallowigi** [comment]
Probably related to Experimental UI. Closing
