### ISSUE TITLE
[Bug]: Accent mode forces itself on startup

### ISSUE THREAD

**Issue by Gurbii95** [mallowigi/material-theme-issues#134]
## Bug description

On startup of Webstorm the accent mode seems to be enabled even when it's not. This happens every time when starting webstorm for the first time regardless of the Material Theme UI settings. 

### general screenshots of the issue
![Screenshot 2022-04-14 at 09 28 42](https://user-images.githubusercontent.com/18457396/163337494-744a2f6d-ee16-4015-a7ee-9b3dfeb5204c.png)
![Screenshot 2022-04-14 at 09 28 11](https://user-images.githubusercontent.com/18457396/163337498-5eeab8fe-703b-49f6-aebb-f19d77f6655c.png)

### screenshots of the material theme ui settings
![Screenshot 2022-04-14 at 09 29 03](https://user-images.githubusercontent.com/18457396/163337593-2eedbd93-27ed-4e04-ab09-1c285607a43a.png)
![Screenshot 2022-04-14 at 09 28 57](https://user-images.githubusercontent.com/18457396/163337597-980e5c22-69bb-472a-837f-c4ad79899d1e.png)

## Temp fix
On startup when the issue occurs it seems to be fixable by fiddling around with contrast mode and contrast mode. Most of the time just disabling contrast mode and enabling accent mode fixes the issue. 
![Screenshot 2022-04-14 at 09 30 16](https://user-images.githubusercontent.com/18457396/163338276-1434beb5-479d-4cff-bf3e-68b96194c2f0.png)

### To Reproduce

1. Enable Material Theme UI and enable contrast mode and disable accent mode
2. Close webstorm
3. Re-open webstorm
4. Observe

### Expected behavior

Accent mode should not be 'enabled'.

### Material Theme Version

v7.3.0

### IDE

WebStorm

### System Info

```shell
WebStorm 2022.1
Build #WS-221.5080.193, built on April 10, 2022
Runtime version: 11.0.14.1+1-b2043.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 1024M
Cores: 6
Registry:
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    eslint.additional.file.extensions=svelte

Non-Bundled Plugins:
    org.jetbrains.plugins.localization (221.5080.126)
    net.seesharpsoft.intellij.plugins.csv (2.18.2)
    com.intellij.properties (221.5080.126)
    IdeaVIM (1.10.1)
    zielu.gittoolbox (212.8.9)
    mobi.hsz.idea.gitignore (4.4.0)
    mdx.js (1.0.221)
    dev.blachut.svelte.lang (0.22.0)
    com.intellij.lang.jsgraphql (3.1.3)
    com.github.iguissouma.nxconsole (0.41.0)
    com.github.etkachev.nxwebstorm (0.9.3)
    com.chrisrm.idea.MaterialThemeUI (7.3.0)
    com.mallowigi (60.0.0)
    com.atlassian.bitbucket.references (2022.1.200)
    Dart (221.5177)
    izhangzhihao.rainbow.brackets (6.21)
    CMD Support (1.0.5)
```

**Comment by mallowigi** [comment]
Are you using Settings Sync? Can you make sure that accentMode is disabled in your XML files?

**Comment by Gurbii95** [comment]
i've exported the settings sync with only materialtheme enabled and this was the output
```
<application>
  <component name="MaterialThemeConfig">
    <option name="highContrast" value="true" />
    <option name="premium" value="true" />
    <option name="borderedButtons" value="true" />
    <option name="compactDropdowns" value="true" />
    <option name="compactSidebar" value="true" />
    <option name="isHighContrast" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="useMaterialWallpapers" value="true" />
    <option name="indicatorStyle" value="None" />
    <option name="tabsHeight" value="42" />
    <option name="accentColor" value="ff9800" />
    <option name="selectedTheme" value="DARKER" />
    <option name="userId" value="-4d91cf25:16fc6dce273:-8000" />
    <option name="version" value="6.4.2.1" />
  </component>
</application>
```

**Comment by mallowigi** [comment]
Did you find this inside the `jba_config` directory ?

**Comment by Gurbii95** [comment]
Ah no, i exported my IDE settings and it showed different values. If i check the `jba_config` folder i get the following information. It does say accent mode is true however it doesn't seem to be in the ui settings? Set accent mode seems disabled in the ui and i can't click it whatsoever

```
<application>
  <component name="MaterialThemeConfig">
    <option name="compactStatusBar" value="true" />
    <option name="contrastMode" value="true" />
    <option name="accentMode" value="true" />
    <option name="compactSidebar" value="true" />
    <option name="isCompactStatusBar" value="true" />
    <option name="isContrastMode" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="overrideAccentColor" value="false" />
    <option name="indicatorStyle" value="None" />
    <option name="tabsHeight" value="42" />
    <option name="accentColor" value="ff9800" />
    <option name="selectedTheme" value="DARKER" />
    <option name="userId" value="-64207253:17988f324f0:-8000" />
    <option name="version" value="7.3.0" />
    <option name="stripedToolWindowsEnabled" value="true" />
  </component>
</application>
```

**Comment by mallowigi** [comment]
Are you sure you're not mistaking it with the accent color ?

https://material-theme.com/docs/configuration/features-settings/#accent-mode

Or, maybe you had it in one previous version and it is disabled because you're on free mode? It should be reset to false if you're not premium though.

**Comment by mallowigi** [comment]
That being said, the accent mode should not paint the tree window in accent color, so this is a bug that I need to fix nevertheless.

**Comment by Gurbii95** [comment]
My preferences, and the setting in the ui
![image](https://user-images.githubusercontent.com/18457396/163570249-235b27d6-df31-4dba-9eba-adc93a6f2719.png)
![image](https://user-images.githubusercontent.com/18457396/163570275-0cb777d1-d48c-43a1-bc26-df6333086a2f.png)

as you can see i'm not able to click on accent mode, might be the case that i used to have it on before it turned premium, i'm indeed a free user but have been using this plugin for years

**Comment by mallowigi** [comment]
So, you were using accent mode?

**Comment by braxtons12** [comment]
I'm encountering this on the latest stable versions of CLion and Rust Rover after enabling premium.

deleting the config files, changing options, etc. doesn't help. No matter what I do, any UI elements that are expanded/visible when the IDE is opened get hit with the secondary accent color.

E.g.:

![Image](https://github.com/user-attachments/assets/391b5cb4-cb1f-457b-8111-97003453871b)

**Comment by mallowigi** [comment]
Please open a new issue
