### ISSUE TITLE
[Bug]: Wrong navigation bar location [Wrong question]

### ISSUE THREAD

**Issue by LovesAsuna** [mallowigi/material-theme-issues#137]
### Describe the bug

Sometimes the navigation bar will not be displayed, sometimes it will be displayed below the window
![G4PUTWLDB4@F$H9 D$FBL5V](https://user-images.githubusercontent.com/32810896/163562087-7f398b88-5442-4119-8e13-18bc1e62c2f9.png)

### To Reproduce

1. The latest material ui plugin
2. Turn off and then turn off the navagiton bar

### Expected behavior

The navigation bar should be displayed above the window

### Material Theme Version

v7.3.0

### IDE

IntelliJ IDEA, WebStorm, PyCharm, DataGrip

### System Info

```shell
IntelliJ IDEA 2022.1 (Ultimate Edition)
Build #IU-221.5080.210, built on April 12, 2022
Licensed to Mirai-Bot / Loves Asuna
Subscription is active until October 31, 2022.
For non-commercial open source development only.
Runtime version: 11.0.14.1+1-b2043.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4056M
Cores: 16
Registry:
    ide.intellij.laf.enable.animation=true
    debugger.watches.in.variables=false
    ide.experimental.ui=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    org.jetbrains.plugins.go (221.5080.210)
    commit-template-idea-plugin (1.2.0)
    com.wakatime.intellij.plugin (13.1.14)
    com.tabnine.TabNine (0.6.0)
    com.robohorse.robopojogenerator (2.3.3)
    org.avaje.ebean11.enhancer (13.3.0)
    com.github.patou.gitmoji (1.8.1)
    com.github.copilot (1.1.16.1219)
    com.fwdekker.randomness (2.7.4)
    com.intellij.selenium (221.5080.154)
    mobi.hsz.idea.gitignore (4.4.0)
    com.mallowigi (61.0.0)
    jclasslib (6.0.4)
    com.demonwav.minecraft-dev (2022.1-1.5.19)
    com.jetbrains.php (221.5080.224)
    JRebelPlugin (2022.2.0)
    org.jetbrains.compose.desktop.ide (1.1.1)
    zielu.gittoolbox (212.8.9)
    izhangzhihao.rainbow.brackets (6.21)
    com.chrisrm.idea.MaterialThemeUI (7.3.0)
    cn.yiiguxing.plugin.translate (3.3-patch.1)
    ASM Bytecode Viewer (9.2)

Kotlin: 221-1.6.20-release-285-IJ5080.210
```

**Comment by mallowigi** [comment]
It's not wrong, it's the new layout. Please disable the "Experimental UI" option in the Settings, then restart.

**Comment by LovesAsuna** [comment]
However, though enable "Experimental UI" when using last version of material ui, there is no issue for this.

**Comment by mallowigi** [comment]
I suspect the issue is that the old setting for the Large Stripes enabled the Experimental UI automatically. I think I'll disable this for preventing further confusion.,
