### ISSUE TITLE
[Feature]: Black background theme

### ISSUE THREAD

**Issue by Birowsky** [mallowigi/material-theme-issues#140]
### Describe the feature

As in pitch black. Zero brightness coming from the background. Would be super sexy in dark environments on the new oled/miniled screens.

### Use Cases

In very dark environments, even the subtle light from the currently darkest themes is enough to put a strain on your eyes. Emitting no light from the background would be pretty darn nice.

### Material Theme Version

6.15.0 (licensed)

### IDE

WebStorm

**Comment by Birowsky** [comment]
It might be worth noting that there already is a black theme out there, but the aesthetics are god awful. I'm hoping for a sleek minimal black theme, just as you guys are able to deliver 💪

![](https://plugins.jetbrains.com/files/14059/screenshot_21477.png)

**Comment by mallowigi** [comment]
Closing this. You can make your own theme or use one of the ones available in the Marketplace.
