### ISSUE TITLE
[Bug]: File Status Colors Revert

### ISSUE THREAD

**Issue by takumiy** [mallowigi/material-theme-issues#142]
### Describe the bug

The colors set in File Status Colors are restored.
![スクリーンショット 2022-04-22 18 43 45](https://user-images.githubusercontent.com/8855351/164701598-bfb512ad-a14d-4308-848a-8ee323c894d0.png)

### To Reproduce

I'm using the Moonlight theme and the File Status Colors Unknown was set to 7AF8CA, 

![スクリーンショット 2022-04-22 17 58 48](https://user-images.githubusercontent.com/8855351/164679193-c56e0cad-ec71-4abd-919b-7c203cc28992.png)

so I reset it to D1675A with Restore DEFAULT. 

![スクリーンショット 2022-04-22 18 24 06](https://user-images.githubusercontent.com/8855351/164679642-9dcfbc8e-03e4-4aba-8451-68c03ebe40b6.png)

However, uncheck Override Accent Color from Theme,

![スクリーンショット 2022-04-22 18 43 28](https://user-images.githubusercontent.com/8855351/164681945-1b9581e2-4077-478a-83e5-d9c909187403.png)

 it will return to the original 7AF8CA.

![スクリーンショット 2022-04-22 18 43 45](https://user-images.githubusercontent.com/8855351/164681997-8592bccd-eb71-4faa-8f98-2f5b6dac398d.png)

### Expected behavior

I want to prevent the colors set in File Status Colors from being restored.

### Material Theme Version

7.3.2

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2022.1 (Ultimate Edition)
Build #IU-221.5080.210, built on April 12, 2022
Subscription is active until November 30, 2022.
For educational use only.
Runtime version: 11.0.14.1+1-b2043.25 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    IdeaVIM (1.10.1)
    com.mallowigi (62.0.0)
    com.haulmont.jpab (2022.2.1-221)
    com.chrisrm.idea.MaterialThemeUI (7.3.2)

Kotlin: 221-1.6.20-release-285-IJ5080.210
```

**Comment by mallowigi** [comment]
I couldn't be able to reproduce, unfortunately. However, please be aware that you shouldn't use the "File Status Colors" page to define the File Statuses, but rather the "Editor > Color Scheme > Custom File Colors" (see https://material-theme.com/docs/configuration/file-status-colors/)

Please try to use these settings and tell me if that issue reproduce. In any case I couldn't get the issue you encountered.

Note: Please be aware that this feature supposes that you're using the same theme and color scheme combination.

**Comment by takumiy** [comment]
I tried Custom File Colors and it worked.
Thank you for creating a wonderful theme!
