### ISSUE TITLE
[Bug]: file path disappears with experimental new UI

### ISSUE THREAD

**Issue by NextAlone** [mallowigi/material-theme-issues#144]
### Describe the bug

File path is lost
![image](https://user-images.githubusercontent.com/12210746/164953005-0be437b2-ed54-436a-97d8-a0f6ed5e9a78.png)

### To Reproduce

Just use the new UI

### Expected behavior

Show the file path

### Material Theme Version

v7.3.2

### IDE

IntelliJ IDEA, PyCharm

### System Info

```shell
IntelliJ IDEA 2022.1 (Ultimate Edition)
Build #IU-221.5080.210, built on April 12, 2022
Licensed to XXX
Subscription is active until November 26, 2022.
For non-commercial open source development only.
Runtime version: 11.0.15+10 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Linux 5.17.3-arch1-1
GC: G1 Young Generation, G1 Old Generation
Memory: 24576M
Cores: 12
Registry:
    external.system.auto.import.disabled=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    commit-template-idea-plugin (1.2.0)
    com.jetbrains.ChooseRuntime (1.2)
    com.intellij.plugins.vscodekeymap (221.5080.106)
    com.intellij.nativeDebug (221.5080.218)
    com.haojiyou.CharAutoReplace (1.6.0)
    com.github.copilot (1.1.17.1262)
    com.daniel-espinoza.inline-error (0.1.1)
    String Manipulation (9.4.0)
    gr.jchrist.gitextender (0.7.0)
    org.jetbrains.compose.desktop.ide (1.1.1)
    zielu.gittoolbox (212.8.9)
    com.mallowigi.colorHighlighter (10.0.0)
    com.chrisrm.idea.MaterialThemeUI (7.3.2)
    cn.yiiguxing.plugin.translate (3.3.1-patch.1)

Kotlin: 221-1.6.20-release-285-IJ5080.210
Current Desktop: Undefined
```

### Logs/Screenshots

```shell
Just in the top block
```

**Comment by mallowigi** [comment]
> As a result, the old setting has been removed, and temporarily replaced with a new setting to open this Experimental UI instead. However, we do NOT recommend using this UI as this is a largely buggy and highly suspect to change between new releases of the IDE. If you’re aware of the risks, you can try it, but don’t come complaining if there are issues.

https://material-theme.com/docs/what-s-new/#large-tool-windows-deprecation-and-experimental-ui
