### ISSUE TITLE
[Bug]: Tab Placement keeps resetting to top

### ISSUE THREAD

**Issue by linaori** [mallowigi/material-theme-issues#149]
### Describe the bug

Every time I set tab placement to "right", when Intellij starts up again it gets reset to top

### To Reproduce

1. Open settings
2. Go to Editor -> General -> Editor Tabs
3. Set Tab Placement to "Right"
4. Restart Intellij, tabs are back to top

### Expected behavior

Expected behavior is that the tab position isn't modified

### Material Theme Version

7.3.2

### IDE

IntelliJ IDEA

### System Info

```shell
Ubuntu 20.04.4 LTS

Build #IU-221.5080.210, built on April 12, 2022
Runtime version: 11.0.14.1+1-b2043.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

Enabled plugins (Downloaded):
.env files support (2022.1)
.ignore (4.4.0)
Apache config (.htaccess) (221.5080.126)
Makefile Language (221.5080.126)
Material Theme UI (7.3.2)
PHP (221.5080.224)
PHP Advanced AutoComplete (1.1.0)
PHP Annotations (8.2.0)
PHP Docker (221.5080.169)
Php Inspections (EA Extended) (4.0.7.1)
PHP Remote Interpreter (221.5080.169)
Psalm Support (221.5080.169)
Symfony Support (2022.1.224)
Twig (221.5080.126)

Enabled plugins (Internal):
Database Tools and SQL (221.5080.210)
Docker (221.5080.210)
FTP/SFTP Connectivity (ex. Remote Hosts Access) (221.5080.210)
HTML Tools (221.5080.210)
XPathView + XSLT (221.5080.210)
IDE Settings Sync (221.5080.210)
Settings Repository (221.5080.210)
Settings Sync (221.5080.210)
JavaScript and TypeScript (221.5080.210)
Markdown (221.5080.210)
Shell Script (221.5080.210)
YAML (221.5080.210)
OpenAPI Specifications (221.5080.210)
CSS (221.5080.210)
ChangeReminder (221.5080.210)
Git (221.5080.210)
GitHub (221.5080.210)
EditorConfig (221.5080.210)
Grazie (221.5080.210)
IDE Features Trainer (221.5080.210)
IDE Features Trainer: Git Lessons (221.5080.210)
IntelliLang (221.5080.210)
Machine Learning Code Completion (221.5080.210)
Machine Learning in Search Everywhere (221.5080.210)
Shared Project Indexes (221.5080.210)
Task Management (221.5080.210)
Terminal (221.5080.210)
```

**Comment by mallowigi** [comment]
Are you using the Experimental UI by any chance ?

**Comment by linaori** [comment]
I have the same tab issue on Windows 11, and both are indeed using  the Experimental UI

**Comment by linaori** [comment]
The option is inside the plugin, is it just a toggle for a hidden option in the IDE? If so I can report it somewhere else instead

**Comment by mallowigi** [comment]
This is a work in progress used by JB's developers, so this is not something open to the public.

There are a few regressions but that's something to be expected when working on a new UI.

Please don't report anything for something experimental, it will only bother them (and possibly block access to it)

**Comment by linaori** [comment]
Alright, thanks for the update!
