### ISSUE TITLE
[Bug]: In the new version v7.4.0, in idea, the code prompts that the background of the current line in the background board is invalid.

### ISSUE THREAD

**Issue by AprilViolet** [mallowigi/material-theme-issues#151]
### Describe the bug

Hello author, in the new version v7.4.0, in idea, the code prompts that the background of the current line in the background board is invalid.

### To Reproduce

1. If you close the plug-in,you can see that a line selected in the prompt box will be marked with background color

<img width="497" alt="Snipaste_2022-05-07_11-05-33" src="https://user-images.githubusercontent.com/40155496/167236626-0a923219-2bfb-44e9-8d7f-2f525fcd10a0.png">

2. When I open the plug-in and the version is in v7.3.2, I can see that there is still color discrimination, although its color becomes dimmer

<img width="779" alt="Snipaste_2022-05-07_11-09-13" src="https://user-images.githubusercontent.com/40155496/167236662-dd777d8e-3b13-46dd-8964-5a4574a15518.png">

3. However, when I update to the latest version v7.4.0, the background color disappears. Whether I press the up arrow key or the down arrow key, there is still no color prompt

<img width="822" alt="Snipaste_2022-05-07_11-06-46" src="https://user-images.githubusercontent.com/40155496/167236727-d5a6c3a3-d4b0-4011-8a34-d3f75b2c9435.png">

### Expected behavior

The background color of the current line in the prompt version can be displayed normally.And is there a way to customize the color, not the whole background, but the background color of a line selected in the prompt box?

### Material Theme Version

v7.4.0

### IDE

IntelliJ IDEA

**Comment by mallowigi** [comment]
I see, this a combination of two settings that got jumbled, basically "Inverted Selection Color" and "Contrast Color".

I'll try to issue a fix when I can, but in the meantime please either disable the inverted selection color or enable the contrast color.

Thanks

**Comment by mallowigi** [comment]
fixed
