### ISSUE TITLE
[Bug]: Material conflicts with the Zen View mode of IDEA

### ISSUE THREAD

**Issue by EmptyDreams** [mallowigi/material-theme-issues#152]
### Describe the bug

When I enter "Zen Mode", the background will be solid black when a window pops up.

Even if I go back to normal mode, the problem persists and the IDE needs to be restarted to return to normal.

The effect is shown below:

![QQ图片20220509170539](https://user-images.githubusercontent.com/44894906/167378771-4463c394-4832-4086-b632-ccb0443ee741.png)

![QQ图片20220509170930](https://user-images.githubusercontent.com/44894906/167378781-299bcea0-e10b-4e3c-9ec2-4994cac60bdf.png)

This is the log:

[idea.log](https://github.com/mallowigi/material-theme-issues/files/8650322/idea.log)

### To Reproduce

1. enter "Zen mode"
2. Open a form randomly (e.g., Settings)

### Expected behavior

The background was supposed to be a translucent mask, but it was plain black

### Material Theme Version

v7.4.1

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2022.1 (Ultimate Edition)
Build #IU-221.5080.210, built on April 12, 2022
Licensed to ***
订阅有效期至 2023年1月3日。
For educational use only.
Runtime version: 11.0.14.1+1-b2043.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
    debugger.watches.in.variables=false
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    ide.images.show.chessboard=true

Non-Bundled Plugins:
    com.intellij.zh (221.179)
    Statistic (4.1.10)
    Key Promoter X (2022.1.1)
    com.jetbrains.plugins.jade (221.5080.169)
    com.mallowigi (64.0.0)
    com.chrisrm.idea.MaterialThemeUI (7.4.1)
    com.demonwav.minecraft-dev (2022.1-1.5.19)
    cn.yiiguxing.plugin.translate (3.3.1-patch.1)

Kotlin: 221-1.6.20-release-285-IJ5080.210
```

**Comment by mallowigi** [comment]
It's a feature of the plugin named Overlays. You can disable it in the settings
