### ISSUE TITLE
[Bug]: Project View custom font does not get applied in IntelliJ IDEA 2021.3

### ISSUE THREAD

**Issue by Rainyun** [mallowigi/material-theme-issues#153]
### Describe the bug

Summary：
The Project View custom font settings do not get applied in IntelliJ IDEA 2021.3

Expected behavior：
The Project View font is Roboto with 20pt size.

Actual behavior：
The Project View font stays the default font & size.

![image](https://user-images.githubusercontent.com/49849992/167896043-cae704ac-f151-4d74-a78c-a8aa21f1a348.png)

The Tab custom font is applying, but not for the Project View Font. 
![QQ截图20220512001307](https://user-images.githubusercontent.com/49849992/167898494-a2e0f075-d0fc-4337-b05a-fc0fad108de2.png)

### To Reproduce

1. Set the font of the The Project View to Roboto with 20pt size.
2. restart the IntelliJ IDEA
3. The Project View font stays the default font & size.

### Expected behavior

The Project View font is Roboto with 20pt size.

### Material Theme Version

v6.16.2

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2021.3.3 (Ultimate Edition)
Build #IU-213.7172.25, built on March 16, 2022
Licensed to XXX
You have a perpetual fallback license for this version.
Subscription is active until December 31, 2025.
Runtime version: 11.0.14.1+1-b1751.46 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1024M
Cores: 4
Registry:
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    ideanginx9 (0.1.9)
    org.jetbrains.kotlin (213-1.6.21-release-334-IJ6777.52)
    com.alibaba.p3c.smartfox (2.1.1)
    mobi.hsz.idea.gitignore (4.4.0)
    JRebelPlugin (2022.2.1)
    jr-mp-ide-idea (0.0.4)
    izhangzhihao.rainbow.brackets (6.23)
    com.ccnode.codegenerator.MyBatisCodeHelperProMarketPlace (2.9.9-183-204)
    MyBatisLog (2022.5.1)
    com.chrisrm.idea.MaterialThemeUI (6.16.2)
    cn.yiiguxing.plugin.translate (3.3.1-patch.1)

Kotlin: 213-1.6.21-release-334-IJ6777.52
```

### Logs/Screenshots

```shell

```

**Comment by mallowigi** [comment]
Sorry, the 2021 versions are not supported anymore. Please update to 2022 as soon as you can. It should be working there.
