### ISSUE TITLE
[Bug]: `Deleted ignored line below` not appear

### ISSUE THREAD

**Issue by Syafiqq** [mallowigi/material-theme-issues#156]
### Describe the bug

It is hard to detect ignored deleted lines, it turns out the setting seems not working, tried to re-tick the option, change the color, it doesnt work.

<img width="986" alt="Screenshot 2022-05-15 at 12 04 09 PM" src="https://user-images.githubusercontent.com/9932470/168458105-7c24bc18-055d-4d03-aed8-58fa664f079f.png">

<img width="1377" alt="Screenshot 2022-05-15 at 12 07 10 PM" src="https://user-images.githubusercontent.com/9932470/168458134-3e163a2d-f80e-411e-911a-a7c77684f83f.png">

### To Reproduce

1. Delete some lines in the editor
2. Move the change into another changelist `Move Files to Another Changelist...`

### Expected behavior

Maybe it should be outlined reddish color, the same color with the solid one

### Material Theme Version

v7.5.0

### IDE

Other (AppCode, CLion, GoLang...)

### System Info

```shell
AppCode 2022.1.1
Build #OC-221.5591.52, built on May 11, 2022
Runtime version: 11.0.14.1+1-b2043.45 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 3016M
Cores: 8
Registry:
    ide.experimental.ui=true
    max.suggested.heap.size=8192
    ide.balloon.shadow.size=0
    ide.images.show.chessboard=true

Non-Bundled Plugins:
    com.github.tom-power.close-tab-left-right (1.1.1)
    com.chrisrm.idea.MaterialThemeUI (7.5.0)
    String Manipulation (9.4.0)
    GrepConsole (12.12.211.6693.0)
    zielu.gittoolbox (212.8.9)
```

**Comment by mallowigi** [comment]
Don't open bugs on experimental ui
