### ISSUE TITLE
[Bug]: i can't open webstorm

### ISSUE THREAD

**Issue by iFTY-R** [mallowigi/material-theme-issues#159]
### Describe the bug

can't open webstorm

### To Reproduce

can't open webstorm

### Expected behavior

can't open webstorm

### Material Theme Version

v7.5.0

### IDE

WebStorm

**Comment by mallowigi** [comment]
can you provide more information: OS, plugins you use, and your local settings ?

**Comment by iFTY-R** [comment]
window11，material theme ui:   v7.5.0



---- Replied Message ----
| From | Elior ***@***.***> |
| Date | 05/17/2022 16:58 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [mallowigi/material-theme-issues] [Bug]: i can't open webstorm (Issue #159) |

can you provide more information: OS, plugins you use, and your local settings ?

**Comment by iFTY-R** [comment]
window11，webstorm 2022.1.1，plugin :  material theme ui 7.5.0



---- Replied Message ----
| From | ***@***.******@***.***> |
| Date | 05/17/2022 19:54 |
| To | ***@***.***> |
| Cc | |
| Subject | Re: [mallowigi/material-theme-issues] [Bug]: i can't open webstorm (Issue #159) |
window11，material theme ui:   v7.5.0



---- Replied Message ----
| From | Elior ***@***.***> |
| Date | 05/17/2022 16:58 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [mallowigi/material-theme-issues] [Bug]: i can't open webstorm (Issue #159) |

can you provide more information: OS, plugins you use, and your local settings ?

**Comment by mallowigi** [comment]
What about the local settings?

**Comment by mallowigi** [comment]
Closing cause duplicate
