### ISSUE TITLE
[Bug]: Webstorm 2022.1.1 cannot be opened normally

### ISSUE THREAD

**Issue by moka12579** [mallowigi/material-theme-issues#162]
### Describe the bug

Version 2022.1.1 of webstorm cannot be opened after installing versions 7.5.0 and 7.4.1 of material theme UI. However, it can be opened normally after installing version 7.5.0 of material theme UI in version 2021.3.3 of webstorm
logs:
[idea.log](https://github.com/mallowigi/material-theme-issues/files/8712513/idea.log)

### To Reproduce

1. Install version 2022.1.1 of webstorm

2. Install the material theme UI plug-in in the plug-in of webstorm settings

3. Restart webstorm

4. It will be stuck in the following interface
![截屏2022-05-17 18 19 14](https://user-images.githubusercontent.com/71615766/168933902-16d54c72-1f18-4dab-a540-5ad657e16d7b.png)

### Expected behavior

open

### Material Theme Version

v7.5.0

### IDE

WebStorm

### System Info

```shell
macOS Monterey 12.4 M1
```

**Comment by mallowigi** [comment]
Duplicate. But as I mentioned in the other issue, do you think you'll be able to help me find the issue by connecting on the slack channel? That would be great
