### ISSUE TITLE
[Bug]: Experimental UI not working on 2022.1.2

### ISSUE THREAD

**Issue by gerryhjs** [mallowigi/material-theme-issues#167]
### Describe the bug

Experimental UI not working on 2022.1.2

### To Reproduce

Update version to idea 2022.1.2

### Expected behavior

Experimental UI should work when turn on it.

### Material Theme Version

v7.5.0.3

### IDE

IntelliJ IDEA

**Comment by mallowigi** [comment]
Seems like access to experimental ui has been revoked. I'll try to find a fix but you should go to a previous version of the ide in the meantime
