### ISSUE TITLE
[Bug]: The width of tab underline color changed after scroll.

### ISSUE THREAD

**Issue by gerryhjs** [mallowigi/material-theme-issues#168]
### Describe the bug

The width of tab underline color changed after scroll.

### To Reproduce

Scroll editor when using IDE.

### Expected behavior

The width of tab underline color should not changed.

### Material Theme Version

v7.5.0.3

### IDE

IntelliJ IDEA

**Comment by mallowigi** [comment]
Can you provide screenshots? I'm not sure I understand

**Comment by gerryhjs** [comment]
![image](https://user-images.githubusercontent.com/45413498/171563260-2b24346d-b002-4eca-ad2c-65bbc7feb506.png)
before scroll

**Comment by gerryhjs** [comment]
![Uploading image.png…]()
after scroll

**Comment by gerryhjs** [comment]
![image](https://user-images.githubusercontent.com/45413498/171563436-726fc9f2-eb26-4d1d-894f-b542bbe63a84.png)
after scroll

**Comment by gerryhjs** [comment]
you can see the width become thinner @mallowigi

**Comment by mallowigi** [comment]
Please disable the tab shadow feature

**Comment by gerryhjs** [comment]
![image](https://user-images.githubusercontent.com/45413498/171563959-6496029c-7e53-44d3-b24a-1b24fac32039.png)
@mallowigi I didnt turn on it.

**Comment by gerryhjs** [comment]
I am using custom theme now , but same things happend on orginal theme in plugin. I use duracal(material) test again.

**Comment by mallowigi** [comment]
I still don't see the problem in the screenshot, but in any case I'll take a look and see if I see something

**Comment by gerryhjs** [comment]
@mallowigi the line under tab width changed become thinner. I will use width 1 to test again so you an see it more clear.

**Comment by gerryhjs** [comment]
![image](https://user-images.githubusercontent.com/45413498/171564660-0a15fdbd-67cb-4af4-bf88-657966b5a698.png)
after scroll ->
![image](https://user-images.githubusercontent.com/45413498/171564682-3838724a-3b19-4bce-9af7-ef25983ca79c.png)
