### ISSUE TITLE
[Feature]: replace custom file type icon to a better icon

### ISSUE THREAD

**Issue by gerryhjs** [mallowigi/material-theme-issues#169]
### Describe the feature

![image](https://user-images.githubusercontent.com/45413498/171564898-80761107-58da-484c-b91f-a4d82318a6c0.png)
This icon is to ugly in IDE when using experiment UI. Maybe can change a better icon.

### Material Theme Version

v7.5.0.3

### IDE

IntelliJ IDEA

**Comment by mallowigi** [comment]
Sorry, this plugin will not change icons.

**Comment by gerryhjs** [comment]
@mallowigi  When I using expriement UI the icon changed. Is it a bug?

**Comment by mallowigi** [comment]
It's a limitation of the atom plugin. If you want to use the exp ui icons you'll have to remove the plugin

**Comment by gerryhjs** [comment]
@mallowigi  can i disable the icon change when use the exp ui?

**Comment by gerryhjs** [comment]
I didnt install the atom plugin but my icon still changed when using exp ui.

**Comment by mallowigi** [comment]
Reopening to investigate but this is odd because the material
Theme doesn't change icons

**Comment by mallowigi** [comment]
I've looked and I don't understand what is the issue. With and without the experimental UI the icons is the same. Can you show me what icon you expect? Not that I'm going to do anything about it because as I said, this plugin doesn't change icons, but I'm curious nonetheless.

**Comment by gerryhjs** [comment]
As you can see in screenshot ,  the icon changed when turn on exp UI (I didnt install atom icon plugin)
![image](https://user-images.githubusercontent.com/45413498/172077016-e6606703-b6da-4489-8e64-5cbfddff5373.png)

**Comment by mallowigi** [comment]
I think I understand now: what you see are the icons that JetBrains made. They are replacing them little by little, but a lot of the older icons still remain. That's why the "cpp" icon is still untouched.

**Comment by gerryhjs** [comment]
Yes and Also I dont know is it a feature icon are changed when turn on exp UI.
