### ISSUE TITLE
Integrate with New UI Plugin

### ISSUE THREAD

**Issue by mallowigi** [mallowigi/material-theme-issues#171]
Need to deprecate the "Experimental UI" once the New UI plugin becomes public :)

—

Created via [Raycast](https://www.raycast.com?ref=signatureGithub)

**Comment by nesl247** [comment]
As someone who likes the material theme but also wants to try out the new ui and has access to the new plugin, is there any incompatibilities between using the two? Do we not need both? I'm not sure what the `New UI` plugin does vs. enabling the `Experimental UI` option.

**Comment by mallowigi** [comment]
Both are doing the same thing internally but all in all the new ui plugin is aligned with the experimental ui code, whereas the material ui plugin is doing extra work to make it work.

Since the new ui is still in alpha and not generally available it's still preferable to use the option from MUI settings but eventually the option will disappear on behalf of the new ui settings.
