### ISSUE TITLE
[Bug]: When using other plugin theme with material theme UI, the editor schema will be set to darcula, not the schema relate to it.

### ISSUE THREAD

**Issue by gerryhjs** [mallowigi/material-theme-issues#176]
### Describe the bug

[Bug]: When using other plugin theme with material theme UI, the editor schema will be set to darcula, not the schema relate to it.

### To Reproduce

Change a theme to other plugins theme

### Expected behavior

the editor schema will be set to schema relate to it.

### Material Theme Version

V7.5.2

### IDE

IntelliJ IDEA

**Comment by gerryhjs** [comment]
Solved after reboot IDE. Closed it.

**Comment by mallowigi** [comment]
Good catch! I'll try to fix asap.

**Comment by mallowigi** [comment]
Fixed in 7.5.2.1
