### ISSUE TITLE
[Bug]: Overlay stays open when popup is kept alive and only visually hidden

### ISSUE THREAD

**Issue by philipp-spiess** [mallowigi/material-theme-issues#179]
### Describe the bug

We're working on an improved version of [Sourcegraph for JetBrains](https://github.com/sourcegraph/sourcegraph/tree/main/client/jetbrains). We're making use of the JBCef web view inside of a custom popover and realized pretty early that there are quite some bugs with web views on macOS. Our biggest one is [described here](https://github.com/sourcegraph/sourcegraph/issues/34773).

To work around these bugs and ensure a snappy experience when our users re-open the Sourcegraph window, the popup is kept in memory while "closed". As such, we only change the UI visibility (`popup.setUiVisible(false);`) but don't call any dispose functionality. This is the only version we found that would allow the behavior we wanted.

When we try our extension with the material UI theme, however, we now run into the issue that the overlay does not close anymore. This is because the theme listens for `WindowEvent.WINDOW_CLOSING` events to hide the overlay but _our window is never closed_. I believe this is the same issues as the one reported in #26.

As a first workaround, we tried to manually fire the `WINDOW_CLOSING` event for the created popup window. However [we had to revert this](https://github.com/sourcegraph/sourcegraph/pull/36738) quickly after because testing concluded that this brings back the web view issues we had earlier. Somehow the web view must also be doing _something_ when the window closing event is sent 🙁.

I tried another workaround where instead of closing _our popup's window_, I created a throwaway popup and closed that. This does not seem to work though, I suppose that the material UI theme is waiting for all created windows to close.

One thing that would work is to listen for focus events on the main window. Whenever we focus the window, we _do not want to show an overlay anyways_. I think this would fix the issue but would also mean that we will not show an overlay again when the Sourcegraph window is re-activated.

Perhaps it is possible to create a custom event that we can fire off from inside the Sourcegraph extension to indicate that the modal is hiding or detect when the UiVisible prop is changed?

We also track the issue in our repo: https://github.com/sourcegraph/sourcegraph/issues/36479 cc @vdavid

### To Reproduce

1. Download an early preview of our new JetBrains extension from [here](https://drive.google.com/file/d/1AF0RlcwY0spbsEeRmReWYV4poCIsbyyC/view?usp=sharing).
2. Install the extension from your local file directory.
3. Open the Sourcegraph popover (`alt+a`)
4. Close it (`esc`)
5. Observe that the overlay stays active.

### Expected behavior

The overlay should close.

### Material Theme Version

v7.5.2.1

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2022.1.1 (Community Edition)
Build #IC-221.5591.52, built on May 10, 2022
Runtime version: 11.0.14.1+1-b2043.45 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.2.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Registry:
    ide.intellij.laf.enable.animation=true
    ide.browser.jcef.debug.port=9229
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    com.sourcegraph.jetbrains (1.2.4)
    com.mallowigi.idea (18.1.0)
    com.chrisrm.idea.MaterialThemeUI (7.5.2.1)

Kotlin: 221-1.6.21-release-337-IJ5591.52
```

### Logs/Screenshots

![image](https://user-images.githubusercontent.com/2552265/171651791-fe213d98-3c8f-45d5-9c80-f8cebebbe363.png)

**Comment by mallowigi** [comment]
Do you think you can add the plugin as a dependency for source graph? This way you can fire the custom events the plugin provides?

**Comment by philipp-spiess** [comment]
> Do you think you can add the plugin as a dependency for source graph? This way you can fire the custom events the plugin provides?

As-in bundle the jar? I don't think it makes sense to do, that would create a lot of headache when we have to upgrade versions I fear.

**Comment by philipp-spiess** [comment]
I think there's something like a [message bus built into JetBrains](https://plugins.jetbrains.com/docs/intellij/messaging-infrastructure.html). Is this something we could use instead?

**Comment by philipp-spiess** [comment]
Hm that would need a shared `Topic` instance. Maybe what we can do is create a shared dependency that only provides this `Topic`?

**Comment by philipp-spiess** [comment]
> I'm not particularly knowledgeable about creating libraries though.

Yeah me neither but I can look into it if we think this makes sense!

>  But perhaps you could check for a listener that would make sense for both of us.

Sorry I’m not sure what listener you refer to? 

I see that we already have an action to hide the popover. Perhaps I can access this via the [`ActionManager`](https://intellij-support.jetbrains.com/hc/en-us/community/posts/206773025-How-to-trigger-IntelliJ-actions-from-plugin-). Do you know what the ID is?

**Comment by mallowigi** [comment]
After pondering a bit, I couldn't find a way to add "orphan overlays" (e.g. overlays without a window). Since I don't want to introduce issues at this point, I think we can go with your solution. Like I said before, it's not a big deal if subsequent opens of the sourcegraph window doesn't add overlays. In fact, there are a few windows that do not trigger an overlay, such as the Find in Files, and I couldn't find a way to do so.

So I'm closing this. Good luck!
