### ISSUE TITLE
[Bug]: Search everywhere input text width is too narrow

### ISSUE THREAD

**Issue by gerryhjs** [mallowigi/material-theme-issues#184]
### Describe the bug

Search everywhere input text width is too narrow. Please see screenshot.
I didnt turn on compact text options.

### To Reproduce

double tap shift

### Expected behavior

Search everywhere input text can see clear.

### Material Theme Version

V7.5.2.2

### IDE

IntelliJ IDEA

**Comment by gerryhjs** [comment]
![abcdefgggg](https://user-images.githubusercontent.com/45413498/173330636-6b066ae4-645f-4bb4-a5f2-486ebef7da28.png)

**Comment by gerryhjs** [comment]
when tab the letter like 'g' or 'j' search everywhere cannot see the full letter.

**Comment by gerryhjs** [comment]
After I turn on "old material style" it works well.
![image](https://user-images.githubusercontent.com/45413498/173330997-1364d99e-3f50-4d2a-b31b-74605289d61c.png)

**Comment by mallowigi** [comment]
disable the compact fields option if that is an issue.

**Comment by gerryhjs** [comment]
@mallowigi  any possibility to solve it for 2021.1? Thanks.

**Comment by mallowigi** [comment]
I am not able to reproduce, can you share your settings?

**Comment by gerryhjs** [comment]
@mallowigi 
![image](https://user-images.githubusercontent.com/45413498/173509281-9472f615-a520-4b26-8c13-79501aafb0a7.png)
![image](https://user-images.githubusercontent.com/45413498/173509336-4aad7800-2caf-45b6-ae73-4c290e02c4df.png)
![image](https://user-images.githubusercontent.com/45413498/173509414-f29c05ba-bfe8-4dea-97f6-1b9968bfbf4d.png)

**Comment by gerryhjs** [comment]
I dont think this bug is related to setting. I have reset my setting to default and same things happened again.

**Comment by gerryhjs** [comment]
Use "old material style" can avoid it. Closed.
