### ISSUE TITLE
[Bug]: GUI buttons missing

### ISSUE THREAD

**Issue by nanohard** [mallowigi/material-theme-issues#185]
### Describe the bug

Buttons are missing from both the file tabs (the `x` to close the file)
as well as the IDE buttons for Run, Debug, etc and git buttons and buttons on for the DataGrip plugin
and along the bottom/side for panels (ie: Project, Commit, Terminal, etc)
for Webstorm 2022.

Using Webstorm 2022.1.2 and Material Theme UI Freemium 7.5.2.2
![image](https://user-images.githubusercontent.com/10169206/173432049-f58390ff-c00c-4664-b2b0-0063c91c2340.png)

Using Webstorm 2021.3.3 and Material Theme UI Freemium 6.16.2
![image](https://user-images.githubusercontent.com/10169206/173432194-92d280c2-45d0-4349-a3b2-206df18d1a3c.png)

### To Reproduce

Install latest stable Material Theme UI on latest stable Webstorm 2022.

### Expected behavior

IDE buttons should be showing.

### Material Theme Version

v7.5.2.2

### IDE

WebStorm

### System Info

```shell
WebStorm 2022.1.2
Build #WS-221.5787.30, built on May 31, 2022
Runtime version: 11.0.15+10-b2043.56 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.41-1-manjaro
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
    ide.intellij.laf.enable.animation=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    com.intellij.database (221.5787.30)
    com.chrisrm.idea.MaterialThemeUI (7.5.2.2)

Current Desktop: KDE
```

**Comment by nanohard** [comment]
It should be noted that as soon as Webstorm 2022 came out and I tried it with Material Theme UI Freemium, I have had this issue.

**Comment by mallowigi** [comment]
I can't reproduce. Can you check if you have the setting enabled?

**Comment by mallowigi** [comment]
Also, can you please share your settings and logs?

**Comment by mallowigi** [comment]
I just realized that you have the Atom Material Icons plugin installed even though you didn't mention it in the System Info.

**Comment by nanohard** [comment]
You're a legend!
Disabling Atom Material Icons (bundled with the IDE) solved the issue!
