### ISSUE TITLE
[Bug]: Loosing theme when switching between Windows and MacOS

### ISSUE THREAD

**Issue by benjaminrobinet** [mallowigi/material-theme-issues#186]
### Describe the bug

Hello!

I use plugin sync between my instances of IDEA. When I switch to Windows, it looks like the selected theme won't change, but when I switch back to my Mac, I loose the selected theme. I have to switch to another theme and the switch back to the previous theme.

### To Reproduce

1. Enable sync
2. Select theme on Mac
3. Open IDEA on Windows
4. Open IDEA on Mac

### Expected behavior

Keep same theme configuration between installations of IDEA.

### Material Theme Version

v7.5.2

### IDE

IntelliJ IDEA, WebStorm, PHPStorm

### System Info

```shell
Build #IU-221.5787.30, built on May 31, 2022

Licensed to Benjamin Robinet
Subscription is active until July 6, 2022.

Runtime version: 11.0.15+10-b2043.56 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
```
**I do not have access to my Windows computer for now**

**Comment by mallowigi** [comment]
I'm sorry but I can't control how sync works. Please open issues to JetBrains.
