### ISSUE TITLE
[Bug]: Devtools becomes invisible when mouse dragging

### ISSUE THREAD

**Issue by SamuelDiasFerreira** [mallowigi/material-theme-issues#189]
### Describe the bug

This bug happens on DevTools browser. In my case I am using Opera.
When there is a user behavior of "holding the left mouse button and dragging", for example:

- Resizing the width of Devtools
- Resizing the height os Devtools CSS Section
- Dragging the timeline of the Devtools Animations Section
- Selecting time range of Devtools Performance Section

The entire Devtools becomes "blank" with invisible content.

![issue](https://user-images.githubusercontent.com/38494332/175016118-b7a44c1f-905e-4e22-81f4-d0fb46256784.png)

### To Reproduce

1. Open devtools browser
2. Mouse hover a devtools draggable area
4. Mouse drag the draggable area
5. The entire devtools will become invislble
6. When releasing the dragging the devtools will become visible again

### Expected behavior

Don't hide the devtools content when mouse dragging.

### Material Theme Version

v7.2.2

### IDE

Other (AppCode, CLion, GoLang...)

### System Info

```shell
Windows 10
Opera Browser
```

**Comment by mallowigi** [comment]
I know about this issue but I have no idea how to fix that. You're welcome to propose a solution.

**Comment by mallowigi** [comment]
Oh oops wrong repo.
