### ISSUE TITLE
[Bug]: Github Dark Theme Highlighting box not showing up

### ISSUE THREAD

**Issue by oyhngithub** [mallowigi/material-theme-issues#190]
### Describe the bug

Highlighting box is not showing up after upgrade from 7.5.0.3 to 7.5.2.2 on both IDEA and GoLand.
<img width="712" alt="Xnip2022-06-25_23-35-22" src="https://user-images.githubusercontent.com/32537123/175780500-fba15ff2-9c62-44ad-9b56-d874cf5fff02.png">

### To Reproduce

1. Install  Material Theme UI Plugin  7.5.2.2 
2. Choose Dark Themes -> Github Dark Theme
3. Open source code(Java or Go), click a variable and see what happens

### Expected behavior

Highlighting box before the upgrading.
<img width="734" alt="Xnip2022-06-25_23-38-59" src="https://user-images.githubusercontent.com/32537123/175780675-4fd8c020-7504-4f87-90cd-fca7b9956c0b.png">

### Material Theme Version

7.5.2.2

### IDE

IntelliJ IDEA, Other (AppCode, CLion, GoLang...)

### System Info

```shell
GoLand 2022.1.3
Build #GO-221.5921.26, built on June 22, 2022
Runtime version: 11.0.15+10-b2043.56 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6.5
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
    suggest.all.run.configurations.from.context=true
    ide.completion.variant.limit=500
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    com.chrisrm.idea.MaterialThemeUI (7.5.2.2)
    com.mallowigi (64.0.0)
```

**Comment by mallowigi** [comment]
Closing this - This is the default behavior for all the bundled themes.
