### ISSUE TITLE
[Feature]: Define themes corresponding to system dark/light mode

### ISSUE THREAD

**Issue by Lootwig** [mallowigi/material-theme-issues#191]
### Describe the feature

I will buy a license as soon as this plugin supports theme switching along with system dark/light mode (without an IDE restart)!

### Material Theme Version

v7.5.2.2

### IDE

IntelliJ IDEA

**Comment by mallowigi** [comment]
This feature is built-in in the IDE.

**Comment by Lootwig** [comment]
Lucky you! License purchased.
