### ISSUE TITLE
[Bug]: Narrow field

### ISSUE THREAD

**Issue by clabough** [mallowigi/material-theme-issues#199]
### Describe the bug

The Font size and Line height text boxes in settings are very narrow and do not display the full text within them.

![image](https://user-images.githubusercontent.com/5217044/179443888-2c79af7b-bc3b-453e-8fd7-2bfaa7b114d5.png)

### To Reproduce

Go to Settings -> Editor -> (Font or Color Scheme -> Font) to view the narrow box size.

### Expected behavior

Display the full text in the boxes.

### Material Theme Version

v7.5.4

### IDE

Rider

### System Info

```shell
JetBrains Rider 2022.1.2
Build #RD-221.5787.36, built on June 1, 2022
Licensed to Washington State University / Shawn Clabough
Subscription is active until October 20, 2022.
Runtime version: 11.0.15+10-b2043.56 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
.NET Framework 4.0.30319.42000
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 12
Registry:
    ide.balloon.shadow.size=0
    indexing.enable.entity.provider.based.indexing=false
    rdclient.asyncActions=false
    ide.new.project.model.index.case.sensitivity=true

Non-Bundled Plugins:
    fr.socolin.application-insights-debug-log-viewer (1.5.1)
    com.samdark.intellij-visual-studio-code-dark-plus (2.6)
    com.markskelton.one-dark-theme (5.6.0)
    com.gmike.visual-studio-2019-dark (1.5.3)
    com.chrisrm.idea.MaterialThemeUI (7.5.4)
    com.mallowigi (64.0.0)
```

### Logs/Screenshots

```shell
![image](https://user-images.githubusercontent.com/5217044/179443854-f69247e3-5d7c-45a5-acba-b95791ca56db.png)

```

**Comment by mallowigi** [comment]
![CleanShot 2022-07-18 at 11 30 48](https://user-images.githubusercontent.com/5015756/179473364-c553056e-400a-45e7-8b10-4a1652e20f1c.png)

I am not able to reproduce at the moment, maybe it's a windows issue.
