### ISSUE TITLE
[Bug]: UnsupportedClassVersionError wih default bundled IntelliJ Runtime JDK

### ISSUE THREAD

**Issue by dtrunk90** [mallowigi/material-theme-issues#204]
### Describe the bug

Current IntelliJ version is bundled with JDK 11 (55.0) while classes of this plugin are compiled with JDK 17 (61.0).
When using the default bundled JDK this plugin fails to initialize.

Current workaround is to install and use a JDK >= 17.

### To Reproduce

1. See https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under to make sure the current Boot Java Runtime for the IDE is set to default (11.0.16 here)
2. Run IntelliJ with Material Theme UI plugin enabled and wait for the error message dialog

### Expected behavior

This plugin should work with the default bundled JDK.

### Material Theme Version

v7.7.1

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2022.2 (Ultimate Edition)
Build #IU-222.3345.118, built on July 26, 2022
Licensed to ...
You have a perpetual fallback license for this version.
Subscription is active until ...
Runtime version: 11.0.16+8-post-Ubuntu-0ubuntu120.04 amd64
VM: OpenJDK 64-Bit Server VM by Ubuntu
Linux 5.4.0-122-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2000M
Cores: 8
Registry:
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    com.jetbrains.ChooseRuntime (1.2)
    org.sonarlint.idea (6.8.0.50884)
    com.mallowigi (65.1.0)
    com.github.jk1.ytplugin (2022.1.212)

Kotlin: 222-1.7.10-release-334-IJ3345.118
Current Desktop: Budgie:GNOME
```

### Logs/Screenshots

```shell
Plugin 'com.chrisrm.idea.MaterialThemeUI' failed to initialize and will be disabled. Please restart IntelliJ IDEA.

java.lang.UnsupportedClassVersionError: com/mallowigi/idea/MTHackComponent has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

**Comment by mallowigi** [comment]
Weird, it has been compiled with JDK 17 for sure. Did you download it from the marketplace?

**Comment by dtrunk90** [comment]
Yes, it was downloaded from marketplace. Somehow I can't switch my Runtime JDK. It always falls back to 11 and so I can't use Material Theme UI as well as Atom Material Icons anymore.

**Comment by mallowigi** [comment]
Why are you switching to another runtime? I will not compile the plugin to JDK 11.

**Comment by dtrunk90** [comment]
I'm trying to switch from the bundled JDK which is 11 to 17 to make it compatible. The default bundled runtime jdk is 11. If you don't want to make it work with the default bundled runtime jdk we have to switch to 17 manually.

**Comment by mallowigi** [comment]
The 2022.2 versions of the ide are already bundled with jdk 17, hence the jump. I don't know why you're still in 11, it doesn't make sense.

**Comment by mallowigi** [comment]
I see that you're on Linux, maybe that's the issue?

**Comment by dtrunk90** [comment]
I don't know either. But, yeah. You're right 2022.2 switched to JDK 17 now and this is not an issue on your side. I've created an issue at where I've installed the IDE from now: https://gitlab.com/mmk2410/intellij-idea-ultimate/-/issues/9
