### ISSUE TITLE
Project Pane does not Change Theme

### ISSUE THREAD

**Issue by dschinkel** [mallowigi/material-theme-issues#208]
### Describe the bug

May not be a bug and expected behavior but I know that I've been able to get the project pain and everything else to switch to whatever theme I select.  But what drives me crazy is when the project pane doesn't change.  For example when I change to `Material Deep Ocean` even after I restart, half the IDE is still the old theme, why does this keep happening?

### To Reproduce

1. Installed the Material UI Plugin
2. cmd + ,
3. Editor => Color Scheme => Select a different Material UI color scheme
4. Project Pane and Preferences Modal still shows old theme even after restarting IntelliJ

### Expected behavior

Entire IDE including Project pane and any modals should be repainted with the currently selected theme.

### Material Theme Version

18.1.0

### IDE

IntelliJ IDEA

### System Info

OS X Monterey 12.5

### Logs/Screenshots

```shell
https://ibb.co/ZhrxdVC
```

**Comment by mallowigi** [comment]
I'm not sure I understand. 

First of all this is not the right repository to report issues, this is for the material ui plugin, and you're reporting about the material lite plugin.

Next, you're talking about changing the color scheme, while what you need to do is to change the theme, and this is done via the Appearance menu, not the editor color scheme.

**Comment by dschinkel** [comment]
Let me move this then.

**Comment by dschinkel** [comment]
Yea it's just confusing, there are several places you can specify the them.  You're correct, we should use Appearance.
