### ISSUE TITLE
License problem: even if i got a license , on the plugin configuration appear No License 

### ISSUE THREAD

**Issue by antimoroma** [mallowigi/material-theme-issues#21]
**Describe the bug**
And some feature are disabled  

**To Reproduce**
1. Open plugin in IntelliJ

**Environment**
Intellij 2021.2.2

It should contain:
* OS  Linux
* IntelliJ Product + version (IDEA, RubyMine...)
* Plugin version Last version

**Screenshots**
![image](https://user-images.githubusercontent.com/7354134/134804190-3f048e8e-b825-45b0-8fc6-bdb9be429ea9.png)

**Comment by mallowigi** [comment]
You need to activate the license: https://material-theme.com/docs/configuration/quick-actions-panel/#material-theme-features

**Comment by antimoroma** [comment]
Thank you problem solved!

Quite strange I use on this installation for a lot of time (but there was an Intellij version update in last weeks if I remember well)
