### ISSUE TITLE
[Bug]: Missing of "Experimental New UI" check box and its features.

### ISSUE THREAD

**Issue by csunking** [mallowigi/material-theme-issues#212]
### Describe the bug

Toolbar is not a icon style as old versions. 

### To Reproduce

....

### Expected behavior

fixed it.

### Material Theme Version

v7.8.0

### IDE

IntelliJ IDEA, Other (AppCode, CLion, GoLang...)

**Comment by mallowigi** [comment]
https://material-theme.com/docs/what-s-new/#sunsetting-the-experimental-ui
