### ISSUE TITLE
[Bug]: character "fl" width problem

### ISSUE THREAD

**Issue by wenpeng** [mallowigi/material-theme-issues#214]
### Describe the bug

<img width="1172" alt="截屏2022-08-27 16 11 53" src="https://user-images.githubusercontent.com/11190229/187021474-d3e549c7-5a6b-4b02-a8b6-bff77767aea6.png">

### To Reproduce

1. Open Goland
2. Create or Open go file
3. create struct with tag or comments
```
type X struct {
	Font  string `json:"font"`  // f
	Like  string `json:"like"`  // l
	Allow string `json:"allow"` // al
	Slow  string `json:"slow"`  // sl
	Flow  string `json:"flow"`  // fl
	Flaw  string `json:"flaw"`  // fl 
}
```
4.the width of "fl" is different to others

### Expected behavior

the width of "fl" is same as others

### Material Theme Version

v7.8.1

### IDE

Other (AppCode, CLion, GoLang...)

### System Info

```shell
GoLand 2022.2.2
Build #GO-222.3739.57, built on August 17, 2022

macOS 12.5.1 
MacBook Pro (13-inch, 2020, Two Thunderbolt 3 ports)
```

**Comment by mallowigi** [comment]
It's because you're using a font with ligatures.
