### ISSUE TITLE
[Bug]: Inconsistent typehint color for None when using PEP604 style

### ISSUE THREAD

**Issue by Juniormin123** [mallowigi/material-theme-issues#217]
### Describe the bug

Inconsistent typehint color for `None` when using PEP604 style. As the user inputs more content, the color for `None` in an expression like `a: int | None` may change.

### To Reproduce

```python
# in pycharm

# may copy/paste or input this example line by line to reproduce

from __future__ import annotations


a: int | None = 11
b: int | None = 11
c: int | None = None
d: int | None = None
e: None = None


def func(a: int | None = None, b: int | None = 11):
    print(a, b)


def func2(a: int | None = 12, b: int | None = None):
    print(a, b)

# input more codes with `| None` typehints to see possible color changes
```

### Expected behavior

Same color for None after operator `|`

### Material Theme Version

v7.8.1

### IDE

PyCharm

### System Info

```shell
PyCharm 2022.2.1 (Professional Edition)
Build #PY-222.3739.56, built on August 16, 2022


Runtime version: 17.0.3+7-b469.37 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.19.3-zen1-1-zen
GC: G1 Young Generation, G1 Old Generation
Memory: 3072M
Cores: 20
Registry:
    ide.editor.tab.selection.animation=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    name.kropp.intellij.makefile (222.3739.24)
    com.intellij.ideolog (203.0.30.0)
    Key Promoter X (2022.2)
    IdeaVIM (1.11.1)
    com.github.copilot (1.1.30.1887)
    mobi.hsz.idea.gitignore (4.4.2)
    com.mallowigi (72.0.0)
    izhangzhihao.rainbow.brackets (6.25)
    com.chrisrm.idea.MaterialThemeUI (7.8.1)

Current Desktop: KDE
```

**Comment by Juniormin123** [comment]
![image](https://user-images.githubusercontent.com/42923055/187641240-7fc52cce-f8f1-4eef-b82c-c3fde1d61581.png)

I can't upload the screenshot in the `Logs/Screenshots` session, so I put it here. The theme is pycharm bundled Monokai.

**Comment by mallowigi** [comment]
Have you tried with "Enforce Highlighting"?

**Comment by mallowigi** [comment]
I will take a look but if you're on the free plan you shouldn't be having the language additions. Are you sure the issue happens only with the plugin themes? If you use other themes the issue doesn't reproduce?

**Comment by Juniormin123** [comment]
I have been using jetbrains bundled Darcula theme and Monokai Pro color scheme from this plugin.

Things I have tried:
* Disable all other non-bundled plugins, leave only the Material Theme plugin on:
  * The problem exists in both jetbrains Monkai color and color schemes from this plugin;
* Disable this plugin and turn on the others:
  * Problem does not reproduce on jetbrains default themes and colors.
