### ISSUE TITLE
CheckBox disapeear on Setting Modal Window when Plugin is installed

### ISSUE THREAD

**Issue by antimoroma** [mallowigi/material-theme-issues#22]
In 2021.2.2 (Linux)
![image](https://user-images.githubusercontent.com/7354134/134821312-0f606438-0bbb-4546-97fe-5b474257d6bd.png)

Seems working  in 2020.3
![image](https://user-images.githubusercontent.com/7354134/134821339-1e13ca6c-edde-41f9-8264-a99450ccc4f8.png)

I try just to make some tests to uninstall reinstall and test on a different version
It seems to disappear when I select "Contrast Mode", then "High Contrast" then deselct one to the two, and the no way to make the visibible (but they reappear one time during the test :( ) 
I tried with different themes :(

**Comment by TiceWise** [comment]
I want to report this same issue. For me it happened after installing the Atom Material Icon plugin, after disabling the PSI Icons specifically (I like the file icons, but want to keep the default UI icons).

PSI Icons turned on:
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/46386345/134856111-3db2287a-742b-47a1-b794-d414311e4062.png">

PSI Icons turned off:
<img width="1217" alt="image" src="https://user-images.githubusercontent.com/46386345/134856225-48aae48d-3ac5-4142-bd7e-92ba1f171fa2.png">

**Comment by mallowigi** [comment]
I have a solution, it will be available in the next version, which should be happening shortly.

**Comment by TiceWise** [comment]
Great, thanks, looking forward!

**Comment by mallowigi** [comment]
Does it reproduce on the latest version?

**Comment by TiceWise** [comment]
It's fixed, thanks!

**Comment by antimoroma** [comment]
Thank you for the rapid fix :)
