### ISSUE TITLE
[Bug]: Icon './public/icons/Material Oceanic.svg' fails to load crashing DevTools sources tab 

### ISSUE THREAD

**Issue by albertonoys** [mallowigi/material-theme-issues#222]
### Describe the bug

This happens in the Chrome Dev Tools. Every time I open them it tells me that it has failed to load that resource: 

![image](https://user-images.githubusercontent.com/3334359/189884404-431f6070-fe2d-4220-9fb3-8335573da859.png)

And the sources tab crashes and it's just kept blank: 

![2022-09-13_12-57](https://user-images.githubusercontent.com/3334359/189884686-7641d5b5-499d-4b53-81a1-a58b528a9869.png)

Note: It may be possible that this error is not the one causing the sources tab to crash, but the sources tab loads correctly if I disable the extension.

### To Reproduce

1. Open the Chrome Dev Tools
2. Go to the Sources tab
3. Undock it into a separate window
4. Hit Ctrl+Shift+I to inspect the DevTools window with another DevTools window
5. Errors should appear there

### Expected behavior

No errors loading assets and sources tab on Chrome DevTools loading properly

### Material Theme Version

7.2.3

### IDE

Other (AppCode, CLion, GoLang...)

### System Info

```shell
- OS: Ubuntu 20.04.5 LTS
- Google Chrome: Version 105.0.5195.102 (Official Build) (64-bit)
```

**Comment by mallowigi** [comment]
That's not the right repository to report issues about the chrome plugin but I'll take a look nonetheless.

**Comment by albertonoys** [comment]
> That's not the right repository to report issues about the chrome plugin but I'll take a look nonetheless.

Oh, I'm so sorry. You don't have to. Let me know where I should report it and I will.

**Comment by albertonoys** [comment]
Also. It occurred to me that maybe the assets were broken on my system since I installed this extension a long long time ago and... I don't know.

I just removed the extension and installed it again and it seems to have fixed the problem. 

So let's close this issue and I'll keep an eye on it. 

Sorry for the loss of time.
