### ISSUE TITLE
[Bug]: Custom Item Line Height no longer working

### ISSUE THREAD

**Issue by AoElite** [mallowigi/material-theme-issues#224]
### Describe the bug

The Custom Item Line Height setting appears to no longer work after version 7.10.0 on IntelliJ 2022.2.2. Doesn't matter what the height is set to it doesn't change.

### To Reproduce

Settings -> Material Theme -> Project View -> Custom Item Line Height -> Edit Height

Project view item heights do not change.

### Expected behavior

Settings -> Material Theme -> Project View -> Custom Item Line Height -> Edit Height

Project view item heights should change.

### Material Theme Version

v7.10.0

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2022.2.2 (Ultimate Edition)
Build #IU-222.4167.29, built on September 13, 2022
Runtime version: 17.0.4+7-b469.53 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2020M
Cores: 24
Registry:
    ide.editor.tab.selection.animation=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    com.github.copilot (1.1.31.1908)
    mobi.hsz.idea.gitignore (4.4.2)
    com.almightyalpaca.intellij.plugins.discord (1.10.0)
    CheckStyle-IDEA (5.70.0)
    com.chrisrm.idea.MaterialThemeUI (7.10.0)

Kotlin: 222-1.7.10-release-334-IJ4167.29
```

### Logs/Screenshots

```shell
https://i.imgur.com/DC7R32U.png
```

**Comment by mallowigi** [comment]
Thanks. Can you provide me more details about your license? Are you a free user or premium user?

**Comment by mallowigi** [comment]
fixed
