### ISSUE TITLE
[Bug]: Override Accent Color Toggle Inverted

### ISSUE THREAD

**Issue by SlanDF** [mallowigi/material-theme-issues#240]
### Describe the bug

The `Override Accent Color from Theme` Toggle is inverted, having the enable override doesnt override, disabling the override allows you to override.

**Theme Accent Color**
![image](https://user-images.githubusercontent.com/13062045/192773411-a947512f-3bbe-4d40-98b0-155a9a8f147a.png)

**Toggle Off**
![image](https://user-images.githubusercontent.com/13062045/192773614-9aa49b7e-a48b-4ecd-baa7-20be921c0ae2.png)
![image](https://user-images.githubusercontent.com/13062045/192773644-8f459c3e-24c3-4590-af6b-fb4ad335117a.png)
![image](https://user-images.githubusercontent.com/13062045/192773970-9211ef5e-ac12-4262-83f0-042dd9c8a80d.png)

**Toggle On**
![image](https://user-images.githubusercontent.com/13062045/192773754-13739abb-d214-48df-89f6-1915cb1dde93.png)

### To Reproduce

1. Material Theme UI > Settings
2. Click the toggle

### Expected behavior

Invert the toggle behaviour

### Material Theme Version

v7.11.0

### IDE

WebStorm

### System Info

```shell
WebStorm 2022.2.2
Build #WS-222.4167.31, built on September 14, 2022
Licensed to Duarte Faria
Subscription is active until August 30, 2023.
For educational use only.
Runtime version: 17.0.4+7-b469.53 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2038M
Cores: 12
Registry:
    editor.focus.mode.color.light=515772
    ide.editor.tab.selection.animation=true
    debugger.watches.in.variables=false
    ide.new.editor.tabs.vertical.borders=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=515772

Non-Bundled Plugins:
    patrick.kelleter.angular-cli-quick-switch (1.3)
    indent-rainbow.indent-rainbow (2.0.2)
    com.xrath.plugin.fold (1.6.0)
    com.jetbrains.plugins.ini4idea (222.4167.35)
    com.jetbrains.darkPurpleTheme (1.3)
    com.intellij.plugin.adernov.powershell (2.0.10)
    com.chylex.intellij.inspectionlens (1.0.0)
    mobi.hsz.idea.gitignore (4.4.2)
    com.mallowigi (73.0.0)
    izhangzhihao.rainbow.brackets (6.26)
    com.hasintech.intellij.angularTemplates (1.1.3)
    com.chrisrm.idea.MaterialThemeUI (7.11.0)
    com.atlassian.bitbucket.references (2020.3.206)
    CMD Support (1.0.5)
    lermitage.intellij.extra.icons (2022.1.11)
```

**Comment by mallowigi** [comment]
I think you misunderstood, "Override Accent Color From Theme" means that it takes the accent color from the theme, whereas if you uncheck it, it will take from the custom accent color. Thats' what you see in your screenshots: when it's unchecked, it's green, the same color as the custom accent color you said. When it's checked, it's purple, the same color you used in the custom theme.

**Comment by SlanDF** [comment]
Ah so it's intended to be this way, sounds backwards though. Feels like it makes more sense that enabling overriding the accent color from the theme would enable you to pick the color, I'm guessing the confusion I'm facing here is that that color picker that i changed to green is the native accent color picker?
Which one is correct?

 "Override Accent Color..."
- "...with the theme's accent color"
- "...of the theme's accent color"
