### ISSUE TITLE
[Bug]: Cant install / use Material Theme UI in Android Studio (ERROR: 404)

### ISSUE THREAD

**Issue by CarinaSchoppe** [mallowigi/material-theme-issues#241]
### Describe the bug

Trying to use the plugin in the latest Canary build deactivates the plugin. 
Trying to reinstall it gives me a 404 exception.

### To Reproduce

Install Android studio Flamingo  (canary 2)
try to install plugin

### Expected behavior

should work correctly.

### Material Theme Version

7.11.0

### IDE

Android Studio

### System Info

```shell
Android Studio Flamingo | 2022.2.1 Canary 2
Build #AI-222.4167.29.2221.9093980, built on September 22, 2022
Runtime version: 11.0.15+0-b2043.56-8887301 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 16
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    tanvd.grazi (222.4167.20)
    some.awesome (1.14)
    net.seesharpsoft.intellij.plugins.csv (2.19.0)
    krasa.CpuUsageIndicator (1.14)
    com.wakatime.intellij.plugin (14.1.1)
    com.tabnine.TabNine (0.7.25)
    com.intellij.marketplace (222.4167.37)
    com.intellij.grazie.pro (0.3.107-221-222)
    jd-intellij (0.8.1)
    com.github.copilot (1.1.32.1958-nightly)
    awesome.console (0.1337.12)
    Statistic (4.2.6)
    PythonCore (222.4167.37)
    Key Promoter X (2022.2)
    org.sonarlint.idea (7.1.0.54364)
    mobi.hsz.idea.gitignore (4.4.2)
    com.mallowigi (73.0.0)
    com.almightyalpaca.intellij.plugins.discord (1.10.0)
    zielu.gittoolbox (212.9.9)
    izhangzhihao.rainbow.brackets (6.26)
    cn.yiiguxing.plugin.translate (3.3.5)
```

### Logs/Screenshots

```shell
```

**Comment by CarinaSchoppe** [comment]
![Screenshot 2022-09-28 220720](https://user-images.githubusercontent.com/29256704/192878617-e77bc454-1de6-4071-8db3-34545337415d.png)

**Comment by mallowigi** [comment]
You must use JDK 17. Did you download Android Studio from the JetBrains toolbox?

**Comment by CarinaSchoppe** [comment]
Yes.

Elior Boukhobza ***@***.***> schrieb am Do., 29. Sept. 2022,
08:04:

**Comment by mallowigi** [comment]
Bad news: according to [this document](https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html#intellij-platform-based-products-of-recent-ide-versions), JDK 17 is required for 222.X builds

Therefore, it's Android Studio's problem that they still have to run on JDK 11. 

I tried, but unfortunately I am unable to compile to JDK 11 due to that condition. As a result, Android Studio cannot be supported. 

Sorry guys, but you're welcome to open an issue to AS folks to make their IDE JDK 17 compatible.

**Comment by mallowigi** [comment]
I'll leave this open, if I find a workaround I'll update

**Comment by mallowigi** [comment]
[Material Theme UI-7.11.0-Android.zip](https://github.com/mallowigi/material-theme-issues/files/9677831/Material.Theme.UI-7.11.0-Android.zip)

Ok I've managed to make a build compatible. Please try it and tell me it's all fine.

I don't know how I'll be able to publish it to prevent it to be distributed to everyone, maybe I'll use channels.

**Comment by CarinaSchoppe** [comment]
maybe submit the zip file here and Ill try it. I guess

**Comment by CarinaSchoppe** [comment]
> [Material Theme UI-7.11.0-Android.zip](https://github.com/mallowigi/material-theme-issues/files/9677831/Material.Theme.UI-7.11.0-Android.zip)
> 
> Ok I've managed to make a build compatible. Please try it and tell me it's all fine.
> 
> I don't know how I'll be able to publish it to prevent it to be distributed to everyone, maybe I'll use channels.

Ive tried it and at least I could install it and it worked.

**Comment by mallowigi** [comment]
I know it worked, but I haven't tested a lot. I was wondering whether working on a daily basis would be suffering from this JDK downgrade

**Comment by mallowigi** [comment]
I published a version for Android Studio only. That's one less thorn in the side!
