### ISSUE TITLE
[Bug]: Exceptions after Updating to 7.12.0 in intellij 2022.2.2

### ISSUE THREAD

**Issue by BlockyTheDev** [mallowigi/material-theme-issues#243]
### Describe the bug

An popup with exceptions opens.

### To Reproduce

1. Update plugin to v7.12.0
2. Restart Intellij 2022.2.2 Community

### Expected behavior

No exception.

### Material Theme Version

v7.12.0

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2022.2.2 (Community Edition)
Build #IC-222.4167.29, built on September 13, 2022
Runtime version: 17.0.4+7-b469.53 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 3054M
Cores: 12
Registry:
ide.intellij.laf.enable.animation=true
editor.focus.mode.color.light=474747
ide.editor.tab.selection.animation=true
debugger.new.tool.window.layout=true
ide.new.editor.tabs.vertical.borders=true
ide.experimental.ui=true
ide.balloon.shadow.size=0
editor.focus.mode.color.dark=474747

Non-Bundled Plugins:
idea.plugin.protoeditor (222.4167.21)
de.femtopedia.diffplugin (2.1.8)
com.jetbrains.performancePlugin (222.4167.21)
com.intellij.javafx (1.0.4)
com.itcodebox.fxtools.id (1.2.4)
com.mallowigi (73.0.0)
com.almightyalpaca.intellij.plugins.discord (1.10.0)
MavenRunHelper (4.21.222.2964.0)
com.chrisrm.idea.MaterialThemeUI (7.12.0)
com.demonwav.minecraft-dev (2022.2-1.5.20)

Kotlin: 222-1.7.10-release-334-IJ4167.29
```

### Logs/Screenshots

<img width="922" alt="193366275-1e0cfc08-b131-4c90-bb3b-e90697c6d52b" src="https://user-images.githubusercontent.com/86119630/193366846-84ab9e67-7bff-4df5-93fa-33c9e232f84a.png">
<img width="971" alt="193366249-281adde6-c396-4fc2-a7ce-b589576ca0ec" src="https://user-images.githubusercontent.com/86119630/193366849-317ef2a5-6179-49c7-88f6-7007f451aca1.png">
<img width="914" alt="193366311-66e3b4d5-fd61-4ca7-9b14-7f2d0143a9bc" src="https://user-images.githubusercontent.com/86119630/193366851-051269e7-d197-4c36-b0fb-61326f810f9a.png">

**Comment by BlockyTheDev** [comment]
I think it has to do with this weird looking colors things: 
<img width="356" alt="image" src="https://user-images.githubusercontent.com/86119630/193367518-0a4f2799-e8ae-49d0-92ec-11e8d2e509c5.png">

**Comment by mallowigi** [comment]
Damn. It should have been available for Android Studio only. Thanks for reporting, I'll delete this version and try again to target AS only.

In the meantime please uninstall the plugin and wait for 7.11.0 to be available

**Comment by BlockyTheDev** [comment]
👍 I already uninstalled it yesterday and downloaded the version 7.11.0 directly from the Jetbrains plugin website and added it.
