### ISSUE TITLE
[Bug]: Default themes on IntelliJ display unreadable (white on white) text

### ISSUE THREAD

**Issue by aarner42** [mallowigi/material-theme-issues#246]
### Describe the bug

Using several of the themes on Windows 10 or Windows 11, opening the annotations/blame panel in IntelliJ IDEA leads to text that is displayed in a zero-contrast configuration (white-on-white or grey-on-grey for instance)

Licensed user.  Have tested with Dracula, Atom Light, and Light Owl.

Easily reproduced, just open any file with more than a few levels of versioning history, and select _annotate_ from the main source editor.  

### To Reproduce

1. Open a source file with multiple generations of SVN or GitHub revisions
2. Right-click on the file and select _Annotate_

Screenshots attached.
![brokenMaterial](https://user-images.githubusercontent.com/13105779/193645794-4c2fa609-dce3-47df-9c4c-a7de35a6cccb.png)
![BrokenMaterial2](https://user-images.githubusercontent.com/13105779/193645809-616ac39b-60dd-40be-a145-7e88948cd4ab.png)

### Expected behavior

All entries in annotation panel should be visible.

### Material Theme Version

v7.9.0

### IDE

IntelliJ IDEA, DataGrip

### System Info

```shell
IntelliJ IDEA 2022.2.2 (Ultimate Edition)
Build #IU-222.4167.29, built on September 13, 2022
Licensed to Aaron Dutenhoefer
Subscription is active until November 17, 2022.
Runtime version: 17.0.4+7-b469.53 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Registry:
    ide.editor.tab.selection.animation=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    monokai-pro (1.9)
    com.vincentp.gruvbox-theme (0.5.5)
    com.thvardhan.gradianto (4.5)
    com.robohorse.robopojogenerator (2.3.7)
    com.jetbrains.jax.ws (222.4167.21)
    com.hiberbee.intellij.hiberbee-theme (2022.5.16.1805)
    com.github.zxj5470.javaxhint (0.1.2)
    com.andrey4623.rainbowcsv (2.0.2)
    atom-one (1.5.1)
    com.intellij.plugin.adernov.powershell (2.0.10)
    com.intellij.javaee.ejb (222.4167.21)
    com.intellij.selenium (222.4167.21)
    Rider UI Theme Pack (0.10.3)
    com.mallowigi (72.0.0)
    com.intellij.jsf (222.4167.21)
    com.intellij.plugins.html.instantEditing (222.4167.21)
    com.intellij.javaee.batch (222.4167.21)
    Pythonid (222.4167.29)
    Batch Scripts Support (1.0.13)
    com.chrisrm.idea.MaterialThemeUI (7.9.0)
    JProfiler (19.7)
    com.intellij.jboss.arquillian (222.4167.21)
    com.haulmont.jpab (2022.4.1-222)
    MavenRunHelper (4.21.222.2964.0)
    JRebelPlugin (2022.3.2)
    izhangzhihao.rainbow.brackets (6.25)

Kotlin: 222-1.7.10-release-334-IJ4167.29
```

### Logs/Screenshots

```shell
See attached screenshots for examples of unreadable text (in To Reproduce: above)
```

**Comment by mallowigi** [comment]
I can understand the issue with the light themes, but what's wrong with Dracula?

**Comment by aarner42** [comment]
@mallowigi If you look on the left-side panel where the annotations are shown in the Dracula theme, on lines 688-690 (and others) there are gaps.  There are text entries in those gaps, they are just displayed in black-on-black and thus can't be seen.  (Sorry for the delay in responding, was on PTO for a few days)

**Comment by mallowigi** [comment]
i changed the foreground color to white for the lighter themes and dracula. This will be available in the next version. Closing this for now
