### ISSUE TITLE
[Bug]: Intentions are counted in Problems Counter

### ISSUE THREAD

**Issue by dmitry-ivanov** [mallowigi/material-theme-issues#248]
### Describe the bug

When you open PHP file which does NOT have any warnings or errors, the counter is still non-zero.

Though, when you open Problems List for the current file - it's empty.

I've experimented for a while and found out that if you disable Material Theme plugin - then counter become zero again. And it seems like Material Theme counts intentions as low-priority problems (even though they are not).

### To Reproduce

1. Open any PHP file without warnings or errors.
2. Make sure PHPStorm has some intentions for it (for example, when you have class with public methods, PHPStorm would add intentions for you to quickly make methods private/protected).
3. Make sure you can see results of analyzing that file (it's in the upper right corner usually).
4. You'll see N found problems, but the Problems list is empty for the current file.

![111](https://user-images.githubusercontent.com/1286821/194040069-4dc42e61-cf66-4e12-b548-0fb815fead3f.jpg)

### Expected behavior

File should be marked as valid (green tick).

### Material Theme Version

7.11.0

### IDE

PHPStorm

### System Info

```shell
PhpStorm 2022.2.2
Build #PS-222.4167.33, built on September 15, 2022
Runtime version: 17.0.4+7-b469.53 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 4
Metal Rendering is ON
Registry:
    editor.focus.mode.color.light=415967
    ide.editor.tab.selection.animation=true
    run.processes.with.pty=TRUE
    ide.new.editor.tabs.vertical.borders=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=415967

Non-Bundled Plugins:
    com.microsoft.vso.idea (1.162.0)
    com.mallowigi (73.0.0)
    com.kalessil.phpStorm.phpInspectionsEA (4.0.7.1)
    com.github.inxilpro.intellijalpine (v0.4.2)
    com.chrisrm.idea.MaterialThemeUI (7.11.0)
    ru.adelf.idea.dotenv (2022.2)
    com.laravel_idea.plugin (6.0.0.222)
```

**Comment by mallowigi** [comment]
It's not a bug, it's a workaround for the Language Additions feature to work. It's not perfect but it does the job.

I tried to find a workaround but to no avail. Just disregard it, it doesn't have an icon for that purpose.

**Comment by dmitry-ivanov** [comment]
@mallowigi Thank you for your reply.

By disabling that feature I was able to solve the problem (for me personally, it's annoying to have these "false-positives").

PS: Here's the path, if someone would like to disable it too:

> Preferences > Appearance & Behavior > Material Theme UI > Settings > Advanced Settings > Other Tweaks > Language Additions
