### ISSUE TITLE
[Bug]: Test directory has bright green color with unreadable text

### ISSUE THREAD

**Issue by tenhobi** [mallowigi/material-theme-issues#249]
### Describe the bug

Theme: Darker Theme in Lite version

The test/ directory is unreadable with toxic green background on the item.

### To Reproduce

🤷 

### Expected behavior

The item should not have such a toxic background color.

### Material Theme Version

16.0

### IDE

Android Studio

### Logs/Screenshots

![image](https://user-images.githubusercontent.com/5287596/194069343-c6b7615a-f5f8-40b5-83c6-d20162c5fffe.png)

**Comment by mallowigi** [comment]
https://material-theme.com/docs/configuration/excluded-files-colors/
