### ISSUE TITLE
[Bug]: F2 Next highlighted error doesn't work properly on M1 Macs

### ISSUE THREAD

**Issue by rherrick** [mallowigi/material-theme-issues#251]
### Describe the bug

Normally pressing F2 while in source code takes you to the next highlighted error in that code. On M1 Macs, it seems to jump from keyword to keyword or something like that. The important thing is that you can have an error highlighted in red and pressing F2 does _not_ take you there but instead jumps to, e.g., `public` on a class declaration or something similar.

I tested against various versions of the plugin. There's already something strange going on in 7.9.0 (see **Expected behavior** section for more details), but it really breaks with 7.10.0. I uploaded a [screen recording of this behavior to YouTube](https://youtu.be/QK0jQKq_1Q0).

To isolate this issue to the Material Theme UI plugin, I uninstalled all other plugins so I was running with nothing but the standard bundled plugins and Material Theme UI. I cleared the IntelliJ log folder before restarting and no errors relevant to this plugin appear from application start-up until I hit **F2** a few times.

Please let me know if I can provide any other info to help debug this issue or to test possible fixes.

### To Reproduce

1. Introduce a breaking error (e.g. declaring an instance of a non-existent class) in some code
2. Go to the first line of the file
3. Press **F2**

An error is included in this simple Spring Boot project.

[api.zip](https://github.com/mallowigi/material-theme-issues/files/9737083/api.zip)

### Expected behavior

It should go to the breaking error. Instead it goes to the next keyword (you can see this in the linked video at about 0:44).

I've reproduced this on two different M1 Macs with the same result. I also tested on an x86 Mac with the same version of OS X, IntelliJ IDEA, and Material Theme UI plugin. It worked properly there.

The issue is already happening in v7.9.0, but not as badly: when I hit **F2** there I go down to the first error/warning instead of the first keyword, but it also doesn't go to all errors of the highest severity first, _then_ to errors/warnings of the next highest severity, etc. The error that I added in my code is:

```java
final Flarn flarn = new Flarn();
```

On x86 when you hit **F2** you'll first go to the first reference to `Flarn` (because it's an unknown class) then the second reference to `Flarn`. If you change those to a known class or create a class for that, then the next time you press **F2** you'll go to the instance name `flarn`, because that's only a warning telling you that that instance isn't being used.

On M1 on v7.9.0, hitting **F2** takes me to the first reference to `Flarn`, then the instance name `flarn`, then the second reference to `Flarn`.

### Material Theme Version

v7.10.0

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2022.2.3 (Ultimate Edition)
Build #IU-222.4345.14, built on October 5, 2022
Licensed to Flywheel Exchange LLC / Rick Herrick
You have a perpetual fallback license for this version.
Subscription is active until August 2, 2023.
Runtime version: 17.0.4.1+7-b469.62 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.6
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 10
Metal Rendering is ON
Registry:
    editor.focus.mode.color.light=6b727d
    external.system.substitute.library.dependencies=true
    ide.editor.tab.selection.animation=true
    ide.new.editor.tabs.vertical.borders=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=6b727d

Non-Bundled Plugins:
    org.nik.presentation-assistant (1.0.10)
    manjaro.mpb (1.7)
    com.nasller.CodeGlancePro (1.5.2)
    org.jetbrains.kotlin (222-1.7.20-release-201-IJ4167.29)
    com.intellij.guice (222.4345.14)
    com.mallowigi (73.0.0)
    com.intellij.kubernetes (222.4345.14)
    com.microsoft.tooling.msservices.intellij.azure (3.69.0-2022.2)
    com.intellij.bigdatatools (222.3345.33)
    com.haulmont.jpab (2022.4.2-222)
    aws.toolkit (1.51-222)
    com.chrisrm.idea.MaterialThemeUI (7.11.0)

Kotlin: 222-1.7.20-release-201-IJ4167.29
```

**Comment by mallowigi** [comment]
This is a known issue, you can disable it by disabling the Language Additions feature. 

Currently I have no other workaround, but I'll update if I find something.
