### ISSUE TITLE
[Bug]: Incorrect rendering of `Selected Item Indicator` in `Project View`

### ISSUE THREAD

**Issue by BppleMan** [mallowigi/material-theme-issues#257]
### Describe the bug

Since 7.7.0, i.e. >= 7.7.1, when I select a file and focus on the editor, the `Selected Item Indicator` goes out.
But I want it to always show.
I came from slack.
![image](https://user-images.githubusercontent.com/16437384/196641399-a6e8ffae-c235-409b-bc74-be64146a3c3f.png)

### To Reproduce

1. Open IntelliJ Idea/Webstorm, install the Material Theme UI plugin
2. Open any project
3. Select any file

![image](https://user-images.githubusercontent.com/16437384/196643319-cc38b068-f823-4dd4-84d3-84d7b3236ee9.png)

4. Focus on the editor

![image](https://user-images.githubusercontent.com/16437384/196643386-0e9cc15e-b03f-4bb5-86ba-48eb2c2c8373.png)

### Expected behavior

The Indicator should always show whether the Project View or the Editor is focused.
I get the expected effect in 7.7.0 but this is not available >= 7.7.1

![image](https://user-images.githubusercontent.com/16437384/196642880-183e767c-12f1-4915-96f2-8ae65f88d472.png)

![image](https://user-images.githubusercontent.com/16437384/196643083-3033c53b-104d-45fc-a7f1-9a82f1915c0b.png)

7.7.0 download link: https://plugins.jetbrains.com/plugin/download?rel=true&updateId=195826

### Material Theme Version

v7.1.1

### IDE

IntelliJ IDEA, WebStorm, Other (AppCode, CLion, GoLang...)

### System Info

```shell
WebStorm 2022.2.3
Build #WS-222.4345.14, built on October 5, 2022
Licensed to Bpple Man
Subscription is active until April 3, 2023.
For educational use only.
Runtime version: 17.0.4.1+7-b469.62 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    com.mallowigi (65.1.0)
    izhangzhihao.rainbow.brackets (6.26)
    com.chrisrm.idea.MaterialThemeUI (7.7.0)
    AceJump (3.8.8)
    IdeaVIM (1.11.1)
```

**Comment by mallowigi** [comment]
It wasn't a bug, it was something that I removed because it broke the UI after moving to 2022.2 

I just readded it and tried to fix the issues, it wasn't simple. I'm still conducting some tests.
