### ISSUE TITLE
[Bug]: Inspector tooltip does not work properly with custom Inspections configuration [Annotator]

### ISSUE THREAD

**Issue by ignqa** [mallowigi/material-theme-issues#258]
### Describe the bug

The next tooltip tells me that I have some Python native statements to check in my code:

![image](https://user-images.githubusercontent.com/56890196/196720200-5a1fffc8-15b9-4386-9f76-48dd8560543b.png)

But they are displayed with empty text in the inspector:

![image](https://user-images.githubusercontent.com/56890196/196720265-48a94704-b655-4a1b-896c-018bf10b2b0b.png)

I'm not so interested in that inspections, so I proceeded to disable it as a workaround:

![image](https://user-images.githubusercontent.com/56890196/196720337-a4b0fa17-e84f-4f44-aaea-8f004c7235fd.png)

But the tooltip is still telling me that I still have 4 inspections to check:

![image](https://user-images.githubusercontent.com/56890196/196720384-2f824f52-029d-4995-9c22-2e90561da4d0.png)

It's a bit annoying cause I cannot see the green check when I accomplish the rules I set for my custom inspection.

I installed the EAP version to check if this was fixed (it's not), but it was also happening on the latest Pycharm version.

Ticket already opened on YouTrack: https://youtrack.jetbrains.com/issue/PY-56885

### To Reproduce

Explained on the Description sectionin

### Expected behavior

No warning should appear, as it happens when the plugin is disabled (even having the inspector checkbox enabled for Annotators

### Material Theme Version

v7.13.1

### IDE

PyCharm

### System Info

```shell
JRE 17.0.4.1+1-b629.2x64 JetBrains s.r.o., OS Windows 11(amd64) v10.0 , screens 2560.0x1080.0
```

**Comment by mallowigi** [comment]
Hi @ignqa , I wrote you in the original ticket but I'll write it here as well. The issue is due to the Language Additions feature. I'll try to figure out a better solution but in the meantime, if it bothers you that much you can simply turn off the Language Additions.
