### ISSUE TITLE
Overlay is visible when popup is not active

### ISSUE THREAD

**Issue by mts527** [mallowigi/material-theme-issues#26]
**Describe the bug**
In some cases the overlay stays visible when a popup is not active any more. Quick guess is that other plugin(s) also trigger the overlay so one of them stays visible.

**To Reproduce**

1. Install [Magento 2 plugin](https://github.com/magento/magento2-phpstorm-plugin) and enable it
2. Right click on some folder in files tree and select New -> Magento 2 module
3. Press escape to close the popup
4. Overlay stays visible even tho popup was closed

**Expected Behavior**
Popup overlay should dissapear.

**Environment**
PhpStorm 2021.2.2
Build #PS-212.5284.49, built on September 16, 2021
macOS 11.6
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI (6.9.0), com.magento.idea.magento2plugin (4.1.0)

**Related issues**
[#667 - Magento 2 PhpStorm Plugin](https://github.com/magento/magento2-phpstorm-plugin/issues/667)
[#18 - Material Theme UI PhpStorm Plugin](https://github.com/mallowigi/material-theme-issues/issues/18#issue-993222323)

**Workaround**
[Disable Show Overlays](https://github.com/magento/magento2-phpstorm-plugin/issues/667#issuecomment-934704790)

**Comment by mallowigi** [comment]
As a workaround, you can simply toggle the Overlays setting to fix it.

**Comment by mts527** [comment]
Yep, I did that temporarely - thanks.
