### ISSUE TITLE
[Bug]: Double click won't open new file 

### ISSUE THREAD

**Issue by suesunss** [mallowigi/material-theme-issues#264]
### Describe the bug

Hi,

I am using latest Material theme, Intellij IDEA 2022.2.3(Ultimate). 

It seems that, all of a sudden, double click to open new file doesn't work anymore. More precsiely, we have to click exactly the **filename area** instead of the area around a file to open a file, which is wired compared to previous experience.

Could anyone help ?

### To Reproduce

1. Donwload latest Intellij IDEA 2022.2.3 
2. Download latest Matrial Theme UI (7.14.1)
3. Double click one file in source project root directory

### Expected behavior

File be opened in editor window as expected

### Material Theme Version

v7.14.1

### IDE

IntelliJ IDEA

**Comment by honkkki** [comment]
me too. But it can open file when click the real file name
if click here cant open file
<img width="422" alt="截屏2022-11-01 14 31 09" src="https://user-images.githubusercontent.com/22451646/199173198-8b27a0ed-2820-4e6a-a2a8-ac503ef50cb8.png">

**Comment by honkkki** [comment]
this bug appear when i updated to v7.14.1

**Comment by Rainyun** [comment]
Me too，And The same is true in webstore editor 2022.2.3

**Comment by zelenyjan** [comment]
Same here with v7.14.1 and PyCharm 2022.2.3.

**Comment by mallowigi** [comment]
[Material Theme UI-7.14.2.zip](https://github.com/mallowigi/material-theme-issues/files/9908725/Material.Theme.UI-7.14.2.zip)

Hey, I tried to fix the issue as much as I can but I'm not sure it fixed everything. Can you try it up and tell me if it's all good? thanks

**Comment by honkkki** [comment]
> [Material Theme UI-7.14.2.zip](https://github.com/mallowigi/material-theme-issues/files/9909391/Material.Theme.UI-7.14.2.zip)
> 
> Hey, I tried to fix the issue as much as I can but I'm not sure it fixed everything. Can you try it up and tell me if it's all good? thanks

It works well after i updating to v7.14.2
