### ISSUE TITLE
[Bug]: Github theme "Checked out new branch" notification balloon has green text on green background

### ISSUE THREAD

**Issue by garethellis36** [mallowigi/material-theme-issues#269]
### Describe the bug

Raised previously [here](https://github.com/ChrisRM/material-theme-jetbrains/issues/1755)

--

I'm using the `Github (Material)` theme on the premium version (6.4.1). IntelliJ version is 2021.1.1.

This notification balloon is very hard to read because the text is green-on-green:
![image](https://user-images.githubusercontent.com/6451455/117814691-8602d500-b25c-11eb-9156-104162678b99.png)

This appears after checking a new VCS branch within the IDE.

--

The same issue is present today in v7.11.0 of the plugin and IntelliJ 2022.2.3

### To Reproduce

- Install the plugin
- Set the theme as `Github (Material)`
- Check out any branch in the IDE

### Expected behavior

The branch name is easy to read in the notification balloon.

### Material Theme Version

v7.11.0

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2022.2.3 (Ultimate Edition)
Build #IU-222.4345.14, built on October 5, 2022
Licensed to ICON Clinical Research / Gareth Ellis
Subscription is active until April 18, 2023.
Runtime version: 17.0.4.1+7-b469.62 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4000M
Cores: 12
Registry:
    editor.focus.mode.color.light=9ba0a3
    ide.editor.tab.selection.animation=true
    debugger.watches.in.variables=false
    ide.new.editor.tabs.vertical.borders=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=9ba0a3

Non-Bundled Plugins:
    mobi.hsz.idea.gitignore (4.4.2)
    org.jetbrains.plugins.ruby (222.4345.14)
    com.jetbrains.php (222.4345.15)
    org.jetbrains.plugins.phpstorm-remote-interpreter (222.4345.14)
    de.espend.idea.php.phpunit (6.2)
    com.vexus2.cakestorm (0.6.1)
    com.kalessil.phpStorm.phpInspectionsEA (4.0.7.1)
    com.intellij.php.psalm (222.4345.15)
    com.iconplc.itrans.plugin (2.4)
    org.jetbrains.plugins.vue (222.4345.15)
    com.intellij.lang.puppet (222.4345.14)
    org.exbin.deltahex.intellij (0.2.6)
    com.chrisrm.idea.MaterialThemeUI (7.11.0)
    izhangzhihao.rainbow.brackets (6.26)

Kotlin: 222-1.7.10-release-334-IJ4345.14
```

**Comment by garethellis36** [comment]
Sorry if I misunderstand what "closed" means here, but I have just updated the plugin and I still get the same issue:
![image](https://user-images.githubusercontent.com/6451455/204028696-c5776f4a-f993-494b-af70-b3ec2b0e52f4.png)

**Comment by mallowigi** [comment]
What version are you on?

**Comment by garethellis36** [comment]
7.14.2

**Comment by mallowigi** [comment]
reproduced.

**Comment by garethellis36** [comment]
Does that need a separate license?

**Comment by mallowigi** [comment]
No, you only need to update the ide
