### ISSUE TITLE
[Bug]: Using the plugin makes the VM to exit

### ISSUE THREAD

**Issue by Smolli** [mallowigi/material-theme-issues#270]
### Describe the bug

I don't know where to locate to origin of the problem. I was able to pinpoint the Material Theme plugin for being responsible of this behaviour.

When working with larger projects it happens that the IDE crashes. But instead of writing logs or creating a heap dump the VM just exits. I tried to watch and catch this behaviour with VisualVM but without any irregularities. 

I'd love to add more information to this as it really bugs me and hinders me with my daily work. The only way to avoid it is to deactivate the plugin what gives my eye cancer. :'(
Is there anything I can do to give you more information? Like starting the IDE in debug mode or whatever? Do you have any tip for me?

### To Reproduce

A good way to reproduce is via log output it seems:
* Load a workspace with two Gradle projects with several sub-projects and a lot of unit tests
* Let the unit tests run via Gradle (generating a log ~1GB)

Alternate way to reproduce:
* Load several workspaces with a single Gradle project 
* Let the projects run 
* Let a infrastructure test run via Node (generating log >1GB)

I don't know if it has something to do with Gradle in particular. My focus lies more on the huge log. My impression is that the more console output there is the more likely is a crash. but that could be a red herring.

### Expected behavior

No crashes. :)

### Material Theme Version

7.14.2

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2022.2.3 (Ultimate Edition)
Build #IU-222.4345.14, built on October 5, 2022
Runtime version: 17.0.4.1+7-b469.62 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.0.8-200.fc36.x86_64
GC: G1 Young Generation, G1 Old Generation
Memory: 3072M
Cores: 16
Registry:
    caches.indexerThreadsCount=14
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    some.awesome (1.14)
    ski.chrzanow.foldableprojectview (1.1.4)
    org.antlr.intellij.plugin (1.19.2)
    net.vektah.codeglance (1.5.4)
    intellij-clock (2.0.0)
    com.vincentp.gruvbox-theme (0.5.5)
    com.jetbrains.php.framework (222.4345.21)
    com.intellij.plugins.watcher (222.4345.14)
    com.intellij.nativeDebug (222.4345.14)
    com.intellij.ideolog (203.0.30.0)
    tarn.gradle.dependencies (1.6.2)
    org.jetbrains.kotlin (222-1.7.21-release-272-IJ4167.29)
    com.intellij.guice (222.4345.14)
    org.jetbrains.idea.grammar (2021.1.2)
    String Manipulation (9.6.1)
    nb-mind-map-idea (1.5.2)
    com.github.platan.gradle-dependencies-formatter (0.6.1)
    Spock Framework Enhancements (0.12)
    GrepConsole (12.15.211.6693.1)
    Gradle View (4.0.0)
    zielu.gittoolbox (212.10.1)
    mobi.hsz.idea.gitignore (4.4.2)
    com.ppolivka.gitlabprojects (2.0.6)
    com.mallowigi (73.0.0)
    PlantUML integration (5.19)
    org.jetbrains.plugins.vue (222.4345.21)
    mdx.js (222.4345.14)
    cucumber-javascript (222.4345.14)
    com.intellij.plugins.webcomponents (222.4345.14)
    com.intellij.plugins.html.instantEditing (222.4345.14)
    com.jetbrains.plugins.jade (222.4345.14)
    com.dmarcotte.handlebars (222.4345.14)
    org.asciidoctor.intellij.asciidoc (0.37.54)
    com.intellij.kubernetes (222.4345.14)
    ru.adelf.idea.dotenv (2022.2)
    org.jetbrains.kotlin-js-inspection-pack-plugin (0.0.10)
    org.jetbrains.compose.desktop.ide (1.2.1)
    izhangzhihao.rainbow.brackets (2022.3.4-ij)
    com.intellij.bigdatatools (222.3345.33)
    com.haulmont.jpab (2022.4.6-222)
    GradleDependenciesHelper (1.16)
    CMD Support (1.0.5)

Kotlin: 222-1.7.21-release-272-IJ4167.29
Current Desktop: KDE
```

**Comment by mallowigi** [comment]
Do you have a project I can reproduce on?

**Comment by Smolli** [comment]
I can reproduce it with the official [`spring-boot`](https://github.com/spring-projects/spring-boot) project every time I run it. but it dawns to me that this is a general problem with IDEA bc I can reproduce it with a vanilla install as well. but it would help if you can verify that the problem exists.

steps to reproduce:
* import the `spring-boot` project
* run `gradle test` via the Gradle menu (`Tasks` -> `verification` -> `test`)

**Comment by Smolli** [comment]
spring boot is the example repo.

**Comment by mallowigi** [comment]
Ok, I'll take a look when I can

**Comment by Smolli** [comment]
tank you!

**Comment by mallowigi** [comment]
I've tried to run the tests, so far I cannot reproduce this issue. In general there's a consensus that this plugin has performance issues, but I have absolutely no idea how to fix such issues, and especially when they reproduce only in certain resource hogging conditions.

There's nothing I can say except that try to disable the plugin if that's what cause the freezes. In daily use for small to medium projects, it should not be an issue. but if you need to work within huge projects, in your case I would disable the plugin and use the lite one instead, or try to run the tests from outside at least.

**Comment by Smolli** [comment]
that's ok. i filed an official bug report at Jetbrains 'cause it looks like IDEA itself is the reason. thanks for your support!
