### ISSUE TITLE
[Bug]: Code changes don't show in terminal after material theme ui install

### ISSUE THREAD

**Issue by Kiefna** [mallowigi/material-theme-issues#275]
### Describe the bug

After a fresh install of pycharm 2022.2.4 for mac, if material theme ui is installed, any code changes made after that point cannot be detected until theme is disabled. 

### To Reproduce

1. Download a fresh install of pycharm 2022.2.4 for mac (macbook 16 2019 intel) 
2. Go to plugins, install Material Theme UI. 
3. Make changes anywhere through pycharm
4. Check for those changes in terminal.

### Expected behavior

Code changes show in terminal. (It's as if every change you make is superficial)

### Material Theme Version

v7.14.2

### IDE

PyCharm

**Comment by mallowigi** [comment]
Do you see any errors ? Can you give the list of the plugins you use?

And what do you mean by "not detect changes"? Can you show a screen video of such behavior?

**Comment by Kiefna** [comment]
Fresh install, no other plugins.
No visible errors. 
I'll grab a video.

**Comment by Kiefna** [comment]
Apologies, appears to have been pycharm's fault. A corrupted settings file after the 2022.4 update
