### ISSUE TITLE
Custom color scheme file colors cant override VCS colors

### ISSUE THREAD

**Issue by mcstarioni** [mallowigi/material-theme-issues#28]
I could make it work with default themes, like Material Oceanic, but it doesn't work with custom color scheme for some reason.
As i understood, color scheme colors work only through color theme. So if I choose default material color scheme with non-default color theme file colors would not work. When i apply appropriate theme, they do work. And as i see they do work by applying colors from scheme to VCS colors.  So probably the issue in a mechanism of copying those colors in non-default themes.

**Comment by mallowigi** [comment]
I've taken a better look at the feature and how it is handled by JetBrains, and I came to the conclusion that even though it is set via the Color Scheme settings, File Colors are part of the underlying UI Theme. You can look by yourself like this:

1. Use an IDE without the Material Theme
2. Install a Theme, for example DRacula
3. Modify a file with version control active
4. You should see that the modified file color is the one from the DRacula Theme's attached color scheme, i.e. DRacula
5. Switch color scheme to DaRcula (the JetBrains one)
6. You will see that the modified color is still the one from DRacula, even though the color scheme is DaRcula.

It's the same behavior applied with the Material Theme plugin, so I'm closing this one. If needed, you can create an issue in JetBrains' YouTrack bug tracker to make the process less awkward.
