### ISSUE TITLE
[Bug]: The colors in IDEA don't change according to the theme

### ISSUE THREAD

**Issue by SupianIDz** [mallowigi/material-theme-issues#281]
### Describe the bug

**1.** There are several displays that do not respect the theme, in this image the pop up is not the same white, different from the previous version.'
![2](https://user-images.githubusercontent.com/37969970/205410077-155151e9-5d42-4923-b31c-b115f2e4d8c2.png)

whereas this pops up normally when the new UI is turned off or downgrade using the previous version of the Material Theme

![1](https://user-images.githubusercontent.com/37969970/205410180-646c6bd0-e94c-48d5-8416-6d5b2230d1ca.png)

----------------

**2.** There are some icons that blend with the theme color
![3](https://user-images.githubusercontent.com/37969970/205410273-00001681-5754-4859-9132-098855874f79.png)

----------------

**3.** There are some folders that are not included in the folder with the icon (or regular folder) but the material icon does not change it.
![4](https://user-images.githubusercontent.com/37969970/205410335-0fc61d75-3eb7-4398-9964-6015cd1b3794.png)

### To Reproduce

1. Install latest Jetbrains Intellij Idea
2. Install latest material ui
3. Install latest material icon
4. Use theme `material lighter`
5. Try enable and disable new UI
6. Open an pop up as example.

### Expected behavior

1. The color of the popup should be the same as the other sections, as it was in the previous version
2. Icon color should not blend with the theme
3. All folders should change, including non-special folders

### Material Theme Version

v8.3.1

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2022.3 (Ultimate Edition)
Build #IU-223.7571.182, built on November 29, 2022
Licensed to Supian M
Subscription is active until March 6, 2023.
Runtime version: 17.0.5+1-b653.14 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.0-53-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 968M
Cores: 4
Registry:
    editor.focus.mode.color.light=d2d4d5
    ide.editor.tab.selection.animation=true
    debugger.new.tool.window.layout=true
    ide.new.editor.tabs.vertical.borders=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=d2d4d5
    eslint.additional.file.extensions=svelte

Non-Bundled Plugins:
    com.jetbrains.plugins.ini4idea (223.7571.203)
    com.fwdekker.randomness (2.7.5)
    com.intellij.apacheConfig (223.7571.203)
    com.intellij.plugins.watcher (223.7571.113)
    quokka.js (1.0.366)
    org.intellij.plugins.postcss (223.7571.117)
    com.intellij.ideolog (203.0.30.0)
    com.pinkfloyded.idea-file-path-autocomplete.idea-file-path-autocomplete (0.4.1)
    ski.chrzanow.foldableprojectview (1.1.4)
    org.jetbrains.jumpToLine (0.1.10)
    UpperLowerCapitalize (0.1.1q)
    com.mallowigi (80.0.0)
    zielu.gittoolbox (213.10.2)
    mobi.hsz.idea.gitignore (4.4.4)
    com.intellij.plugins.html.instantEditing (223.7571.117)
    com.jetbrains.php (223.7571.182)
    izhangzhihao.rainbow.brackets (2022.3.5)
    com.jetbrains.php.framework (223.7571.203)
    com.chrisrm.idea.MaterialThemeUI (8.3.1)
    cn.yiiguxing.plugin.translate (3.4.0)
    ru.adelf.idea.dotenv (2022.3)
    com.mallowigi.colorHighlighter (14.0.0)
    org.endpointdeps.EndpointDependencies (1.3)
    com.jetbrains.php.blade (223.7571.182)
    com.laravel_idea.plugin (6.1.1.223)

Kotlin: 223-1.7.20-release-201-IJ7571.182
Current Desktop: X-Cinnamon
```

**Comment by mallowigi** [comment]
Please create the issues related to the Material Icons in the right repository, thank you.

Regarding the search everywhere, this is apparently a new style named Popup.background, and I have set this to NotificationColor, which is indeed wrong. I'll fix that in a further release
