### ISSUE TITLE
[Feature]: Hide Floating Button in the bottom right (Chrome extension)

### ISSUE THREAD

**Issue by doggy8088** [mallowigi/material-theme-issues#283]
### Describe the feature

I'd like to hide Floating Button in the bottom right.

### Use Cases

I'd like to have an option to hide Floating Button in the bottom right.

### Material Theme Version

10.0.0

### IDE

Other (AppCode, CLion, GoLang...)

### System Info

```shell
Version 108.0.5359.94 (Official Build) (64-bit)
```

**Comment by mallowigi** [comment]
wrong repo
