### ISSUE TITLE
[Bug]: Material Custom File Colors settings don't work

### ISSUE THREAD

**Issue by makarichevss** [mallowigi/material-theme-issues#285]
### Describe the bug

Custom File Colors settings (from Material theme) don't override File Status Colors settings (in IntelliJ).

### To Reproduce

1) I installed Material Theme plugin and turned on Material File Status Colors.

![2022-12-11_203533](https://user-images.githubusercontent.com/62963044/206919828-abe3f911-36d1-4942-81ef-a2b9b28e4469.jpg)

2) In Custom File Colors section I changed the color of the modified file to pink. But the color of modified file didn't change and remained aquamarine.

![2022-12-11_203515](https://user-images.githubusercontent.com/62963044/206919817-edc3c47e-66ce-4707-8b80-21ac4a760dd4.jpg)

3) I opened File Status Colors section in IntelliJ - and there is that aquamarine color of the modified file.

![2022-12-11_203438](https://user-images.githubusercontent.com/62963044/206919803-30a2aae6-ff64-48b6-b10f-67e26ab41cb7.jpg)

This is only the example of one file color option. All the other color settings in Custom File Colors don't override File Status Colors.
Please fix this bug.

### Expected behavior

Custom File Colors settings (from Material theme) should override File Status Colors settings (in IntelliJ).

### Material Theme Version

v8.3.2

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2022.3 (Ultimate Edition)
Build #IU-223.7571.182, built on November 29, 2022
Licensed to Sergey Makarichev
Subscription is active until May 5, 2023.
Runtime version: 17.0.5+1-b653.14 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Registry:
    editor.focus.mode.color.light=98b6ff
    external.system.auto.import.disabled=true
    ide.new.editor.tabs.vertical.borders=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=98b6ff
    feature.suggester.enable.suggesters=true

Non-Bundled Plugins:
    some.awesome (1.14)
    com.jetbrains.darkPurpleTheme (1.3)
    com.github.catppuccin.jetbrains (2.0.6)
    com.markskelton.one-dark-theme (5.7.2)
    AceJump (3.8.9)
    DBN (3.3.5790.0)
    String Manipulation (9.6.1)
    MavenRunHelper (4.23.222.2964.0)
    com.chrisrm.idea.MaterialThemeUI (8.3.2)
    com.haulmont.jpab (2022.5.1-223)
    com.cursiveclojure.cursive (1.12.5-2022.3)
    com.mallowigi (80.0.0)
    mobi.hsz.idea.gitignore (4.4.4)

Kotlin: 223-1.7.20-release-201-IJ7571.182
```

**Comment by mallowigi** [comment]
Are you using a custom theme?

**Comment by makarichevss** [comment]
Yes

**Comment by mallowigi** [comment]
There is known issue with custom themes (or when using a different color scheme than the one bundled with the theme).

However, bundled themes should be working just fine if you're not using a custom color scheme.

https://share.cleanshot.com/1gJIhF

I'll leave this open to try again to fix this issue though.
