### ISSUE TITLE
[Bug]: IntelliJ Light find box dark

### ISSUE THREAD

**Issue by justrhysism** [mallowigi/material-theme-issues#297]
### Describe the bug

When using Light/Dark OS sync, the IntelliJ Light theme is has a dark find box and mis-aligned buttons

<img width="978" alt="image" src="https://user-images.githubusercontent.com/1326759/211686528-99666ae8-463c-4437-9c9a-efc363b984e1.png">

### To Reproduce

1. Tick "Appearance & Behaviour" > "Sync with OS"
2. Click three vertical dots and select "IntelliJ Light" for "Light"
3. Open file and open the "Edit" > "Find" > "Find..."

### Expected behavior

The find box to be light and icons aligned correctly.

### Material Theme Version

v8.4.1

### IDE

WebStorm

### Logs/Screenshots

```shell
<img width="978" alt="image" src="https://user-images.githubusercontent.com/1326759/211686528-99666ae8-463c-4437-9c9a-efc363b984e1.png">
```

**Comment by mallowigi** [comment]
will be fixed for next version
