### ISSUE TITLE
[Bug]: Weird shadow below editor tabs after more than one line of tabs

### ISSUE THREAD

**Issue by apouche** [mallowigi/material-theme-issues#300]
### Describe the bug

Since upgrading to Android Studio 2022.1, there are some weird shadows below the editor tabbar once we reach more than one line of tabs.

This can be easily observed in this screenshot:
![CleanShot 2023-01-23 at 20 16 49@2x](https://user-images.githubusercontent.com/528492/214130636-b0cb0924-4760-4791-a124-ed097f5e157a.png)

### To Reproduce

Download Android Studio 2022.1.
Install Material Theme plugin v 7.5.4
Open several tabs until you reach two lines
Observe how some weird shadows are added below

### Expected behavior

The shadows should not be there (or at least we should be able to disable them)

### Material Theme Version

7.5.4

### IDE

Android Studio

**Comment by mallowigi** [comment]
It's a feature, it's called Tabs Shadow.
