### ISSUE TITLE
[Bug]: File Icons not work

### ISSUE THREAD

**Issue by bartosz-szymanski** [mallowigi/material-theme-issues#302]
### Describe the bug

Hi.

After updating WebStorm and Material Theme file icons are not working and all of them looks like:
![image](https://user-images.githubusercontent.com/19731560/216610195-6d6e41e3-8df6-4b30-8aa2-e8d5222ebaa4.png)

### To Reproduce

Open IDE

### Expected behavior

Previously, all icons were adjusted to file name / file extension

### Material Theme Version

v8.4.1

### IDE

WebStorm

### System Info

```shell
* MacOS
* WebStorm 2022.3.2
* Material Theme 8.4.1
```

**Comment by mallowigi** [comment]
wrong repository
