### ISSUE TITLE
Support Rainbow Variables from Rainbow Brackets and Semantic Highlighting in General

### ISSUE THREAD

**Issue by GroxDots** [mallowigi/material-theme-issues#303]
### Describe the feature

It is semantic highlighting.

### Use Cases

It is used to highlight each variable in a color of their own.

### Material Theme Version

any

### IDE

IntelliJ IDEA

### System Info

```shell
Material Theme UI, Rainbow Brackets
```

**Comment by mallowigi** [comment]
Huh?
