### ISSUE TITLE
[Bug]: Every time I restart Pycharm, my custom color scheme goes away

### ISSUE THREAD

**Issue by RheingoldRiver** [mallowigi/material-theme-issues#306]
### Describe the bug

Every time I restart pycharm, my custom color scheme is unset from my preferences.

### To Reproduce

1. Open Pycharm
2. Not sure if relevant: Create a settings repository and sync it for backup
3. Select a custom color scheme
4. Save your settings
5. Sync your settings to your settings repo (again, possibly optional)
6. Quit pycharm
7. Reopen pycharm
8. Observe your color scheme is reset to Darcula

### Expected behavior

Your color scheme should have been the custom scheme.

### Material Theme Version

v7.14.2

### IDE

PyCharm

### Logs/Screenshots

Wrong theme:
![image](https://user-images.githubusercontent.com/18037011/219560275-a416d56f-c771-4004-b279-e79ae6c188d5.png)

This is the one I want:
![image](https://user-images.githubusercontent.com/18037011/219560348-e9789ec1-5ac0-4a1f-b01e-935dfe023244.png)

Here are the instructions I used to create the custom theme: https://github.com/RheingoldRiver/misc_settings/issues/1 - basically I didn't like the Oceanic redesign so I hand-copied the old version of the skin and put it in the folder. I'm not sure if this is related to the problem.

**Comment by mallowigi** [comment]
https://material-theme.com/docs/configuration/custom-themes/#color-scheme

Have you read this? I think this is your issue. Closing this unless it's not the case.

**Comment by RheingoldRiver** [comment]
ahhh no, and that wasn't actually the problem, but in trying to find the menu, i DID find the problem. Here is what was wrong in case someone else opens a similar ticket. I had two different color schemes selected in two different places (and maybe this is actually a different bug, because it shouldn't be possible I think):

So, 

1. As I explained in the issue linked above (here it is again: https://github.com/RheingoldRiver/misc_settings/issues/1), I use AppData to "export" my theme so that I can "import" it back into PyCharm on this screen, and set it on this page:

![image](https://user-images.githubusercontent.com/18037011/219716753-e866225d-b8af-48ab-9a04-dde60ca88397.png)

3. On this screen, it still said Darcula, even though I had set it elsewhere in settings to what I actually wanted it:

![image](https://user-images.githubusercontent.com/18037011/219716301-5d7ef62e-d836-4518-9bd9-991a07f9e31a.png)

And so that's what I believe Material was re-applying every single time I opened Pycharm. Probably this has never been reported before because no one is neurotic enough to save their colors in their OS and copy them from folder to folder like I do haha

So if you could hook into "user sets a color theme" and then remember it, that would be fantastic.

**Comment by mallowigi** [comment]
This is a good question,

**Comment by mallowigi** [comment]
This feature will be enabled next release

**Comment by RheingoldRiver** [comment]
Fantastic, thanks so much!
