### ISSUE TITLE
[Bug]: The Project View color settings do not get applied in IntelliJ IDEA 2022.3.1

### ISSUE THREAD

**Issue by antimoroma** [mallowigi/material-theme-issues#309]
### Describe the bug

In can't find a way to change the color of font in the Project view, change theme or even if i change theme and select Settings -> Projcet View -> Configure Directory Colors , Colors of directory (and file) shown in Project View stay the same.

May be i change change some config in Intellij non related to Material but anyway it seems that matherial cannot change this colo in any way, i can't rember exactly sorry

Thank you for any help

![Screenshot 2023-02-20 at 10 26 15](https://user-images.githubusercontent.com/7354134/220066084-5ec5997b-f5cf-4ac6-9f5a-fb6f7bbf04a9.png)

### To Reproduce

In MAtherial Theme UI inside Intellij Settings 
Go to : Settings -> Projcet View -> Configure Directory Colors , Colors of directory (and file) shown in Project

and try to change color . Nothing happen 

### Expected behavior

Colors of of Dircetory / Files shown in Project Panel should change

### Material Theme Version

8.4.1  (it happens i think with older version)

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2022.3.1 (Ultimate Edition)
Build #IU-223.8214.52, built on December 20, 2022
Licensed to *****
Subscription is active until April 27, 2023.
Runtime version: 17.0.5+1-b653.23 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.6.3
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 12
Metal Rendering is ON
Registry:
    editor.focus.mode.color.light=005454
    compiler.automake.postpone.when.idle.less.than=100
    ide.editor.tab.selection.animation=true
    debugger.new.tool.window.layout=true
    compiler.document.save.enabled=true
    compiler.document.save.trigger.delay=10
    ide.new.editor.tabs.vertical.borders=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=005454
    editor.minimap.enabled=true


Kotlin: 223-1.7.21-release-272-IJ8214.52
```

**Comment by mallowigi** [comment]
duplicate

**Comment by mallowigi** [comment]
Have you tried the Material File Status Colors ?

**Comment by antimoroma** [comment]
Can't find the entry in Colors scheme i.e. "Material file colors" is missing
EDITOR -> COLOR SCHEME -> MATERIAL FILE COLORS

https://material-theme.com/docs/configuration/file-status-colors/

Is this in another place?

I found Custom file Colurs (not Material File Colors) in color scheme, but changing for example Dircetories background nothing change.

May be i'm missing something sorry

**Comment by mallowigi** [comment]
I thought you were talking about the font color

**Comment by SirMishaa** [comment]
@mallowigi Hello, 
I'm running on Remote Development for WSL (it uses JetBrains Gateway for the backend + Code With Me client)

![image](https://user-images.githubusercontent.com/42717232/221249327-610c9af1-443f-4310-aec5-36a2cfc1890a.png)


It looks like I have the same issue : 

![image](https://user-images.githubusercontent.com/42717232/221248865-7bbe0b5c-e7b7-4278-9628-08562c7e957a.png)

When I'm running Rubymine  2022.3.2, it's fine : 

![image](https://user-images.githubusercontent.com/42717232/221249187-b0f7720b-eb3d-4538-af88-ca4c310fb813.png)

Is that a bug from your side ? Development on Windows is a pain in the ass that's why I prefer running IDE on WSL when I'm not on my mac

Thank you

**Comment by mallowigi** [comment]
Is this still happening?

**Comment by mallowigi** [comment]
I think I found a better solution. Will be available next release
