### ISSUE TITLE
Please do not open "what's new" pages when the plugin updates

### ISSUE THREAD

**Issue by LoganDark** [mallowigi/material-theme-issues#31]
![image](https://user-images.githubusercontent.com/4723091/140318853-efe20361-1343-43cd-8fa2-874cea6edcfd.png)

:/

**Comment by mallowigi** [comment]
there's a setting for that. Did you turn it off ?

**Comment by LoganDark** [comment]
I didn't know that setting existed, as this feature did not exist in the version I was updating from
