### ISSUE TITLE
[Bug]: The activated tool window bar is too difficult find which on is activaed in dark mode 

### ISSUE THREAD

**Issue by mqliutie** [mallowigi/material-theme-issues#315]
### Describe the bug

It is not easy to find activated tool.  see below

<img width="926" alt="image" src="https://user-images.githubusercontent.com/11795518/224916837-791f2971-926d-4b7f-a425-e27bb76f4f46.png">

I can not know `Git` is activated. I want to change the background color and font color, but I can not find a way

### To Reproduce

1. Choose `Github Dark（material）`
2. click anyone item in tool window bar

### Expected behavior

show me clearly

### Material Theme Version

7.14.2

### IDE

WebStorm

### System Info

```shell
macOS  12.6
```

### Logs/Screenshots

```shell
<img width="926" alt="image" src="https://user-images.githubusercontent.com/11795518/224916837-791f2971-926d-4b7f-a425-e27bb76f4f46.png">
```

**Comment by mqliutie** [comment]
@mallowigi no, all of dark mode themes

**Comment by mallowigi** [comment]
I just realized you're talking about an older version. I will close it because I'm not working on older versions. If it happens on latest version please update me.
