### ISSUE TITLE
[Bug]: Light owl theme highlights the text making difficult to read

### ISSUE THREAD

**Issue by MisterOryon** [mallowigi/material-theme-issues#316]
### Describe the bug

When WebStorm highlights a text, the light owl theme makes the text unreadable.

![image](https://user-images.githubusercontent.com/55950346/225703675-a47aeab0-0366-4c98-90ca-08cc92122ee9.png)

### To Reproduce

Just choose the light owl theme, and write a condition in which you check the `typeof` of the variable or `instanceof` of the class.

### Expected behavior

Please change highlight text color, for example the highlight text color in night owl is greet.

![image](https://user-images.githubusercontent.com/55950346/225705643-23b9a5b4-5d22-46e3-821e-bf79262fb0fb.png)

### Material Theme Version

v8.5.0

### IDE

WebStorm

### System Info

```shell
WebStorm 2023.1 EAP
Build #WS-231.8109.51, built on March 10, 2023
Licensed to WebStorm EAP user: Clément Médart
Expiration date: April 9, 2023
Runtime version: 17.0.6+10-b829.5 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.2.6-arch1-1
GC: G1 Young Generation, G1 Old Generation
Memory: 750M
Cores: 12
Registry:
    editor.focus.mode.color.light=93a1a1
    ide.editor.tab.selection.animation=true
    debugger.new.tool.window.layout=true
    ide.new.editor.tabs.vertical.borders=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=93a1a1

Non-Bundled Plugins:
    ru.adelf.idea.dotenv (2023.1)
    org.jetbrains.plugins.astro (231.8109.91)
    com.chrisrm.idea.MaterialThemeUI (8.5.0)
    com.intellij.lang.jsgraphql (3.4.0)
    com.mallowigi (88.0.0)

Current Desktop: sway
```

**Comment by mallowigi** [comment]
Please make sure you get the latest color scheme updates
