### ISSUE TITLE
What are the icons used in the What's New screenshot?

### ISSUE THREAD

**Issue by jahirfiquitiva** [mallowigi/material-theme-issues#317]
### Describe the bug

Hi

I know this isn't the right place to ask this, but I wanted to ask, what are the icons used in this screenshot (from the What's New website).

Please let me know which plugin you used for that, or how to enable them, thanks!

![226142917-85531978-53d4-4b80-b989-02ace0585603](https://user-images.githubusercontent.com/10360816/226142986-fd7c66e4-3771-455a-a7bc-fd839e37902d.png)

### To Reproduce

N/A

### Expected behavior

N/A

### Material Theme Version

8.5.0

### IDE

IntelliJ IDEA

### System Info

```shell
* OS: MacOS
* IntelliJ Version: 2022.3.3
```

**Comment by mallowigi** [comment]
They are the default icons from the new ui
