### ISSUE TITLE
[Bug]: TS keywords being highlighted inside TSX.

### ISSUE THREAD

**Issue by tom-ricci** [mallowigi/material-theme-issues#319]
### Describe the bug

When I write content in TSX, syntax highlighting is applied to keywords when it shouldn't be. It doesn't happen to JSX.

![image](https://user-images.githubusercontent.com/79022795/226795627-d95c272d-807c-40a3-ab33-a96b29727075.png)

### To Reproduce

1. Scaffold a React project with typescript
2. Write some content in a TSX file

### Expected behavior

The syntax shouldn't be highlighted, like it is in JSX:

![image](https://user-images.githubusercontent.com/79022795/226795921-3ff0185d-db8e-4d77-8c44-18b6e8f01b06.png)

### Material Theme Version

v8.4.1

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2022.3.3 (Ultimate Edition)
Build #IU-223.8836.41, built on March 9, 2023
Licensed to Thomas Ricci
Subscription is active until March 5, 2024.
For educational use only.
Runtime version: 17.0.6+1-b653.34 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.19.0-35-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
    editor.focus.mode.color.light=6b727d
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=6b727d

Non-Bundled Plugins:
    com.vermouthx.xcode-theme (1.6.1)
    com.github.tth05.minecraft-nbt-intellij-plugin (1.5.4)
    cn.yiiguxing.plugin.md.palette (1.4)
    org.intellij.plugins.postcss (223.7571.117)
    net.antelle.intellij-xcode-dark-theme (1.2.4)
    lermitage.intellij.extra.icons (2023.1.2)
    com.demonwav.minecraft-dev (2022.3-1.6.2)
    MetricsReloaded (1.12)
    me.mbolotov.cypress.pro (3.6)
    Pythonid (223.8836.41)
    com.chrisrm.idea.MaterialThemeUI (8.4.1)
    mobi.hsz.idea.gitignore (4.4.4)

Kotlin: 223-1.8.0-release-345-IJ8836.41
Current Desktop: GNOME
```

**Comment by mallowigi** [comment]
I know, there is a similar issue with keywords inside comments or as variable names. I don't have a particular way of fixing it at the moment sadly.

**Comment by mallowigi** [comment]
I think I found a solution. I'll deploy a solution soon
