### ISSUE TITLE
CLion new feature: improve classes UI.

### ISSUE THREAD

**Issue by math-cheveux** [mallowigi/material-theme-issues#32]
C++ classes are generally coded -separately from each others- in two files, the .h and the .cpp files. But it means it takes twice the space in the file tree and in the file tab.
It would be good to add an option to group these files in the "Project" tree as a "class file". And in the editor, do either a tab menu (like IntelliJ with JavaFX and the SceneBuilder, see the image below), or a split view (horizontal or vertical).
![Capture d’écran 2021-11-05 102606](https://user-images.githubusercontent.com/52175278/140488551-d80c053f-8f4e-4080-87ce-ab95043f42c5.png)

Moreover, in IntelliJ, the class files icon changes if the class is abstract or not, final or not, etc. Therefore, it would nice to apply this behaviour on the "class files" cited above.

**Comment by mallowigi** [comment]
No no no, this is way outside the scope of this plugin, sorry. I am not familiar with such things.
