### ISSUE TITLE
[Feature]: Gruvbox theme

### ISSUE THREAD

**Issue by tracphil** [mallowigi/material-theme-issues#321]
### Describe the feature

Please add Gruvbox theme to Material Theme UI. The [original](https://github.com/Vincent-P/gruvbox-intellij-theme) theme has been archived and is no longer actively developed.

### Material Theme Version

8.6.0

### IDE

IntelliJ IDEA

**Comment by mallowigi** [comment]
Sorry, this is not something I'm planning to do. Thanks for the idea though.
