### ISSUE TITLE
[Bug]: macOS switching theme (light/dark/auto) resets terminal font

### ISSUE THREAD

**Issue by gregkos** [mallowigi/material-theme-issues#326]
### Describe the bug

While having different light and dark themes selected in the IDE (both Material, both set to use the default font and console font) whenever the OS (macOS) switches from light to dark and vice versa, the console font resets to Material's defaults. Closing and reopening the app restores the correct settings.

I opened up [a bug with JetBrains](https://youtrack.jetbrains.com/issue/WI-70746), tried a few things, it's **not** reproducible without Material Theme UI installed.

### To Reproduce

1. Use macOS
2. Install Material Theme UI
3. Select a different console font than the IDE's default settings
4. Select light and dark themes inside the IDE, make sure they are both using the correct default console font
5. Go to your macOS settings and switch to the other OS theme (either from light to dark or from dark to light — auto causes it too, but you need to wait for sunrise/sundown)
6. Observe the console

### Expected behavior

Console font should still be the default font and size

### Material Theme Version

v8.4.1

### IDE

WebStorm, PHPStorm

**Comment by mallowigi** [comment]
https://material-theme.com/docs/configuration/features-settings/#use-editor-default-font try to disable this setting

**Comment by gregkos** [comment]
These are my settings:

<img width="697" alt="image" src="https://user-images.githubusercontent.com/6676236/229704406-76e145dc-4779-4bcc-b840-33a8e7c9aad4.png">

**Comment by mallowigi** [comment]
And in Other Tweaks > Automatically reset color scheme ?

**Comment by gregkos** [comment]
Disabled!

**Comment by mallowigi** [comment]
And it's still happening?

**Comment by gregkos** [comment]
Yes, consistently. I had uninstalled the plugin because this is fairly disruptive, waited for the next IDE and plugin versions, reinstalled, and it's still happening. 😔

**Comment by gregkos** [comment]
I even tried uninstalling every other plugin, still happening. The only thing I haven't tried is a completely clean install of the IDE, but my work schedule doesn't allow that.

**Comment by mallowigi** [comment]
I'll check if i can reproduce. I thought this would be an issue of the "Automatically reset"

**Comment by gregkos** [comment]
Thank you. Please let me know if I can help in any way — further tests or whatever.

**Comment by mallowigi** [comment]
Currently I am reproducing this without the Material UI

**Comment by gregkos** [comment]
I was able to reproduce it after uninstalling Material UI but before explicitly changing the Theme and Color Scheme. There are some leftovers after uninstalling that might take an IDE or system restart to completely clear up. Are you reproducing while having JetBrains default themes and color schemes for both light and dark modes?

**Comment by mallowigi** [comment]
https://share.cleanshot.com/HwLRzZKg

**Comment by gregkos** [comment]
Hm, I think this is a slightly different issue. Here, I should have added screenshots from the start.

Opening up the IDE, a project, and the console:

<img width="1505" alt="image" src="https://user-images.githubusercontent.com/6676236/229711242-c9a38657-aeaf-4442-971e-090257cd93f2.png">

Switching themes at the OS level, without touching anything in the IDE:

<img width="1505" alt="image" src="https://user-images.githubusercontent.com/6676236/229711397-d72cae55-bff7-41dc-bdc2-bdf4b454eb79.png">

Switching back, still no IDE changes:

<img width="1505" alt="image" src="https://user-images.githubusercontent.com/6676236/229711548-ad57f7c2-8cb3-4958-9f6d-40dc678c9255.png">

Relevant settings (NB - color scheme font and console font unchecked in both light and dark themes, wanting to keep default/same in every scenario):

<img width="1505" alt="image" src="https://user-images.githubusercontent.com/6676236/229711649-16d026b5-6862-4971-83f7-28af24ba0100.png">

**Comment by mallowigi** [comment]
It is relevant, as far as I'm concerned. Switching themes resets the console font, and it doesn't look like it's the plugins fault

**Comment by gregkos** [comment]
I revived my YouTrack issue, and will try to do some further testing myself. Maybe it was changing my font but not the size and that's why I didn't notice. I'll get back to you ASAP.

I gather this hasn't been reported by anybody else? I found a sort of similar but slightly different closed issue.

**Comment by gregkos** [comment]
Did you also try switching OS-level themes instead of the IDE? Could the fact that you have "Use console font instead of the default" enabled be related?

**Comment by mallowigi** [comment]
I remember that I already opened an issue about it in the past.

**Comment by mallowigi** [comment]
> Did you also try switching OS-level themes instead of the IDE? Could the fact that you have "Use console font instead of the default" enabled be related?

If I don't check the checkbox it will use the default font. It shouldn't matter in the results but I'll check as well

**Comment by gregkos** [comment]
#59 looks closely related, but not exactly. #210 would be related, but my settings appear to be persisting just fine.

I'm asking for that checkbox because what I want to do is to use the default font, this is what's failing.

**Comment by gregkos** [comment]
Recent updates to the IDE (2023.1) and the plugin (8.6.2) appear to have resolved the issue. Not sure on which side it was, but looks okay now. Closing this.
