### ISSUE TITLE
[Bug]: Tab menu displaying issue

### ISSUE THREAD

**Issue by TiMkaJK** [mallowigi/material-theme-issues#331]
### Describe the bug

<img width="2198" alt="Screenshot 2023-04-04 at 16 11 32" src="https://user-images.githubusercontent.com/25300317/230613263-4750d1cc-a70e-4859-9abf-032f5e279a71.png">

### To Reproduce

Started from 8.6.0

### Expected behavior

<img width="2184" alt="Screenshot 2023-04-07 at 16 03 03" src="https://user-images.githubusercontent.com/25300317/230613482-4c7b4ad0-8189-4c06-a3d6-1ed64000216c.png">

### Material Theme Version

v8.6.2

### IDE

IntelliJ IDEA

**Comment by mallowigi** [comment]
What is your value of the tab height?

**Comment by TiMkaJK** [comment]
15

**Comment by mallowigi** [comment]
That's the problem, the minimum changed to 24. Because with the new implementation, the end result is different so we had to revise the minima and maxima. Please change to 24 (or more)

**Comment by TiMkaJK** [comment]
it helped, thanks a lot
