### ISSUE TITLE
[Bug]: UI Tabs are being cut off in datagrip

### ISSUE THREAD

**Issue by jimmymain** [mallowigi/material-theme-issues#336]
### Describe the bug

The tabs are being cut off, and I cannot increase the tab size.

![image](https://user-images.githubusercontent.com/2555050/231369554-21c782a2-013a-4d57-925b-53fa1bebeaac.png)

I cannot increase the height further or decrease it, it's disabled.

![image](https://user-images.githubusercontent.com/2555050/231369688-d34cc53b-170b-42b0-8b95-fef21ce7b015.png)

### To Reproduce

1. Ensure tabs are enabled for editing.
2. Install brand new data grip 2023.1
3. Use the new theme / layout in datagrip.
4. See that tabs cannot be read.

### Expected behavior

Tabs can be read.

### Material Theme Version

v8.6.2

### IDE

DataGrip

### System Info

```shell
DataGrip 2023.1
Build #DB-231.8109.163, built on March 27, 2023
Licensed to Craig Main
Subscription is active until April 30, 2023.
Runtime version: 17.0.6+10-b829.5 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Registry:
    editor.focus.mode.color.light=415967
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=415967

Non-Bundled Plugins:
    String Manipulation (9.7.1)
    IdeaVIM (2.1.0)
    com.mallowigi (90.0.0)
    com.chrisrm.idea.MaterialThemeUI (8.6.2)
```

**Comment by jimmymain** [comment]
Yes, thanks, I can confirm that by manually increasing the value and clicking apply - it's working now.

**Comment by bariod** [comment]
![image](https://user-images.githubusercontent.com/35639254/232448384-877c37f3-c958-4a3a-af35-ba79769ac42c.png)
the tooltip should also be updated then @mallowigi
