### ISSUE TITLE
[Bug]: Tip of the Day window issue

### ISSUE THREAD

**Issue by oldium** [mallowigi/material-theme-issues#349]
### Describe the bug

When the Material Theme UI plugin is enabled, the appearance of Tip of the Day window is broken. When I disable the plugin, it is drawn correctly.

### To Reproduce

1. Start PyCharm
2. Open Help/Tip of the Day
3. Observe small corruption of the dialog
4. Use TAB several times or mouse to get to Don't show tips on startup
5. Observe additional corruption of the dialog

### Expected behavior

The dialog is drawn without artefacts.

### Material Theme Version

v8.6.3

### IDE

PyCharm

### System Info

```shell
PyCharm 2023.1.1 (Professional Edition)
Build #PY-231.8770.66, built on April 27, 2023
Licensed to ***
Subscription is active until July 31, 2023.
Runtime version: 17.0.6+10-b829.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
    editor.focus.mode.color.light=5a5d63
    ide.editor.tab.selection.animation=true
    debugger.new.tool.window.layout=true
    ide.new.editor.tabs.vertical.borders=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=5a5d63

Non-Bundled Plugins:
    dev.polek.adbwifi (1.2.5)
    com.tang (1.3.20-IDEA231)
    com.tabnine.TabNine (1.0.11)
    com.alayouni.ansiHighlight (23.1.0)
    ski.chrzanow.foldableprojectview (1.1.5)
    com.chrisrm.idea.MaterialThemeUI (8.6.3)
    com.mallowigi (90.0.0)
    mobi.hsz.idea.gitignore (4.5.0)
```

### Logs/Screenshots

![corruption-1](https://github.com/mallowigi/material-theme-issues/assets/1260936/841aba08-57ab-49cf-9334-c34ffe20eeb0)
![corruption-2](https://github.com/mallowigi/material-theme-issues/assets/1260936/06a79170-5ab6-444a-9a79-0d000f2b189f)

**Comment by mallowigi** [comment]
Can't reproduce on Mac. I'll try to see if it only happens on Windows whenever I can have access to a Windows machine

**Comment by mallowigi** [comment]
Reproduced, and fixed. Will be available shortly.
