### ISSUE TITLE
High contrast - why is this a premium feature?

### ISSUE THREAD

**Issue by jdphenix** [mallowigi/material-theme-issues#35]
**Is your feature request related to a problem? Please describe.**
Consider enabling high contrast mode to be a free feature.

**Describe alternatives you've considered**
Not using your theme. Or buying it on principle.

**Additional context**
High contrast is an accessibility feature.

**Comment by mallowigi** [comment]
High contrast is not an accessibility feature. The high contrast made by JetBrains is.

The high contrast option allows you to darken/brighten the foreground and background to increase the contrast. Nothing related to accessibility.

The reason I put it as a premium feature is that I am doing it in the fly, as opposed as regular themes that do not have this option. Moreover this feature works in every theme, not only the ones provided by the plugin.

In the future I'm planning to release an extension of this feature to control the amount of contrast applied.

**Comment by mallowigi** [comment]
By the way I originally planned to release the sole feature separately from the main plugin, as a paid plugin but much cheaper. I didn't have the time to work on extracting the feature until now but I'll try to do it in the future.

**Comment by jdphenix** [comment]
Can you provide an example or two or what the high contrast premium feature allows one to do? I fail to see how what you described, "allows you to darken/brighten the foreground and background to increase the contrast", isn't clearly an accessibility concern.

**Comment by mallowigi** [comment]
Everything is documented in the website, please check there.

--
Elior

**Comment by jdphenix** [comment]
I see, thank you.
