### ISSUE TITLE
[Bug]: Buttons and controls rendering glitches. Random graphics show up behind buttons and Tip of the Day checkbox

### ISSUE THREAD

**Issue by AMDphreak** [mallowigi/material-theme-issues#353]
### Describe the bug

Random controls show up in the background. Random text showed up, which could not be seen anywhere else on screen. It may be text for one of the tips that is not currently showing. The buttons flicker when hovered, and when clicked. The margins around the buttons also inherit random artefacts. This is a fresh install of Windows 11 stable version, not even 24 hours old.

Based on bug report on IntelliJ: https://youtrack.jetbrains.com/issue/IDEA-320340/Button-control-and-Tip-of-the-Day-rendering-problem

### To Reproduce

1. Change theme...any theme seems to work.
2. Restart IJ
3. Move cursor over the "Do not show tips on startup" check box.
4. Move cursor over any button control on screen except disabled buttons. Try clicking them and moving the cursor around while depressed (the button, not you).
5. Resize the Tip of the Day window to see that the rendering reverts to normal, then go to steps 3 and 4 again to see the bug keeps going.

### Expected behavior

Buttons and check boxes look like normal and don't have random graphics show up behind them.

### Material Theme Version

v8.6.4

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2023.1.2 (Community Edition)
Build #IC-231.9011.34, built on May 16, 2023
Runtime version: 17.0.6+10-b829.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2022M
Cores: 16
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    Dart (231.9065)
    com.thvardhan.gradianto (5.1)
    io.flutter (73.1.1)

Kotlin: 231-1.8.21-IJ9011.34
```

### Logs/Screenshots

[Logs](https://youtrack.jetbrains.com/api/files/74-1669347?sign=MTY4NTE0NTYwMDAwMHwxMS0xMTY3ODcwfDc0LTE2NjkzNDd8elFISFFyV2xDVWxIWEotVkRDVHI2%0D%0AYmY0Y0ZyV09xNndPckh1TVVaanpsbw0K%0D%0A&updated=1684088844390&forceDownload=true)

[Video](https://youtu.be/Fp-XwI7Av98)

![image](https://github.com/mallowigi/material-theme-issues/assets/1058978/acb50a9e-f273-4580-8b4c-d84d4781253c)

**Comment by mallowigi** [comment]
I need to get my hands on a windows machine. This looks like something only happening on windows.

**Comment by mallowigi** [comment]
Fixed. Will be available next release
