### ISSUE TITLE
[Bug]: Tab color error

### ISSUE THREAD

**Issue by heartzwh** [mallowigi/material-theme-issues#354]
### Describe the bug

When I open a project from the Project in the Toolbox, the background color of the EditorTab will display an error.

### To Reproduce

Already use vertical EditorTab display

1. Open Toolbox
2. Select rider project
3. Open Rider project

### Expected behavior

Vertical EditorTab:
![image](https://github.com/mallowigi/material-theme-issues/assets/28264550/e2d7a256-e5c4-4f30-ae62-89c0e98f9eac)

Settings:
![Snipaste_2023-06-07_09-23-50](https://github.com/mallowigi/material-theme-issues/assets/28264550/a9dcba8d-d2d9-4500-b124-683af1b48a22)
![Snipaste_2023-06-07_09-24-34](https://github.com/mallowigi/material-theme-issues/assets/28264550/dc9047d4-3fda-4401-8272-e5475c1889fd)
![Snipaste_2023-06-07_09-24-42](https://github.com/mallowigi/material-theme-issues/assets/28264550/eab9f08d-634d-46d7-b230-305d7cb43bae)

### Material Theme Version

v8.6.4

### IDE

Rider

### System Info

```shell
JetBrains Rider 2023.1.2
Build #RD-231.9011.39, built on May 17, 2023
```

**Comment by mallowigi** [comment]
<img width="1088" alt="CleanShot 2023-06-07 at 10 33 57@2x" src="https://github.com/mallowigi/material-theme-issues/assets/5015756/fdcb9ece-7d3d-4512-855b-61583bf08861">

this is done by this screen

**Comment by heartzwh** [comment]
![Snipaste_2023-06-07_15-40-11](https://github.com/mallowigi/material-theme-issues/assets/28264550/d25ad724-010e-480b-9a9e-ef716f514ff2)
my settings

**Comment by mallowigi** [comment]
Ha ok I see your problem. You're using Accent Mode, I can see the value being on. But you're on free plan, so you can't turn it off...

Were you on the premium plan at some point?

**Comment by heartzwh** [comment]
> 
I am using a free version

**Comment by mallowigi** [comment]
I don't understand why the value would be turned on or why it would be working without a license. I'll investigate this issue.

In the meantime, try to edit the settings file manually and remove the accent mode property

https://material-theme.com/docs/configuration/settings/#advanced-configuration
