### ISSUE TITLE
[Bug]: Broken git dialog layout

### ISSUE THREAD

**Issue by Shay-repos** [mallowigi/material-theme-issues#356]
### Describe the bug

Plugin disabled:
<img width="269" alt="Screenshot 2023-06-15 at 12 08 56" src="https://github.com/mallowigi/material-theme-issues/assets/22854836/70458bb6-d4b0-4447-8f67-4516b20e8ff5">

Plugin enabled:
<img width="255" alt="Screenshot 2023-06-15 at 12 08 45" src="https://github.com/mallowigi/material-theme-issues/assets/22854836/032acf71-491e-4ace-8e68-cddcd54907c9">

### To Reproduce

Install plugin??

### Expected behavior

Same spaces as original

### Material Theme Version

newest

### IDE

WebStorm

**Comment by mallowigi** [comment]
Yes I know about this one, I've noticed it a long time ago but forgot to open an issue. Thanks for reminding me.

**Comment by Shay-repos** [comment]
will it be fixed in next release?

**Comment by mallowigi** [comment]
It's already available.

**Comment by Shay-repos** [comment]
seems like it hasn't been fixed yet
<img width="674" alt="Screenshot 2023-09-29 at 16 36 38" src="https://github.com/mallowigi/material-theme-issues/assets/22854836/b9dfb044-0693-4417-a0d5-ea868e03633b">

WebStorm 2023.2.2
Build #WS-232.9921.42, built on September 12, 2023
Licensed to Nguyen Tat Thanh
Subscription is active until January 9, 2024.
Runtime version: 17.0.8+7-b1000.22 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4048M
Cores: 8
Metal Rendering is ON
Registry:
    editor.focus.mode.color.light=828bb8
    ide.editor.tab.selection.animation=true
    debugger.new.tool.window.layout=true
    ide.animate.toolwindows=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=828bb8
    ide.images.show.chessboard=true
    js.debugger.webconsole=false
    eslint.additional.file.extensions=svelte

Non-Bundled Plugins:
    some.awesome (1.14)
    org.toml.lang (232.8660.88)
    com.github.copilot (1.3.0.3342-nightly)
    ru.adelf.idea.dotenv (2023.2)
    com.atlassian.bitbucket.references (2022.1.242)
    com.chrisrm.idea.MaterialThemeUI (8.12.0)
    dev.blachut.svelte.lang (232.8660.129)
    com.mallowigi (93.1.0)
    aws.toolkit (1.77-232)

**Comment by mallowigi** [comment]
What's not fixed about that?

**Comment by Shay-repos** [comment]
@mallowigi 
the search icon does not align with other icons.
the setting and fetch icon also seem to misaligned
![image](https://github.com/mallowigi/material-theme-issues/assets/22854836/42f1b93d-a614-4616-9389-c2c1213fc031)

![image](https://github.com/mallowigi/material-theme-issues/assets/22854836/68fa2513-8fa6-43f2-918c-6a449f6dc763)

**Comment by Shay-repos** [comment]
is that a features 🤣 ?

**Comment by mallowigi** [comment]
Why did you assume that it has to be aligned? My concern was with the absence of padding, and it's now fixed. It doesn't get in the way of usability, so I consider that issue irrelevant :)

**Comment by Shay-repos** [comment]
the way they're arranged made my eye twitch a bit. So I checked the UI with the plugin disabled, and they all aligned.
I agree that this issue is subtle, but I think you can make it look better with a little change.
Anyway, if you find it unimportant, I'm happy to leave it be.
