### ISSUE TITLE
[Bug]: VCS file statuses are missing from Custom File Colors settings panel

### ISSUE THREAD

**Issue by reubenShilling** [mallowigi/material-theme-issues#357]
### Describe the bug

VCS file status colors cannot be set per theme in the _Editor > Color Scheme > Custom File Colors_ options in the Rider IDE.
![image](https://github.com/mallowigi/material-theme-issues/assets/25227743/97311d2f-7d4b-49a6-99b9-93ae3615e7f4)

### To Reproduce

1. Open settings
2. Expand _Editor_
3. Expand _Color Scheme_
4. Select _Custom File Colors_

### Expected behavior

There should be a list of all the VCS file statuses in the options panel that can be customized per theme as seen in the screenshot below from the same setting as seen in the PyCharm IDE.
![image](https://github.com/mallowigi/material-theme-issues/assets/25227743/1fc65efb-7640-459e-bd9c-e6bdb2b2d2cd)

### Material Theme Version

v8.7.1

### IDE

Rider

### System Info

```shell
JetBrains Rider 2023.1.2
Build #RD-231.9011.39, built on May 17, 2023
Runtime version: 17.0.6+10-b829.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
.NET 7.0.2 (Server GC)
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 16
Registry:
    ide.intellij.laf.enable.animation=true
    editor.focus.mode.color.light=5c5c5c
    ide.editor.tab.selection.animation=true
    ide.mac.bigsur.window.with.tabs.enabled=false
    ide.new.editor.tabs.vertical.borders=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=5c5c5c
    database.show.search.tab=false
    rdclient.asyncActions=false
    vcs.empty.toolwindow.show=false
    ide.new.project.model.index.case.sensitivity=true

Non-Bundled Plugins:
    com.chrisrm.idea.MaterialThemeUI (8.7.1)
    com.intellij.settingsSync (231.8109.108)
    unreal-link (2023.1.0.282)
```

**Comment by mallowigi** [comment]
should be fixed
