### ISSUE TITLE
[Bug]: Android SDK upgrade assistant has wrong dark theme

### ISSUE THREAD

**Issue by marcelpinto** [mallowigi/material-theme-issues#358]
### Describe the bug

When opening the Android Studio SDK upgrade assistant the description text is not visible since it has the same color as the background.

![Screenshot 2023-06-16 at 11 17 18](https://github.com/mallowigi/material-theme-issues/assets/2639977/0c69d59d-c9aa-4d26-a280-f09e80013a90)

Selecting the text

![Screenshot 2023-06-16 at 11 25 24](https://github.com/mallowigi/material-theme-issues/assets/2639977/3d4ad436-aa6a-4bb0-b3d6-0af83628a8c0)

### To Reproduce

1. Set Material Oceanic theme
2. Open "Android SDK upgrade assistant" (you can find it with search-everywhere)

### Expected behavior

Text description is shown. Instead the text has the same theme color as the background.

### Material Theme Version

v8.5.0

### IDE

Android Studio

### System Info

```shell
Android Studio Hedgehog | 2023.1.1 Canary 3
Build #AI-231.7864.76.2311.10083640, built on May 7, 2023
Runtime version: 17.0.6+0-17.0.6b829.9-10027231 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.4
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
    editor.focus.mode.color.light=415967
    ide.editor.tab.selection.animation=true
    external.system.auto.import.disabled=true
    debugger.new.tool.window.layout=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    ide.new.editor.tabs.vertical.borders=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=415967

Non-Bundled Plugins:
    com.intellij.marketplace (231.7864.85)
    com.jetbrains.kmm (0.6.0(231)-5)
    com.chrisrm.idea.MaterialThemeUI (8.5.0)
```

**Comment by mallowigi** [comment]
Closing these old issues for now. If it reproduces on the latest versions, please reopen.
