### ISSUE TITLE
[Bug]: Can't start an IDE after updating Atom Material Icons

### ISSUE THREAD

**Issue by AntonMenov** [mallowigi/material-theme-issues#360]
### Describe the bug

_I believe Atom Material Icons is also associated with your project._

An IDE does not start normally after updating Atom Material Icons to 91.0.0.
It is stuck in loading the interface and the app is frozen (you have to kill it using task manager, also takes some time).

### To Reproduce

1. Update Atom Material Icons to 91.0.0 in the IDE / enable updated plugin
2. Start the IDE

### Expected behavior

The IDE should start normally.

### Material Theme Version

v8.7.1

### IDE

IntelliJ IDEA, PyCharm

### System Info

```shell
Windows 10 (22H2)

IntelliJ IDEA 2023.1.2 (Ultimate Edition)
Build #IU-231.9011.34, built on May 16, 2023
Runtime version: 17.0.6+10-b829.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

Not a single plugin enabled, but Atom Material Icons 91.0.0.
```

### Logs/Screenshots

```shell
https://i.postimg.cc/MKv7tCm3/1.png
https://i.postimg.cc/LsBLn2m5/2.png
```

**Comment by mallowigi** [comment]
Wrong repo
