### ISSUE TITLE
New UI Issues

### ISSUE THREAD

**Issue by mallowigi** [mallowigi/material-theme-issues#363]
- ~~Tabs~~
- ~~Project Icon doesn't show~~
- Integrate the "colored project headers"
- No configurable for displayName...
- Statusbar becomes gray after theme change
- ~~Accent color widget doesn't show~~
- Selected tree indicator is broken again

**Comment by matiux** [comment]
I think to have same problem.

PhpStorm 2023.2 EAP
Build #PS-232.8296.18, built on June 26, 2023

Material Theme UI: 8.7.0

Changing Tab Height doesn't affect the current height of the tabs.

![Screenshot_20230630_092039](https://github.com/mallowigi/material-theme-issues/assets/821668/0cb4e18f-fe3d-48f9-b772-6aa58268778b)

**Comment by jkcdarunday** [comment]
On a HiDPI screen, I get the following issues:
- Some tab bar and status bar fonts are too small
- File explorer fonts are small and bold
- Terminal tab bars have unusually large height
- Top run icons are too small while other icons are too large

All of these are displayed correctly with the Material Theme plugin disabled.

Versions:
IntelliJ IDEA 2023.2 (Ultimate Edition)
Build #IU-232.8660.185, built on July 26, 2023
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
com.chrisrm.idea.MaterialThemeUI (8.9.1)

![Screenshot_20230802_125504](https://github.com/mallowigi/material-theme-issues/assets/4564810/79c06991-db6f-44e7-a121-579cf8b1f6f6)

**Comment by Jaimss** [comment]
I have the same issue as above. It is OK on `2023.1.4`, but has the above issue starting at version `2023.2`

**Comment by Zeratoxx** [comment]
The option "Legacy Material Design Style" has round corners in menus.

![image](https://github.com/mallowigi/material-theme-issues/assets/35294329/5a379a70-7555-4e57-b983-d0ced27d8b26)

![image](https://github.com/mallowigi/material-theme-issues/assets/35294329/923389d7-1141-4d7e-9083-e0c40ab8e5c9)

**Comment by mallowigi** [comment]
Closing this as I don't want to leave this issue as a put-it-all place for reporting bugs. Please open issues separately. Thanks.
