### ISSUE TITLE
[Bug]: "Marked as incompatible" with RubyMine 2023.1.3

### ISSUE THREAD

**Issue by stex** [mallowigi/material-theme-issues#366]
### Describe the bug

After upgrading to the latest RubyMine release, the plugin is no longer loaded as it is "Marked as incompatible".

### To Reproduce

Install RubyMine 2023.1.3 and try to activate the plugin.

### Expected behavior

Compatibility with the latest stable RubyMine version

### Material Theme Version

8.7.1

### IDE

RubyMine

### System Info

```shell
RubyMine 2023.1.3
Build #RM-231.9161.40, built on June 20, 2023
Runtime version: 17.0.7+10-b829.16 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 3080M
Cores: 10
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    ruby.rails.projectView.enabled=true

Non-Bundled Plugins:
    com.intellij.plugins.watcher (231.8109.91)
    com.mallowigi (90.0.0)
    zielu.gittoolbox (500.0.13+213)
```

### Logs/Screenshots

![CleanShot 2023-07-07 at 10 53 50](https://github.com/mallowigi/material-theme-issues/assets/27221/d31dd91b-605b-446b-8973-062b8b58ac39)

**Comment by mallowigi** [comment]
can you remove the plugin and reinstall it again ?

**Comment by 021-projects** [comment]
Same issue with PhpStorm 2023.1.3

**Comment by 021-projects** [comment]
Fixed. You are the best, guys
