### ISSUE TITLE
[Bug]: Incorrect rendering of `Selected Item Indicator` in `Project View`

### ISSUE THREAD

**Issue by BppleMan** [mallowigi/material-theme-issues#367]
### Describe the bug

This was a bug that was fixed, and now it's reappearing, it's causing me a lot of trouble, I often can't locate the files I open.

The original issue: [[Bug]: Incorrect rendering of `Selected Item Indicator` in `Project View`](https://github.com/mallowigi/material-theme-issues/issues/257) #257 

### To Reproduce

The same to #257 

### Expected behavior

The same to #257 

### Material Theme Version

>= v8.5.0

### IDE

IntelliJ IDEA, Other (AppCode, CLion, GoLang...)

**Comment by mallowigi** [comment]
Closing this one. This issue always gets fixed and gets broken because the feature is unstable. JetBrains have completely blocked the ability to customize the inactive indicator, and resorting to hacks is not something I want to invest time on.

**Comment by mallowigi** [comment]
One precision, my old fix is still working some times. But there is an event that I don't know of that removes this function. So there's little to do here unfortunately. By all means I recommend working without the project tree open ;)
