### ISSUE TITLE
Compatibility with WebStorm 8.7.1

### ISSUE THREAD

**Issue by dschinkel** [mallowigi/material-theme-issues#368]
### Describe the feature

This is what I see after installing the latest version of WebStorm.

<img width="1080" alt="Screenshot 2023-07-10 at 2 34 59 PM" src="https://github.com/mallowigi/material-theme-issues/assets/338798/58edbeca-ad1c-49eb-a853-71662f38e3da">

### Material Theme Version

8.7.1

### IDE

WebStorm

My Mac is running Ventura 13.4.1 (22F82)

```shell
WebStorm 2023.1.3
Build #WS-231.9161.29, built on June 15, 2023
```

**Comment by mallowigi** [comment]
Try to reinstall the plugin

**Comment by dschinkel** [comment]
sorted itself out after an update button appeared.  It wasn' there before so maybe that was just pushed after this thread? 🤷
