### ISSUE TITLE
[Bug]: Scroll bar effect does not work in markdown edit mode and preview mode 

### ISSUE THREAD

**Issue by zhouxinghong** [mallowigi/material-theme-issues#369]
### Describe the bug

Scroll bar effect does not work in markdown edit mode and preview mode
![image](https://github.com/mallowigi/material-theme-issues/assets/54253524/4008426e-92c5-4f11-8adb-232ae906d0ba)
OS: Windows10
Interllij IDEA 2023.1.4
Version: 8.7.1

### To Reproduce

Scroll bar effect does not work in markdown edit mode and preview mode
![image](https://github.com/mallowigi/material-theme-issues/assets/54253524/4008426e-92c5-4f11-8adb-232ae906d0ba)
OS: Windows10
Interllij IDEA 2023.1.4
Version: 8.7.1

### Expected behavior

Scroll bar effect does not work in markdown edit mode and preview mode
![image](https://github.com/mallowigi/material-theme-issues/assets/54253524/4008426e-92c5-4f11-8adb-232ae906d0ba)
OS: Windows10
Interllij IDEA 2023.1.4
Version: 8.7.1

### Material Theme Version

Version: 8.7.1

### IDE

IntelliJ IDEA

### System Info

```shell
Scroll bar effect does not work in markdown edit mode and preview mode
![image](https://github.com/mallowigi/material-theme-issues/assets/54253524/4008426e-92c5-4f11-8adb-232ae906d0ba)
OS: Windows10
Interllij IDEA 2023.1.4
Version: 8.7.1
```

### Logs/Screenshots

```shell
Scroll bar effect does not work in markdown edit mode and preview mode
![image](https://github.com/mallowigi/material-theme-issues/assets/54253524/4008426e-92c5-4f11-8adb-232ae906d0ba)
```

**Comment by mallowigi** [comment]
This is an issue from JetBrains. I opened a PR in their repo, let's see if it got merged.

Closing this

**Comment by zhouxinghong** [comment]
Follow up:
The style and size of the scroll bar in `Markdown` editing mode, preview mode and code block are inconsistent. Among them, the code block and the scroll bar of the preview mode are very small and not rounded.
I've labeled them with numbers and arrows:
![image](https://github.com/mallowigi/material-theme-issues/assets/54253524/9954ce77-aa11-4f9d-8b69-91ddc5afd1de)


[Enhancement]: It would be perfect if the `Markdown` editing mode and preview mode, as well as the size of the scroll bar in the code block can be enlarged and maintained in a uniform style. Hope you can improve the above problems in the next version, thank you very much for your very beautiful and excellent theme extension!

IDEA 2023.2
The latest version of the theme
Windows10

**Comment by zhouxinghong** [comment]
[@mallowigi](https://github.com/mallowigi)  
Please see the latest issue tracking progress. . .  
[https://youtrack.jetbrains.com/issue/IDEA-338799/Third-party-theme-extensions-cannot-customize-the-size-background-color-foreground-color-border-color-and-style-of-the-Markdown](https://youtrack.jetbrains.com/issue/IDEA-338799/Third-party-theme-extensions-cannot-customize-the-size-background-color-foreground-color-border-color-and-style-of-the-Markdown)
