### ISSUE TITLE
Color Scheme Font always resets to 'JetBrains Mono' after restart

### ISSUE THREAD

**Issue by Kevin-Lee** [mallowigi/material-theme-issues#37]
**Describe the bug**
I changed `Color Scheme Font`, but it always resets to `JetBrains Mono` after restart.

**To Reproduce**
What steps will reproduce the issue?
1. Change the Color Scheme Font to any font other than JetBrains Mono and save.
2. Restart IntelliJ IDEA
3. Check the Color Scheme Font'. It's back to JetBrains Mon.

What is the expected result?
The font I selected persists.

What happens instead?
It resets to JetBrains Mono.

I originally reported it [here](https://youtrack.jetbrains.com/issue/IDEA-282523). JetBrains team suggested disabling Material Theme UI so I did and it was fine when I disabled Material Theme UI.

**Environment**
===

IntelliJ IDEA 2021.3 Beta (Ultimate Edition)

Build #IU-213.5744.18, built on November 11, 2021

IntelliJ IDEA EAP User

Expiration date: December 11, 2021

Runtime version: 11.0.13+7-b1751.19 x86_64

VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

macOS 11.6

GC: G1 Young Generation, G1 Old Generation

Memory: 2048M

Cores: 16

Registry:

    undo.documentUndoLimit=500

    ide.tooltip.initialDelay=507

    ide.balloon.shadow.size=0

    scala.erase.compiler.process.jdk.once=false

Non-Bundled Plugins:

    net.vektah.codeglance (1.5.4)

    indent-rainbow.indent-rainbow (1.6.2)

    com.paperetto.dash (3.3)

    org.jetbrains.plugins.hocon (2021.1.0)

    awesome.console (0.1337.11)

    org.asciidoctor.intellij.asciidoc (0.35.12)

    GrepConsole (12.0.211.6086.4)

    mobi.hsz.idea.gitignore (4.3.0)

    com.mallowigi (50.2.0)

    com.chrisrm.idea.MaterialThemeUI (6.10.0)

    izhangzhihao.rainbow.brackets (6.21)

    org.intellij.scala (2021.3.491)

    ASM Bytecode Viewer (9.2)

Kotlin: 213-1.5.10-release-949-IJ5744.18

===
It should contain:
* OS (Windows, Linux, Mac)
* IntelliJ Product + version (IDEA, RubyMine...)
* Plugin version
* If needed a list of enabled plugins -->

**Screenshots**

Before restart:
<img width="1195" alt="Screen Shot 2021-11-14 at 2 15 44 pm" src="https://user-images.githubusercontent.com/2307335/141770612-24bdb493-5695-4e7d-8419-cdb45231cf33.png">

After restart:
<img width="1192" alt="Screen Shot 2021-11-14 at 2 27 46 pm" src="https://user-images.githubusercontent.com/2307335/141770669-e92c8b9a-747f-460f-82ee-f8019de5bee1.png">

**Comment by mallowigi** [comment]
Please check whether you have the "use default font" setting (https://material-theme.com/docs/configuration/features-settings/)

**Comment by kiddick** [comment]
@mallowigi 
Same issue here. But seems `Use Editor Default Font` is not included in free version anymore so I can not test it
<img width="418" alt="image" src="https://user-images.githubusercontent.com/9250239/185926507-2e8f73a6-91e0-4e69-b4c1-9194063b3747.png">

I do not need any extra functionality, but auto resetting color scheme on every restart is really annoying

**Comment by mallowigi** [comment]
If the feature is off, it should do the normal behavior then, e.g not resetting it.

Are you sure it's the case?

**Comment by kiddick** [comment]
Yes
I have custom editor color scheme
![image](https://user-images.githubusercontent.com/9250239/185956880-22770ed7-5a08-4627-94c8-48f0b6f79957.png)
and after every restart it resets to Material Darker
![image](https://user-images.githubusercontent.com/9250239/185956920-f0af1dc8-8480-4570-a1fc-57bc64853490.png)

**Comment by kiddick** [comment]
I am also use custom version of 'Material Darker'
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/9250239/185957223-3ee7f7c9-4333-4b24-8501-04b545e4bee1.png">

**Comment by kiddick** [comment]
Also if I completely disable Material Theme UI plugin, pycharm does not reset theme. it is ok

**Comment by mallowigi** [comment]
It's not related to the issue. If you're using a custom theme, you have to set the color scheme you're using (in this case Pycharm Monokai) in the color scheme option of the custom theme settings. Here you specified Material Darker that's why it resets to Material Darker.

**Comment by kiddick** [comment]
@mallowigi thanks

**Comment by kiddick** [comment]
seems not it is only available in PRO mode ;(

**Comment by mallowigi** [comment]
How are you using custom theme if it's not pro?

**Comment by kiddick** [comment]
it was ok in august, now after updating Pycharm this window is forbidden with message saying it is only available in PRO verison

**Comment by tavria-forever** [comment]
I am switch off options ["Automatically reset color schemes"](https://material-theme.com/docs/configuration/other-tweaks-settings/#automatically-reset-color-schemes) and it fixed the same problem in webstorm 2022.2
