### ISSUE TITLE
[Bug]: Menus and context menus are compacted

### ISSUE THREAD

**Issue by jkazimierczak** [mallowigi/material-theme-issues#372]
### Describe the bug

Both menus (File, Edit, View etc.) and context menus (Right Mouse Click) are very compact, almost un-themed. 

This happened after upgrading to WebStorm 2023.2 (Build #WS-232.8660.143, built on July 21, 2023). Selected theme is Material Atom One Dark. All of "Compact settings" in Material Theme UI settings are unchecked (I never used compact mode).

Menus:
![image](https://github.com/mallowigi/material-theme-issues/assets/77862767/d015c33c-a55f-4ac1-8bf3-70ab47f2fbd7)

### To Reproduce

1. Apply any material theme (preferably: Material Atom One Dark)
2. Click on File menu.
3. See the compacted menu.

### Expected behavior

The menus are not compacted.

### Material Theme Version

8.9.0

### IDE

WebStorm

### System Info

```shell
PyCharm 2023.1 (Professional Edition)
Build #PY-231.8109.197, built on March 29, 2023

Runtime version: 17.0.6+10-b829.5 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 4

Registry:
    editor.focus.mode.color.light=6b727d
    ide.editor.tab.selection.animation=true
    ide.new.editor.tabs.vertical.borders=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=6b727d

Non-Bundled Plugins:
    hunspell (231.8109.91)
    net.seesharpsoft.intellij.plugins.file-preview (1.6.4)
    com.almightyalpaca.intellij.plugins.discord (1.11.0)
    com.chrisrm.idea.MaterialThemeUI (8.6.3)
    ru.adelf.idea.dotenv (2023.1)
    com.leinardi.pycharm.pylint (0.14.0)
    com.koxudaxi.pydantic (0.4.2-231)
    com.mallowigi (90.0.0)
    mobi.hsz.idea.gitignore (4.5.0)
```

### Logs/Screenshots

```shell
Illustration of current look of menus:
Context menus:
![image](https://github.com/mallowigi/material-theme-issues/assets/77862767/c72fecb8-b38b-44e6-bac5-c7a71737c1c7)
File browser menu:
![image](https://github.com/mallowigi/material-theme-issues/assets/77862767/995ce5e9-bd1a-4720-89b4-5d35f7499d4b)

Illustration of expected look of menus from PyCharm that uses Material Theme UI 8.7.1:
![image](https://github.com/mallowigi/material-theme-issues/assets/77862767/298a4bc7-a259-4098-a0c4-ce39f607ad81)
```

**Comment by mallowigi** [comment]
I haven't tried on Windows yet, but make sure you're not using the Compact Mode (from JetBrains, not the plugin)

**Comment by jkazimierczak** [comment]
I never enabled Compact Mode. I also see that it's exclusive to the New UI, which I'm not using. 

I also rolled back to WebStorm 2023.1.3 and reinstalled the theme just to make sure and the theme behaves as expected, but that's not a solution.

**Comment by jkazimierczak** [comment]
Themed menus are even more condensed than unthemed ones. Side-by-side comparison: left themed, right unthemed (JetBrains Darcula):
![menussidebyside](https://github.com/mallowigi/material-theme-issues/assets/77862767/6cf84cbe-906d-4905-9b31-7ed1ee224462)

**Comment by Szlavicsek** [comment]
I just came here to submit a ticket about this, haha... I have the same error on a fresh webstorm install (2023.2). All Material Theme settings are on default + Material Oceanic is selected for me (don't think that matters tho).

I can confirm, this happens if "**Enable new UI**" is turned **off** in Appearance & Behavior / New UI.

**Comment by iris-qq** [comment]
old:
![image](https://github.com/mallowigi/material-theme-issues/assets/32732041/7544358d-1fed-40f0-9cf4-6175340a52b8)
upgrade:
![image](https://github.com/mallowigi/material-theme-issues/assets/32732041/751a095b-8b2b-4fe1-b9b4-9ab70bb15c3d)


ui version: 8.10.0
pycharm:
PyCharm 2023.2 (Professional Edition)
Build #PY-232.8660.197, built on July 26, 2023
Licensed to wang qiqiang
Subscription is active until February 16, 2024.
Runtime version: 17.0.7+7-b1000.6 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.5
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Metal Rendering is ON
Registry:
    editor.focus.mode.color.light=415967
    ide.editor.tab.selection.animation=true
    ide.animate.toolwindows=true
    ide.new.editor.tabs.vertical.borders=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=415967

Non-Bundled Plugins:
    com.mzyupc.a-redis (beta-0.9.0)
    co.anbora.labs.brew-bundle (1.4.0)
    org.elasticsearch4idea (2023.2.6-232)
    com.intellij.ideolog (222.1.0.0)
    com.godwin.json.parser (1.7)
    ru.meanmail.plugin.requirements (2022.4.1)
    com.chrisrm.idea.MaterialThemeUI (8.10.0)
    ru.adelf.idea.dotenv (2023.2)
    com.koxudaxi.pydantic (0.4.7)
    net.seesharpsoft.intellij.plugins.csv (3.2.1-232)
    com.mallowigi (92.0.0)
    mobi.hsz.idea.gitignore (4.5.1)


macOS

**Comment by mallowigi** [comment]
Duplicate

**Comment by dwyart** [comment]
Also affected by this, not sure why it has been closed... Is there another open issue tracking this? I am not able to find any.

Currently, running the latest versions of JetBrains tools (not with the New UI, which I do not like) + all up-to-date plugins gives this ugly compacted menus, so it is not solved as far as I know. I am stuck at the previous major version for now.

Any idea of a way forward? Do we know if the issue is more on JetBrains or MaterialUI side?

Thanks!

**Comment by mallowigi** [comment]
https://github.com/mallowigi/material-theme-issues/issues/376
