### ISSUE TITLE
[Bug]: unreadable menu with 2023.2 and new UI with deep ocean theme

### ISSUE THREAD

**Issue by luispabon** [mallowigi/material-theme-issues#375]
### Describe the bug

The gradient on the menu when new UI is enabled on 2023.2 in combination with material + deep ocean's colour scheme can make it unreadable due to insufficient contrast.

**Deep ocean:**
![image](https://github.com/mallowigi/material-theme-issues/assets/6388823/a9056816-8eda-4773-905a-1d346c1c80c4)

**Without theme:**
![image](https://github.com/mallowigi/material-theme-issues/assets/6388823/fe24811b-a017-400e-be8d-e14bb3b096f9)

Also, it looks as if the gradient is of a different colour on every app restart (feature from the new ui). I can imagine all themes could potentially be impacted.

![image](https://github.com/mallowigi/material-theme-issues/assets/6388823/1515acd6-4b7b-499d-bac0-9c7e05ca42d0)

### To Reproduce

1. IntelliJ 2023.2
2. Enable new ui
3. Enable menu bar
4. Enable material theme
5. Choose the Deep Ocean theme

### Expected behavior

Menus remain readable.

### Material Theme Version

v.8.9.1

### IDE

PHPStorm, PyCharm

### System Info

```shell
PyCharm 2023.2 (Professional Edition)
Build #PY-232.8660.197, built on July 26, 2023
Licensed to Luis Pabon
You have a perpetual fallback license for this version.
Subscription is active until July 17, 2025.
Runtime version: 17.0.7+7-b1000.6 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.2.0-26-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 3974M
Cores: 8
Registry:
    editor.focus.mode.color.light=6272a4
    ide.editor.tab.selection.animation=true
    debugger.new.tool.window.layout=true
    ide.animate.toolwindows=true
    ide.new.editor.tabs.vertical.borders=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=6272a4

Non-Bundled Plugins:
    io.github.fstaudt.helm (0.7.1)
    net.sjrx.intellij.plugins.systemdunitfiles (223.230322.126)
    com.mnr.java.intellij.idea.plugin.base64helper (2.0.3)
    ru.sadv1r.ansible-vault-editor-idea-plugin (1.20)
    org.intellij.plugins.hcl (232.8660.88)
    de.netnexus.camelcaseplugin (3.0.12)
    lermitage.intellij.ilovedevtoys (1.9.0)
    org.jetbrains.plugins.go-template (232.8660.88)
    codes.rudolph.idea.cfg (0.3.1)
    com.intellij.ideolog (222.1.0.0)
    name.kropp.intellij.makefile (232.8660.88)
    ir.msdehghan.plugins.ansible (0.92)
    dev.meanmail.plugin.nginx-intellij-plugin (2022.1.1)
    YAML/Ansible support (0.11.2)
    indent-rainbow.indent-rainbow (2.1.0)
    com.intellij.kubernetes (232.8660.158)
    izhangzhihao.rainbow.brackets (2023.3.2)
    ru.meanmail.plugin.requirements (2022.4.1)
    com.chrisrm.idea.MaterialThemeUI (8.9.1)
    net.ashald.envfile (3.4.1)
    ru.adelf.idea.dotenv (2023.2)
    net.seesharpsoft.intellij.plugins.csv (3.2.1-232)
    com.mallowigi (91.0.0)
    mobi.hsz.idea.gitignore (4.5.1)

Current Desktop: sway
```
```


### Logs/Screenshots

_No response_

**Comment by mallowigi** [comment]
I don't think there is much we can do here. The gradient is controlled by the user, not the plugin, and it's his responsibility to select a gradient that goes well with the theme he selected. The color on the items of the toolbar are not only appearing inside the gradient, so it's not like we can paint such items differently only inside the gradient while leaving the rest untouched.

**Comment by luispabon** [comment]
Just to point out that at no point did I select a gradient on Pycharm's settings, I just upgraded from 2023.1.4 to 2023.2 and this behaviour of random colours seems to be the default one.

The gradient can be disabled tho, I've done so from now.
![image](https://github.com/mallowigi/material-theme-issues/assets/6388823/a7483ece-2987-4bf5-8782-95aae091e68b)

**Comment by mallowigi** [comment]
That doesn't contradict my comment.

**Comment by luispabon** [comment]
> The gradient is controlled by the user

While technically the user _can_ control the gradient, by default the gradient is enabled and random with the new UI. It's not an opt-in feature, but opt-out. So "controlled by the user" is only technically right, with big caveats

**Comment by mallowigi** [comment]
The point is - the user is responsible for selecting a gradient that blends with the theme, not the other way around.

**Comment by luispabon** [comment]
It's of course up to you, but initial UX is going to suffer for everyone. Most people don't veer from defaults, and nobody on first run.
