### ISSUE TITLE
[Bug]: Main menu item height offset too tiny

### ISSUE THREAD

**Issue by OfficialError** [mallowigi/material-theme-issues#376]
### Describe the bug

![grafik](https://github.com/mallowigi/material-theme-issues/assets/45919406/06cc0048-0ca1-4167-b521-35c9f0770471)
The offset between the items of this main menu dropdown is practically 0 and I haven't been able to find a setting to change it.

### To Reproduce

1. Click on File
2. Look at the items

### Expected behavior

The items should be offset from eachother

### Material Theme Version

v8.9.1

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2023.2 (Ultimate Edition)
Build #IU-232.8660.185, built on July 26, 2023
Runtime version: 17.0.7+7-b1000.6 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Non-Bundled Plugins:
    GLSL (1.24)
    org.rust.lang (0.4.199.5415-232)
    com.github.copilot (1.2.16.2847)
    ASM Bytecode Viewer (9.5)
    com.jetbrains.packagesearch.intellij-plugin (232.8660.142)
    Pythonid (232.8660.185)
    com.demonwav.minecraft-dev (2023.2-1.6.9)
    com.chrisrm.idea.MaterialThemeUI (8.9.1)
    org.intellij.scala (2023.2.17)
    org.jetbrains.plugins.docker.gateway (232.8660.202)

Kotlin: 232-1.9.0-IJ8660.185
```

**Comment by OfficialError** [comment]
![grafik](https://github.com/mallowigi/material-theme-issues/assets/45919406/064fb2af-c8b2-4487-aab5-baf4fa7e8298)
This also happens with the right click context menu.
The bug doesnt occur when I disable the Material UI Theme plugin

**Comment by ashleysommer** [comment]
I'm seeing the same thing. I think this is a bug with the "Compact Menus" option. Toggling "compact menus" on and off changes nothing, so I think this bug is forcing it always on.
I found a workaround. If you enable "Legacy Material Design Style", the menu item heights are correct, and toggling "compact menus" works as expected again. But I don't want to leave Legacy Design turned on.
