### ISSUE TITLE
Broken credit links

### ISSUE THREAD

**Issue by equinusocio** [mallowigi/material-theme-issues#383]
### Describe the bug

Hello, just writing this to ask if you can update the credit link inside the readme. The original material theme has been moved under material-theme org, and the new link is now: [https://github.com/material-theme/vsc-material-theme](https://github.com/material-theme/vsc-material-theme),

### To Reproduce

,

### Expected behavior

,

### Material Theme Version

,

### IDE

Other (AppCode, CLion, GoLang...)

**Comment by mallowigi** [comment]
Sure, but you can also make a PR directly here: https://github.com/mallowigi/material-theme-docs
