### ISSUE TITLE
[Bug]: Latest Update not changing the editor file color to selected theme in IDEA

### ISSUE THREAD

**Issue by SasquatchXYZ** [mallowigi/material-theme-issues#384]
### Describe the bug

Updated to the latest version 8.10.0 in Rider and IDEA, however when using IDEA the color theme selected (Deep Ocean) is not reflected in IDEA while it is in Rider. 
![image](https://github.com/mallowigi/material-theme-issues/assets/40616938/827fad24-b860-4f2a-ae5e-2c586b63fcd0)

### To Reproduce

Selecte Deep Ocean as color theme, High Contrast

### Expected behavior

I expected it to look the same as it was before and how Rider still currently looks: 
![image](https://github.com/mallowigi/material-theme-issues/assets/40616938/f2e21daf-5519-43cf-8a1c-b4125bd87046)

### Material Theme Version

8.10.0

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2023.2 (Ultimate Edition)
Build #IU-232.8660.185, built on July 26, 2023
Runtime version: 17.0.7+7-b1000.6 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
    editor.focus.mode.color.light=464b5d
    ide.editor.tab.selection.animation=true
    ide.new.editor.tabs.vertical.borders=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=464b5d

Non-Bundled Plugins:
    detekt (2.0.1)
    Key Promoter X (2023.2.0)
    com.intellij.kubernetes (232.8660.158)
    HighlightBracketPair (1.4.1)
    String Manipulation (9.10.0)
    CheckStyle-IDEA (5.82.0)
    com.intellij.lang.jsgraphql (4.0.2)
    org.sonarlint.idea (8.5.1.75093)
    izhangzhihao.rainbow.brackets (2023.3.3)
    com.netflix.graphql.dgs.intellijplugin (1.3.2)
    com.chrisrm.idea.MaterialThemeUI (8.10.0)
    com.mallowigi (92.0.0)
    mobi.hsz.idea.gitignore (4.5.1)
    org.jetbrains.plugins.docker.gateway (232.8660.202)

Kotlin: 232-1.9.0-IJ8660.185
```

**Comment by kei-ichi** [comment]
Same issue here, but it happen on both WebStorm and PyCharm Pro and Clion.

#### How to To Reproduce: 
> Select Deep Ocean as color theme, High Contrast


#### Material Theme Version: 
> 8.10.0

#### IDE
> WebStorm: v2023.2
> PyCharm Pro: v2023.2
> Clion: v2023.2

#### OS Infos

```
Software:

    System Software Overview:

      System Version: macOS 13.5 (22G74)
      Kernel Version: Darwin 22.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Tim Cook
      User Name: Tim Apple
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 15 days, 5 hours, 21 minutes

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro18,3
      Model Number: Z12345678WJ/A
      Chip: Apple M1 Pro
      Total Number of Cores: 10 (8 performance and 2 efficiency)
      Memory: 32 GB
      System Firmware Version: 8422.141.2
      OS Loader Version: 8422.141.2
      Serial Number (system): T1MAPPL3KJP
      Hardware UUID: E6F23A81-3672-50FD-AE06-3E60EG556E72
      Provisioning UDID: 00009000-0002625922A3801E
      Activation Lock Status: Disabled
```

#### Screenshot
![](https://i.imgur.com/Xb3DEty.png)

**Comment by mallowigi** [comment]
Duplicate

**Comment by SasquatchXYZ** [comment]
which one is this a duplicate of, I didn't see another one listed in the issues?

**Comment by mallowigi** [comment]
https://github.com/mallowigi/material-theme-issues/issues/377

**Comment by SasquatchXYZ** [comment]
thank you, yes the fix you listed [here](https://github.com/mallowigi/material-theme-issues/issues/377#issuecomment-1685074444) seems to have fixed the problem for me.  I did have two copies of Deep Ocean listed: one that displayed the correct theme and one that did not.
