### ISSUE TITLE
[Bug]: The editor scroll bar, code block scroll bar, and Markdown scroll bar have inconsistent styles

### ISSUE THREAD

**Issue by zhouxinghong** [mallowigi/material-theme-issues#385]
### Describe the bug

For details, please see:
https://github.com/mallowigi/material-theme-issues/issues/369

### To Reproduce

For details, please see:
https://github.com/mallowigi/material-theme-issues/issues/369

### Expected behavior

For details, please see:
https://github.com/mallowigi/material-theme-issues/issues/369

### Material Theme Version

8.10

### IDE

IntelliJ IDEA, Rider

### System Info

```shell
IDEA | Rider 2023.2
Aug 06, 2023
Version 8.10.0
Windows10
```

### Logs/Screenshots

```shell
For details, please see:
https://github.com/mallowigi/material-theme-issues/issues/369
```

**Comment by mallowigi** [comment]
not fixing

**Comment by zhouxinghong** [comment]
> not fixing

Hello! I know this question is not a bug, but to make the user experience better! It should be necessary to keep the style of all scroll bars consistent. You can see that the scroll bars in the current Edge browser almost all use the rounded corner effect, and you can look at the scroll bar effects of Windows 11 and so on. You should be able to consider this improvement suggestion. 😜👍 This theme you provided is awesome! Following these suggested improvements will improve the overall look and feel of your theme.

**Comment by mallowigi** [comment]
Yes but it's outside of the scope of the plugin. It's controlled by JetBrains and their JCEF rendering.

**Comment by zhouxinghong** [comment]
oh! I see! 😂 I always thought it was implemented by extension.
If so, I suggest that you can give the JetBrains team a suggestion for improving the scroll bar. In addition, can the size and width of all scroll bars remain the same?

**Comment by mallowigi** [comment]
They already have a thousand issues related to it on their Youtrack. I invite you to take a look.

I submitted them a PR about the inconsistency in colors, it got merged but I don't know if it was released yet. Anyway, it's out of the plugin's scope.

**Comment by zhouxinghong** [comment]
OK! I've looked, but the JetBrains team hasn't been able to fix the scrollbar related issue. . .

But I still hope that your theme user experience will get better and better! 👍👏😜

**Comment by zhouxinghong** [comment]
@mallowigi 
Please see the latest issue tracking progress. . .
https://youtrack.jetbrains.com/issue/IDEA-338799/Third-party-theme-extensions-cannot-customize-the-size-background-color-foreground-color-border-color-and-style-of-the-Markdown
