### ISSUE TITLE
[Bug]: Incompatibilities with IntelliJ IDEA 2023.2.1

### ISSUE THREAD

**Issue by mgroth0** [mallowigi/material-theme-issues#389]
### Describe the bug

On IntelliJ EAP, I get the following error on startup:

```
Plugin 'Material Theme UI Custom Theme' (version '2022.1.0') is not compatible with the current version of the IDE, because it requires build 231.* or older but the current build is IU-232.9559.62 Plugin 'Material Theme UI Extras' (version '2022.1.1') is not compatible with the current version of the IDE, because it requires build 231.* or older but the current build is IU-232.9559.62 Plugin 'Material Theme UI High Contrast' (version '2022.1.1') is not compatible with the current version of the IDE, because it requires build 231.* or older but the current build is IU-232.9559.62 Plugin 'Material Theme UI Language Additions' (version '2022.1.1') is not compatible with the current version of the IDE, because it requires build 231.* or older but the current build is IU-232.9559.62 Plugin 'Material Theme UI Project Frame' (version '2022.1.1') is not compatible with the current version of the IDE, because it requires build 231.* or older but the current build is IU-232.9559.62
```

### To Reproduce

1. Install this IntelliJ EAP version
2. Enable all Material Theme plugins

### Expected behavior

I expect Material Theme to stay up to date with the latest EAP. The main plugin "Material Theme UI", which is free, as well as "Atom Material Icons" support the latest EAP. However, all of the paid plugins do not. 

Scrolling through my list of IntelliJ plugins, I notice that the rest of them (which are all free except for the Material Theme plugins) support my current IntelliJ version.

### Material Theme Version

8.11.0

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2023.2.1 (Ultimate Edition)
Build #IU-232.9559.62, built on August 23, 2023
```

**Comment by mallowigi** [comment]
should be fixed, please update

**Comment by mallowigi** [comment]
[Material_Theme_UI_Project_Frame-2024.1.1.zip](https://github.com/mallowigi/material-theme-issues/files/12482523/Material_Theme_UI_Project_Frame-2024.1.1.zip)

I don't know why it seeped through the cracks... Here's the updated version until JetBrains approves the public rerelease.
