### ISSUE TITLE
[Bug]: Bad Atom One light theme since last update

### ISSUE THREAD

**Issue by hfezvcksks** [mallowigi/material-theme-issues#393]
### Describe the bug

The theme is not the same as before (see pictures):
Before the update:
<img width="1725" alt="Capture d’écran 2023-09-03 à 14 56 39" src="https://github.com/mallowigi/material-theme-issues/assets/69317809/c88a2b58-dce9-4c72-a679-595e66b4a6fe">

After the update:
<img width="1725" alt="Capture d’écran 2023-09-03 à 14 56 28" src="https://github.com/mallowigi/material-theme-issues/assets/69317809/ca9ef9f4-d695-49e2-a878-67e44e6bd766">

### To Reproduce

1. Select the "Atom One light" theme

### Expected behavior

Same theme as before

### Material Theme Version

v8.11.0

### IDE

PHPStorm

### System Info

```shell
Mac Pro M1
```

**Comment by mallowigi** [comment]
Are you using settings sync ?

**Comment by mallowigi** [comment]
If yes, then please follow the workaround here https://github.com/mallowigi/material-theme-issues/issues/377

Closing until further response.

**Comment by hfezvcksks** [comment]
Hi @mallowigi ,
Yes I am using the Settings Sync and it works now with the fix you gave me. Thanks a lot :)
