### ISSUE TITLE
[Bug]: Vertical Heigth Discrepancy on Bottom Toolbar

### ISSUE THREAD

**Issue by gssj85** [mallowigi/material-theme-issues#394]
### Describe the bug

Image for better understanding:

![Screenshot from 2023-09-03 13-24-53](https://github.com/mallowigi/material-theme-issues/assets/66959217/e5c7b4e4-6b17-4d68-8341-6e0a0051164b)

### To Reproduce

Just open anything on the bottom toolbar.

### Expected behavior

Normal sized tabs.

### Material Theme Version

v8.11.0

### IDE

PHPStorm

### System Info

```shell
PhpStorm 2023.2.1
Build #PS-232.9559.64, built on August 25, 2023
Runtime version: 17.0.8+7-b1000.8 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.2.0-31-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 4
Registry:
    editor.focus.mode.color.light=464b5d
    ide.editor.tab.selection.animation=true
    run.processes.with.pty=TRUE
    ide.new.editor.tabs.vertical.borders=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=464b5d

Non-Bundled Plugins:
    com.chrisrm.idea.MaterialThemeUI (8.11.0)
    com.mallowigi (93.0.1)

Current Desktop: ubuntu:GNOME
```

**Comment by mallowigi** [comment]
It uses the same value as the tabs height. If you changed it there, it will change it here too.

**Comment by ddc** [comment]
I think this still an issue.
Same value will be applied on both of them, but the vertical one still bigger than the file tabs.
This screenshot shows the minimum value, which is 24.

![image](https://github.com/mallowigi/material-theme-issues/assets/34492089/e51ada85-0627-4b7a-875f-e5dae3db5718)

**Comment by gssj85** [comment]
> I think this still an issue. Same value will be applied on both of them, but the vertical one still bigger than the file tabs. This screenshot shows the minimum value, which is 24.
> 
> ![image](https://user-images.githubusercontent.com/34492089/270027492-e51ada85-0627-4b7a-875f-e5dae3db5718.png)

Yep...

**Comment by mallowigi** [comment]
That's weird...

![CleanShot 2023-09-23 at 11 33 16@2x](https://github.com/mallowigi/material-theme-issues/assets/5015756/c680d869-7bdf-4e6c-9131-5ff870344171)

**Comment by gssj85** [comment]
I don't know if it may help track the issue but I use custom font:

`Appearance & Behavior > Appearance > [X] Use custom font: [Ubuntu] Size: [18]`

Also I use compact mode, because when I use custom font 18 the side icons get bigger too (and I don't want that):

`Appearance & Behavior > New UI > [X] Enable new UI > [X] Compact mode`

Hoppefuly this helps diagnose the issue.

Just to note I can't decrease it lower than `24`, the tooltip says `18 to 60` but the arrows only allow as low as `24`:

![Screenshot from 2023-12-29 14-51-14](https://github.com/mallowigi/material-theme-issues/assets/66959217/762e0575-da14-4bd6-822a-efab3221390c)
