### ISSUE TITLE
[Bug]: something wrong with top code editor border

### ISSUE THREAD

**Issue by mehdiidehqan** [mallowigi/material-theme-issues#396]
### Describe the bug

in some themes, a border shown up that introduce top of the code editor and starting of codes.
however, in some (for example mt atom one dark) it isn't shown that is confusing.

### To Reproduce

make an android compose class

### Expected behavior

tell me how to fix it 

### Material Theme Version

17.0.6

### IDE

Android Studio

**Comment by mehdiidehqan** [comment]
![Screenshot 2023-09-12 021655](https://github.com/mallowigi/material-theme-issues/assets/84234418/6bdfca0e-ecbd-460e-95ad-1bb228d90dca)
![Screenshot 2023-09-12 022249](https://github.com/mallowigi/material-theme-issues/assets/84234418/2f7a5afa-a902-4171-b250-6b9de2cb8908)

**Comment by mallowigi** [comment]
you can disable that in the settings (Tabs Shadow)
