### ISSUE TITLE
[Bug]: no inline regex highlight in pycharm

### ISSUE THREAD

**Issue by trim21** [mallowigi/material-theme-issues#397]
### Describe the bug

regexp file have highlight, but inline code fragment `re.compile('...')` doesn't have highlight, 

![image](https://github.com/mallowigi/material-theme-ui-lite/assets/13553903/4d04d431-34e9-4691-ac9b-75aab19a7be1)

![image](https://github.com/mallowigi/material-theme-ui-lite/assets/13553903/4ccc73d5-20c2-4164-9c43-4d01ea02ddfe)

And I'm sure this string is consider as PythonRexExp, not plain text, because it has hightlight when I switch to monokai 

![image](https://github.com/mallowigi/material-theme-ui-lite/assets/13553903/5369814d-1a3d-4c94-84fc-317a9fac9da8)

(monokai has highlight)
![image](https://github.com/mallowigi/material-theme-ui-lite/assets/13553903/f8786737-7e64-4d61-87d6-cb4b0676b4f3)

in seprated editing view, it get highlight in the first place, then it become gray again

![image](https://github.com/mallowigi/material-theme-ui-lite/assets/13553903/3f7be8cb-3c34-406d-8122-e32312f235bf)

### To Reproduce

1. install pycharm
2. install plugin
3. change `Editor/Color Scheme` to `Material Darker`
4. create a new python project
5. create a new python file (`.py`)
6. paste this as file content:

```python
import re

pattern = re.compile(r"((?P<d>\d+)日)?((?P<h>\d+)時)?((?P<m>\d+)分)?")
```

### Expected behavior

python inline regexp in pycharm should have highlight

### Material Theme Version

8.11.0

### IDE

PyCharm

### System Info

```shell
* OS: Windows
* IntelliJ Product: PyCharm 2023.2.1 (Professional Edition)
```

**Comment by mallowigi** [comment]
I don't know how this could be related to the plugin. Have you checked without the plugin?

**Comment by trim21** [comment]
> I don't know how this could be related to the plugin. Have you checked without the plugin?

it's related to the color scheme `Material Darker`

**Comment by mallowigi** [comment]
Interesing. It identifies that regex as an hyperlink for some reason. In any case, I've remvoved the gray color for hyperlinks, as it is the case for other schemes. Should be fine now.

**Comment by trim21** [comment]
> Interesing. It identifies that regex as an hyperlink for some reason. In any case, I've remvoved the gray color for hyperlinks, as it is the case for other schemes. Should be fine now.

Yes, you are right. Removing the color of hyperlink fix this. This looks like a pycharm bug?
