### ISSUE TITLE
[Bug]: Atom One Light Theme Changes Color On Stepping Through Call Stack

### ISSUE THREAD

**Issue by mcmah309** [mallowigi/material-theme-issues#398]
### Describe the bug

Whenever I attempt to step up the call stack in the "Atom One Light" Theme, it makes the text unreadable.
![image](https://github.com/mallowigi/material-theme-issues/assets/56412856/6978b465-e6ff-432f-9fc4-6d3fac57b2fc)
![image](https://github.com/mallowigi/material-theme-issues/assets/56412856/6101f0ca-cbcf-4d77-ac50-b4fc4db077c3)
![image](https://github.com/mallowigi/material-theme-issues/assets/56412856/1e55fe10-0c9b-4107-9ca0-503992652df6)
I've observed this in Dart and Rust. The above example is Dart.

### To Reproduce

1. Set break point
2. Hit break point
3. Step up the call stack

### Expected behavior

No color change

### Material Theme Version

v8.6..4

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2023.1.4 (Ultimate Edition)
Build #IU-231.9225.16, built on July 12, 2023
Runtime version: 17.0.7+10-b829.16 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 16384M
Cores: 8
Registry:
    editor.focus.mode.color.light=b8b8b9
    ide.editor.tab.selection.animation=true
    ide.new.editor.tabs.vertical.borders=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=b8b8b9

Non-Bundled Plugins:
    org.mvnsearch.plugins.justPlugin (0.3.6)
    com.github.fawaz.flutter-freezed-snippets (1.0.6)
    org.tbm98.flutter-riverpod-snippets (2.232.1)
    com.github.copilot (1.2.21.2995)
    com.intellij.nativeDebug (231.8770.15)
    org.jetbrains.settingsRepository (231.8109.91)
    org.rust.lang (0.4.200.5421-231)
    Dart (231.9161.14)
    Pythonid (231.9225.16)
    club.nutsoft.Github3Theme (1.2.0)
    io.flutter (74.0.4)
    com.chrisrm.idea.MaterialThemeUI (8.6.4)

Kotlin: 231-1.8.21-IJ9225.16
```

**Comment by mallowigi** [comment]
will be fixed on next version
