### ISSUE TITLE
Jest test files display with bright green background in project pane

### ISSUE THREAD

**Issue by philipbulley** [mallowigi/material-theme-issues#399]
**Describe the bug**

Jest tests appear with a bright green background in the Project pane. I'm not sure if this is trying to indicate a status and is something I can configure? It's barely readable at present. 

**To Reproduce**

1. Create a JavaScript project (in my example, I'm using `npx react-native@latest init MyProject`
1. Use a Material theme, most seem to be affected. I'm using Palenight.
1. Open the JS project and expand the `__tests__` folder in the project pane. Notice how the Jest test file name is almost impossible to read due to the background colour.

**Expected Behavior**

The filename of Jest test when viewed in the Project pane should be readable.

**Environment**

```
IntelliJ IDEA 2023.2 (Ultimate Edition)
Build #IU-232.8660.185, built on July 26, 2023
Runtime version: 17.0.7+7-b1000.6 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.2.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Metal Rendering is ON
Registry:
    ide.intellij.laf.enable.animation=true
    editor.focus.mode.color.light=415967
    ide.editor.tab.selection.animation=true
    ide.new.editor.tabs.vertical.borders=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=415967

Non-Bundled Plugins:
    com.fwdekker.randomness (2.7.7)
    com.mallowigi.idea (22.0.0)
    cucumber-javascript (232.8660.142)
    com.intellij.lang.jsgraphql (4.0.2)
    ru.adelf.idea.dotenv (2023.2)

Kotlin: 232-1.9.0-IJ8660.185
```

**Screenshots**

<img width="282" alt="image" src="https://github.com/mallowigi/material-theme-ui-lite/assets/309607/1c6e3dc7-6d63-4e67-8419-7bc7374a6b2c">

**Comment by mallowigi** [comment]
will be fixed next release
