### ISSUE TITLE
[Bug]: phpstorm tab font size changes, jumps up after just after opening

### ISSUE THREAD

**Issue by Abdelraman** [mallowigi/material-theme-issues#403]
### Describe the bug

by opening phpstorm tab font size changes automatically as well as the tab size, and some times it didn't change, but by clicking on the tab itself it changes
please check the attached video   

https://github.com/mallowigi/material-theme-issues/assets/4821833/652f2ccd-eef5-48be-8b1f-b9e9cd3af4c7

### To Reproduce

1- open phpstorm
2- make sure that you are using inter as font family for the interface, and change the font size as well
3- choose any project
4- if tabs already opened, you will release a jump in the font size

### Expected behavior

tab font size as well as size should be consistent

### Material Theme Version

8.12.0

### IDE

PHPStorm

**Comment by mallowigi** [comment]
Please provide your settings files (not just the material ones)

**Comment by Abdelraman** [comment]
here is my settings.zip file extracted from the IDE
[settings.zip](https://github.com/mallowigi/material-theme-issues/files/12720571/settings.zip)

**Comment by mallowigi** [comment]
Is this issue stil happening in 2024.1 ?

**Comment by Abdelraman** [comment]
still 2024.1 not available for phpstorm, but it is not very noticeable in the latest versions e.g. 2023.3,
Thanks Elior

**Comment by mallowigi** [comment]
@Abdelraman still happening ?

**Comment by Abdelraman** [comment]
the font starts smaller, then automatically get larger (to the normal font I already set) after all files gets loaded
