### ISSUE TITLE
[Bug]: Very aggressive colored file names

### ISSUE THREAD

**Issue by BlockyTheDev** [mallowigi/material-theme-issues#405]
### Describe the bug

I don't know what is happening here but this looks very strange because the colors are so strange, because only the Gradle folders look like this, which is a bit distracting:
<img width="290" alt="image" src="https://github.com/mallowigi/material-theme-issues/assets/86119630/d03ca785-87e8-4ef7-a923-c47ee182477b">

### To Reproduce

1. Install Material Theme UI
2. Select the theme "Material Darker"
3. Open a Gradle project

### Expected behavior

The files/folders aren't colored or don't have such a distracting color background.

### Material Theme Version

8.12.2

### IDE

IntelliJ IDEA, PyCharm

### System Info

```shell
IntelliJ IDEA 2023.2.2 (Community Edition)
Build #IC-232.9921.47, built on September 12, 2023
Runtime version: 17.0.8+7-b1000.22 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 3054M
Cores: 12
Registry:
    ide.intellij.laf.enable.animation=true
    editor.focus.mode.color.light=474747
    ide.editor.tab.selection.animation=true
    debugger.new.tool.window.layout=true
    ide.animate.toolwindows=true
    ide.new.editor.tabs.vertical.borders=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=474747

Non-Bundled Plugins:
    com.chrisrm.idea.MaterialThemeUI (8.12.2)
    com.mallowigi (93.1.0)

Kotlin: 232-1.9.0-IJ9921.47
```

**Comment by mallowigi** [comment]
You can change the colors in the File Colors Settings

**Comment by BlockyTheDev** [comment]
> You can change the colors in the File Colors Settings

Ohh sorry, I thaught it is from Material Theme, because I never seen it before. Maybe it got enabled through the last IDE update i did.
