### ISSUE TITLE
[Feature]: Option to Explicitly Opt-In to Ads Tracking on "What's New" Page

### ISSUE THREAD

**Issue by muya** [mallowigi/material-theme-issues#409]
### Describe the feature

Hello. I had a slight blip with my internet connection after a plugin upgrade, and saw this error when the "What's New" page loaded:

![screenshot-20230929-042805](https://github.com/mallowigi/material-theme-issues/assets/1861055/6286ddbe-4f69-4917-96c4-584aabf22dfa)

It seems that there was a failed attempt to call the Google Ads network.

Could we please have an option to explicitly opt in to such tracking?

### Use Cases

- Cases where a user would like their usage data not to be shared with 3rd parties without consent

### Material Theme Version

v8.12.2

### IDE

Other (AppCode, CLion, GoLang...)

### System Info

```shell
GoLand 2023.2.2
Build #GO-232.9921.53, built on September 14, 2023
(Removed licensing info)
Runtime version: 17.0.8+7-b1000.22 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.5
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
    editor.focus.mode.color.light=2e5861
    ide.editor.tab.selection.animation=true
    suggest.all.run.configurations.from.context=true
    debugger.new.tool.window.layout=true
    ide.animate.toolwindows=true
    ide.completion.variant.limit=500
    ide.new.editor.tabs.vertical.borders=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=2e5861

Non-Bundled Plugins:
    com.intellij.datagen (232.8660.88)
    String Manipulation (9.11.3)
    org.intellij.plugins.hcl (232.8660.88)
    org.toml.lang (232.8660.88)
    IdeaVIM (2.5.1)
    com.github.copilot (1.2.22.3129)
    Dart (232.9559.10)
    com.mallowigi (93.1.0)
    uk.co.ben-gibson.remote.repository.mapper (4.3.6)
    mobi.hsz.idea.gitignore (4.5.1)
    ru.adelf.idea.dotenv (2023.2)
    com.chrisrm.idea.MaterialThemeUI (8.12.2)
```

**Comment by mallowigi** [comment]
The what's new page is not related to telemetry, it just loads the page into the ide. The page itself uses telemetry but it's not related to the ide or the user's information.

Moreover you can turn it off in the settings.
