### ISSUE TITLE
[Bug]: Android Studio does not show license activation

### ISSUE THREAD

**Issue by hyyu** [mallowigi/material-theme-issues#411]
### Describe the bug

Hi,

I just had a new pc (macbook pro M1 2021), installed Android Studio (Giraffe 2022.3.1 Patch 2), JetBrains Marketplace Licensing Support plugin, and then Material Theme UI plugin in that order.

The problem is that when I click on the "Activate License" button, either from the Quick Actions Panel or the settings, Android Studio just restarts and does not show me the License window.

### To Reproduce

1. Install Android Studio Giraffe 2022.3.1 Patch 2 (current version on the official page at the moment)
2. Install JetBrains Marketplace Licensing Support plugin
3. Install Material Theme UI plugin
4. Try to activate a license from the Quick Actions Panel
5. Try to activate a license from the Material Theme UI settings

### Expected behavior

Expectations:
4. Android Studio opens a window to let me activate my license
5. Android Studio opens a window to let me activate my license

What happens:
4. Android Studio asks me to restart the IDE and nothing else happens
5. Android Studio asks me to restart the IDE and nothing else happens

### Material Theme Version

v8.4.1

### IDE

Android Studio

### System Info

```shell
Android Studio Giraffe | 2022.3.1 Patch 2
Build #AI-223.8836.35.2231.10811636, built on September 14, 2023
Runtime version: 17.0.6+0-17.0.6b829.9-10027231 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.0.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
    editor.focus.mode.color.light=6a737d
    ide.editor.tab.selection.animation=true
    external.system.auto.import.disabled=true
    debugger.new.tool.window.layout=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    ide.new.editor.tabs.vertical.borders=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=6a737d

Non-Bundled Plugins:
    com.intellij.marketplace (223.8836.56)
    com.chrisrm.idea.MaterialThemeUI (8.4.1)
```

**Comment by mallowigi** [comment]
https://material-theme.com/docs/faq-troubleshooting/#license-activation

**Comment by hyyu** [comment]
Well those are the rules I followed, but the modal does not show. It only restarts Android Studio.

**Comment by mallowigi** [comment]
try in menubar > Help > Register

**Comment by hyyu** [comment]
This one worked, thanks. Do you have any idea why even the tip from the doc does nothing? Does it come from Studio changes?

**Comment by mallowigi** [comment]
This info might be outdated, it was relevant last year but things might have changed since then. Thanks for the cooperation
