### ISSUE TITLE
[Bug]: Custom color for directories with changed descendants is not working

### ISSUE THREAD

**Issue by simonschaufi** [mallowigi/material-theme-issues#412]
### Describe the bug

Having set a custom color for directories with changed descendants is not working

### To Reproduce

1. Go to Appearance & Behavior -> Material Theme UI -> Settings -> Tab Project View
2. Activate Custom directories Style
3. Click "Click here to configure Directories Colors"
4. Change "Have changed descendants" and "Have immediate changed children" Foreground color
5. Click OK
6. Change any file
7. File color is changed but NOT the parent directories

### Expected behavior

All the parent directories get a different color

### Material Theme Version

8.12.2

### IDE

PHPStorm

**Comment by mallowigi** [comment]
These are IDEA's status file colors. If they don't work with the plugin off, they won't work with the plugin on either.

**Comment by simonschaufi** [comment]
Why do you close this issue? When I disable the plugin, it works without problems. When I enable the plugin again, it doesn't work again so it must be an issue with this plugin.

**Comment by mallowigi** [comment]
Can you provide your settings ? And share some screenshots?

**Comment by simonschaufi** [comment]
[settings-2023-10-07.zip](https://github.com/mallowigi/material-theme-issues/files/12838420/settings-2023-10-07.zip)

with custom directory colors disabled:

![image](https://github.com/mallowigi/material-theme-issues/assets/941794/7dcf2559-306e-4dd5-b386-aaa0d3785117)

with custom directory colors activated:

![image](https://github.com/mallowigi/material-theme-issues/assets/941794/c5888b19-ea8f-4ade-bc71-8acbab0ce9e6)

![image](https://github.com/mallowigi/material-theme-issues/assets/941794/652cff53-54c5-45c1-8f64-0eb8b69b45f6)

same color as "Have immediate changed children"

**Comment by mallowigi** [comment]
Hi, I tried to reproduce but without avail. That being said according to your screenshots, you're mentioning that the issue happens when "custom directory style" is enabled, isn't that right?

In that case, it makes sense, because that color is controlled by the "Directories" key of that same screen.

**Comment by simonschaufi** [comment]
> Hi, I tried to reproduce but without avail.

What does that mean? Do you see the directory in a different color when you change something?

> when "custom directory style" is enabled, isn't that right?

yes that is right.

> In that case, it makes sense, because that color is controlled by the "Directories" key of that same screen.

I don't understand this at all.

**Comment by mallowigi** [comment]
https://material-theme.com/docs/configuration/file-status-colors/#directories

**Comment by simonschaufi** [comment]
Dear @mallowigi, instead of just closing this issue, could you take my issue serious please? Whenever I switch on the "Custom Directory Style", they have no effect. It is not working for me! Is it working for you?

**Comment by mallowigi** [comment]
I sent you a link explaining what I meant with my previous message. Please read what's in that link.
