### ISSUE TITLE
[Bug]: Bookmark label size

### ISSUE THREAD

**Issue by asamofal** [mallowigi/material-theme-issues#414]
### Describe the bug

Hi! There's a problem with the bookmark label size: not enough space for numbers.
Theme: `Atom One Dark (Material)`

<img width="657" alt="image" src="https://github.com/mallowigi/material-theme-issues/assets/2729547/b62048cf-ba6e-4a41-98b3-849d6b4a633f">

### To Reproduce

Add a bookmark in the code (right-click next to the line number -> Add bookmark or shortcut).

### Expected behavior

The number fits the border.

### Material Theme Version

v8.12.5

### IDE

PHPStorm

### System Info

```shell
PhpStorm 2023.2.2
Build #PS-232.9921.55, built on September 15, 2023
Licensed to Anton Samofal
Subscription is active until June 8, 2024.
Runtime version: 17.0.8+7-b1000.22 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.0
GC: G1 Young Generation, G1 Old Generation
Memory: 6144M
Cores: 10
Metal Rendering is ON
Registry:
    editor.focus.mode.color.light=6b727d
    ide.editor.tab.selection.animation=true
    debugger.watches.in.variables=false
    debugger.new.tool.window.layout=true
    run.processes.with.pty=TRUE
    ide.new.editor.tabs.vertical.borders=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=6b727d

Non-Bundled Plugins:
    com.faebeee.vuecomponentcreator (2.7.3)
    de.netnexus.camelcaseplugin (3.0.12)
    org.intellij.plugins.hcl (232.8660.88)
    one.util.ideaplugin.screenshoter (1.8.1)
    com.intellij.ideolog (222.1.0.0)
    dev.meanmail.plugin.nginx-intellij-plugin (2022.1.1)
    com.kalessil.phpStorm.phpInspectionsEA (5.0.0.0)
    ru.adelf.idea.dotenv (2023.2)
    de.beyondco.tinkerwell.tinkerwell (2.6.1)
    com.intellij.ml.llm (232.9826)
    com.chrisrm.idea.MaterialThemeUI (8.12.5)
    com.github.jk1.ytplugin (2023.1.48)
    com.laravel_idea.plugin (7.4.2.232)
    com.mallowigi (93.1.0)
    mobi.hsz.idea.gitignore (4.5.2)
```

**Comment by mallowigi** [comment]
I am not able to reproduce on mac: 
![CleanShot 2023-10-13 at 20 26 34@2x](https://github.com/mallowigi/material-theme-issues/assets/5015756/1bb3c612-75c6-4cbd-8a7c-2d05f1973228)

**Comment by mallowigi** [comment]
I'm not aware of that. Can you share your IDE settings?

**Comment by asamofal** [comment]
Yes, I can, but in what specific settings are you interested?

**Comment by mallowigi** [comment]
I don't know, so i guess all your settings files

**Comment by asamofal** [comment]
@mallowigi I found what causes this issue. This is not related to Material Theme... but does Material Theme have control over bookmark labels, can you do something with it? Or should I go to JetBrains with it?

<img width="1299" alt="image" src="https://github.com/mallowigi/material-theme-issues/assets/2729547/7e164ef1-2fa6-41df-a76e-acdd6560cbb2">

**Comment by mallowigi** [comment]
No, it's not something we control. We might be able to control the color but that's it.

**Comment by asamofal** [comment]
Ok, I got it, thanks for your time.
