### ISSUE TITLE
[Feature]: Support customizing the full gradient in the menu toolbar in custom themes (new UI)

### ISSUE THREAD

**Issue by RheingoldRiver** [mallowigi/material-theme-issues#417]
### Describe the feature

I want to be able to customize the blue color here, in the new UI:

![2023-10-12_18-28-25](https://github.com/mallowigi/material-theme-issues/assets/18037011/4be8fcfb-c4cd-4d75-bd72-ae2aa7536454)

### Material Theme Version

v8.12.5

### IDE

PyCharm

### System Info

```shell
* Windows 10
* PyCharm professional edition, Build #PY-232.9559.58, built on August 22, 2023
```

**Comment by mallowigi** [comment]
What do you mean? You can already customize it by right clicking it.

**Comment by RheingoldRiver** [comment]
Sorry, where do you right-click? I thought it would be in this window but I don't see anything:

![image](https://github.com/mallowigi/material-theme-issues/assets/18037011/89eeb960-3f67-463b-8a78-6c2612921873)

**Comment by mallowigi** [comment]
https://www.jetbrains.com/help/idea/customize-actions-menus-and-toolbars.html#customize-main-toolbar
