### ISSUE TITLE
Last EAP breaks the IDE

### ISSUE THREAD

**Issue by mallowigi** [mallowigi/material-theme-issues#418]
### Describe the bug

The latest EAP changed a vital component used in the Material Theme UI plugin (and Atom Material Icons too).

As a result, the IDE crashes at start.

This has been fixed and is awaiting publish, but nonetheless to download the fix you will need to remove the plugin from the IDE.

To do so: open Finder -> Library -> Application Support -> JetBrains -> your ide -> delete the Material Theme UI/Atom Material Icons

For Windows and Linux you should check the equivalent directories.

Then you'll be able to open the ide once again. 

### To Reproduce

.

### Expected behavior

.

### Material Theme Version

v8.12.4

### IDE

IntelliJ IDEA, RubyMine, WebStorm, PHPStorm, Rider, PyCharm

**Comment by kevin-lee** [comment]
Oh, cool so that can solve [this issue](https://youtrack.jetbrains.com/issue/IDEA-334887/The-latest-IntelliJ-IDEA-EAP-2023.3-EAP-on-2023-10-14-UTC-crashes-when-start-up) I guess. Thanks!
Can I get the version number that has the fix?

**Comment by kevin-lee** [comment]
I've just upgraded to the latest Material Theme UI, and it's fine now.
