### ISSUE TITLE
[Bug]: Console window not zooming

### ISSUE THREAD

**Issue by Adriansun** [mallowigi/material-theme-issues#419]
### Describe the bug

Since a couple of versions ago I noticed that the console window would not update anymore when ctrl + scroll mouse in IntelliJ. Disabled Material Theme UI and restarted IntelliJ and sure enough the zoom in the console / output terminal started to work again.

### To Reproduce

Make a project like a server. Press the play button in IntelliJ. Let the console window print something. Have zoom enabled in IntelliJ and ctrl + mouse scroll when hovering over the console / terminal output window. Nothing will happen.

### Expected behavior

That when I ctrl + mouse scroll that the console window font size would change.

### Material Theme Version

8.12.2

### IDE

IntelliJ IDEA

### System Info

```shell
Windows 10
IntellliJ Ultimate
Material Theme UI
Java 21

All with the latest updates.
```

### Logs/Screenshots

```shell
No logs at all. Scrolling in the console window just does not work.
```

**Comment by Adriansun** [comment]
Same with v8.12.6.

**Comment by mallowigi** [comment]
https://github.com/mallowigi/material-theme-issues/assets/5015756/4060d736-9650-45e4-912e-61a1d3b1742e

Haven't tried on windows but it seems to be working in Mac, at least.

**Comment by Adriansun** [comment]
@mallowigi I see the video and I am happy for you. It does not work on my home desktop Windows computer and not on my work Windows computer. When disabling Material Theme UI on both of my computers it does start to work. Re-enabling the plug-in -> it does not work. Could it be that I have checked or unchecked some sort of setting that disables zooming?

**Comment by mallowigi** [comment]
Then it could be a windows issue. Unfortunately I don't have a windows computer available at the moment. I'll check whenever I can.

**Comment by mallowigi** [comment]
Check in Settings > Editor > General > Mouse Control

**Comment by Adriansun** [comment]
![mousecontrol](https://github.com/mallowigi/material-theme-issues/assets/9981908/8385b70a-721f-42e8-a74e-36c4da985e42)

Looks good on my side. Simple UI. Nothing special there.

**Comment by mallowigi** [comment]
I just checked on windows and it worked fine... I don't know what else I can do.

Maybe send the logs, something might get in the way. Also send me the plugins you use.

**Comment by Adriansun** [comment]
Alright I did a check of all plugins. This is what I did and found:
All turned on except Material Theme UI: Scrolling works in the console window.
All turned off except Material Theme UI: Scrolling does not work in the console window.

Also I do not very often send Log files of plugins and such. Could you direct me to the location of this log file that you are talking about, pleasE?

**Comment by mallowigi** [comment]
What version of the IDE are you using. I'll try whenever I get my hands on a windows machine again.

For the Logs, you should see that in the Menu > Help > Show Log

**Comment by Adriansun** [comment]
I always stay up-to-date. Got a small IntelliJ update today, a few hours ago. It is IntelliJ IDEA 2023.2.4 (Ultimate Edition). Build #IU-232.10203.10, built on October 24, 2023.

Is this what you are looking for?
[idea.log](https://github.com/mallowigi/material-theme-issues/files/13169532/idea.log)

**Comment by mallowigi** [comment]
Yes thanks. I'll check if there is something there

**Comment by Adriansun** [comment]
Found anything?

**Comment by mallowigi** [comment]
No, still unable to reproduce.
