### ISSUE TITLE
[Bug]: Losing DB connection colors

### ISSUE THREAD

**Issue by asamofal** [mallowigi/material-theme-issues#421]
### Describe the bug

I lose my colors for DB connections with every Material Theme plugin update. This happened to me 3-4 times already, this is really annoying to setting the colors after every update.

This is how it looks after every update:
![image](https://github.com/mallowigi/material-theme-issues/assets/2729547/93217fd4-fc7d-4e60-8b1b-06fedf5e0629)

This is before the update:
![image](https://github.com/mallowigi/material-theme-issues/assets/2729547/8a926289-f45b-4716-a87f-14d5b548eeb4)

![image](https://github.com/mallowigi/material-theme-issues/assets/2729547/4f808916-f890-4c84-97a9-61d1e5fc43df)

### To Reproduce

Update the plugin.

### Expected behavior

Update don't override the colors.

### Material Theme Version

v8.12.6

### IDE

PHPStorm

**Comment by mallowigi** [comment]
It was during some of the latest updates. Basically, we removed the file colors that were existing for a long time to propose much more color options and more saturated colors. But having too much colors was breaking the menu, so we decided to remove most of them and leave only a bunch. There's a chance the color you used was part of that purge.

Try to use another one in the available colors. We don't plan on changing the colors again in the early future.
