### ISSUE TITLE
[Bug]: Large table headers in New UI

### ISSUE THREAD

**Issue by nadia-tarashkevich** [mallowigi/material-theme-issues#422]
### Describe the bug

Not enough space for table "Module" rows (all space occupied by the table header)

### To Reproduce

1. Go to Settings -> Build, Execution, Deployment -> Compiler -> Per-module bytecode

### Expected behavior

Normal size table header for "Module"

### Material Theme Version

7

### IDE

IntelliJ IDEA

### System Info

```shell
2023.2.3
```

### Logs/Screenshots

```shell
![image](https://github.com/mallowigi/material-theme-issues/assets/96170885/38535616-2dba-4a06-9a78-9a3512892cd9)

```

**Comment by mallowigi** [comment]
Have you tried enabling "Compact Table Headers" in the settings?

**Comment by Adriansun** [comment]
@mallowigi Hi it is me again. I was asking IntelliJ about this issue too and they made a ticket for me. I have looked around for Compact Table Headers but cannot find it. 8.12.6 is the plug-in version.

**Comment by Adriansun** [comment]
Found it and it helped a little bit, but still not enough when having 20 modules to run through. Also in the IntelliJ ticket there was a mention of a "Missing resize control".

https://youtrack.jetbrains.com/issue/IDEA-336146

**Comment by mallowigi** [comment]
![CleanShot 2023-10-26 at 20 08 46@2x](https://github.com/mallowigi/material-theme-issues/assets/5015756/f1a098f8-9aa3-410d-ad64-0b1122e32ff6)

The plugin doesn't change individual sizes, they probably fixed the size, that's why you see only three/four modules at once.

**Comment by Adriansun** [comment]
Actually I see maybe 1 + 1/3 modules at the same time. The photo you just posted would be fine enough for me.

**Comment by Adriansun** [comment]
Any update on this one too?

**Comment by mallowigi** [comment]
I thought I was clear that this wasn't related to the plugin
