### ISSUE TITLE
[Bug]: Retained disposed instances of com.mallowigi.idea.focusmode.MTFocusedElementHighlightingCaretListener hold 77mb 

### ISSUE THREAD

**Issue by ViugiNick** [mallowigi/material-theme-issues#430]
### Describe the bug

149 instances com.mallowigi.idea.focusmode.MTFocusedElementHighlightingCaretListener$2 are holding references to 149 disposed MTFocusedElementHighlightingCaretListener, which holds 149 editors(77mb)
```
58.9MB/1 objects          project: com.intellij.openapi.project.impl.ProjectImpl
49.9MB/1 objects          +-serviceInstanceHotCache: java.util.concurrent.ConcurrentHashMap
49.9MB/1 objects          | table: [Ljava.util.concurrent.ConcurrentHashMap$Node;
36.7MB/4 objects          | []: java.util.concurrent.ConcurrentHashMap$Node
2.07MB/1 objects          | +-val: io.flutter.view.FlutterView
 855KB/1 objects          | | busConnection: com.intellij.util.messages.impl.MessageBusConnectionImpl
 855KB/1 objects          | | bus: com.intellij.util.messages.impl.RootBus
  216B/1 objects          | | subscribers: java.util.concurrent.ConcurrentLinkedQueue
  192B/1 objects          | | head: java.util.concurrent.ConcurrentLinkedQueue$Node
81.0MB/1 objects   (rep)  | | next: java.util.concurrent.ConcurrentLinkedQueue$Node
78.1MB/151 objects        | | item: com.intellij.util.messages.impl.MessageBusConnectionImpl
78.1MB/151 objects        | | subscriptions: java.util.concurrent.atomic.AtomicReference
78.1MB/151 objects        | | value: [Ljava.lang.Object;
77.7MB/149 objects        | | +-[]: com.mallowigi.idea.focusmode.MTFocusedElementHighlightingCaretListener$2
77.7MB/149 objects        | | | this$0: com.mallowigi.idea.focusmode.MTFocusedElementHighlightingCaretListener(disposed)
77.6MB/149 objects        | | | editor: com.intellij.openapi.editor.impl.EditorImpl
```

According to the reporting the problem remained for ~13 hours and the number of retained disposed instances was increasing: 
* Sat, 18 Nov 2023 13:31:11 GMT //149 instances
* ...
* Sat, 18 Nov 2023 00:34:37 GMT //101 instances

### To Reproduce

Unfortunately we don't have exact steps to reproduce the issue, the bug is based on memory usage reports

### Expected behavior

No memory leaks

### Material Theme Version

no data

### IDE

Android Studio

### System Info

```shell
Iguana | 2023.2.1 Canary 14
Windows 11
```

**Comment by mallowigi** [comment]
I've decided to remove this feature in the next versions of the plugin. Thanks for your support.

**Comment by ViugiNick** [comment]
@mallowigi Thanks!
Also found cases where MTTabsPainterPatcherComponent$initComponent$2$3 is holding disposed projects:

```
98.9MB/15 objects          []: com.mallowigi.idea.tabs.MTTabsPainterPatcherComponent$initComponent$2$3
98.9MB/15 objects          $project: com.intellij.openapi.project.impl.ProjectImpl(disposed)
```

Could you please take a look

**Comment by ViugiNick** [comment]
@mallowigi One more path:

```
    24.3MB/1 objects            \-[]: com.mallowigi.idea.projectframe.MTTitleFrame$$Lambda$3456/0x0000000801eb52e8
    24.3MB/1 objects              arg$1: com.mallowigi.idea.projectframe.MTTitleFrame
    24.1MB/1 objects              project: com.intellij.openapi.project.impl.ProjectImpl(disposed)
```

**Comment by mallowigi** [comment]
Just so I understand, what is the right course of action to fix these issues?

--
Elior

**Comment by ViugiNick** [comment]
It these cases it's worth checking what is the parrent disposable for the connections and why they remain in the `subscriptions` queue even when the corresponding project is disposed. I'm not entirely sure, but these handlers may be attached to something with a longer lifecycle then a project, but it this case it shouldn't store a reference to it.
