### ISSUE TITLE
[Bug]: buttons accelerators not underlined when hitting ALT

### ISSUE THREAD

**Issue by dotpanic** [mallowigi/material-theme-issues#431]
### Describe the bug

Hello,

When hitting ALT on any popup or window, the buttons accelerators are not underlined anymore with latest IntelliJ version. 
On IntelliJ 2022.3, the buttons were correctly underlined (see the "I" on commit button):

![image](https://github.com/mallowigi/material-theme-issues/assets/10357940/18e3a7f6-0aea-4b6f-b437-0261410d7afc)

But with Intellij 2023.3, this is what I see:

![image](https://github.com/mallowigi/material-theme-issues/assets/10357940/ff802405-7b81-464c-adf1-8ceaf3e0fad9)

I hope this issue has not already been reported :)

Thank you,
Mike

### To Reproduce

1. open a project under CVS
2. change any file
3. hit CTRL-K to open the commit popup
4. hit ALT

### Expected behavior

"Commit" button accelerator (i) must be underlined

### Material Theme Version

8.13.2

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2023.3 (Ultimate Edition)
Build #IU-233.11799.241, built on December 2, 2023
Runtime version: 17.0.9+7-b1087.7 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
```

**Comment by mallowigi** [comment]
Have you checked if it reproduces with the plugin off ?

**Comment by dotpanic** [comment]
With the plugin off, the IDE works as expected:
<img width="204" alt="image" src="https://github.com/mallowigi/material-theme-issues/assets/10357940/3ad30336-0ea2-4ebf-99d5-83daa2bcc06d">
