### ISSUE TITLE
[Bug]: Plugin is blocking the start of Pycharm 2023.3.x

### ISSUE THREAD

**Issue by zerubeus** [mallowigi/material-theme-issues#439]
### Describe the bug

Plugin is blocking the start of Pycharm 2023.3.x

### To Reproduce

you can't start the IDE anymore!

### Expected behavior

I should be able to start my IDE

### Material Theme Version

8.12.6

### IDE

PyCharm

**Comment by mallowigi** [comment]
<https://github.com/mallowigi/material-theme-issues/issues/426>

check if that fixes it

**Comment by zerubeus** [comment]
Link doesn't exit

**Comment by mallowigi** [comment]
my bad, please check now

**Comment by zerubeus** [comment]
I can't find this file material_theme.xml, I'm on macos

**Comment by mallowigi** [comment]
It should be on ~/Library/Application Support/JetBrains/<ide>/options

**Comment by zerubeus** [comment]
<img width="339" alt="Screenshot 2023-12-20 at 15 17 18" src="https://github.com/mallowigi/material-theme-issues/assets/6376307/3767c293-8b33-4616-9cc5-cd50e17aab1e">

I see no options folder

**Comment by zerubeus** [comment]
Ahh I can see it now, inside Pycharm...

**Comment by zerubeus** [comment]
working now, thanks
