### ISSUE TITLE
Language Additions highlights keywords in comment headers

### ISSUE THREAD

**Issue by nazrhyn** [mallowigi/material-theme-issues#44]
**Describe the bug**
When Other Tweaks / Language Additions is on, keywords are highlighted in comment headers, but not other comments. I feel like I remember reporting this years ago, and then it stopped happening. At this point, I'm not sure what the resolution to that old issue was.

**To Reproduce**
Type a keyword in a `/**`  `*/` comment header while Language Additions is turned on. After changing the setting, I had to switch color schemes to get the keywords to appear or disappear.

**Expected Behavior**
I would expect that comment headers would not have keywords highlighted.

**Environment**
```
WebStorm 2021.3
Build #WS-213.5744.224, built on November 27, 2021
Runtime version: 11.0.13+7-b1751.19 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.10.16.3-microsoft-standard-wsl2
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    qualia.reval.plugin (1.1)
    net.vektah.codeglance (1.5.4)
    com.intellij.lang.graql (1.4.1)
    com.intellij.lang.jsgraphql (3.0.0)
    com.intellij.database (213.5744.224)
    com.chrisrm.idea.MaterialThemeUI (6.10.1)
    com.mallowigi (50.2.0)
```

**Screenshots**
**Language Additions On**
_Material Darker Color Scheme_   
![image](https://user-images.githubusercontent.com/1672405/143934780-1ecacb71-0b80-47c4-b9d2-1860eec9f405.png)   
_Another Color Scheme_   
![image](https://user-images.githubusercontent.com/1672405/143934843-53e5e1df-e965-49d1-8802-7d4aaa757a49.png)   
**Language Additions Off**
_Material Darker Color Scheme_   
![image](https://user-images.githubusercontent.com/1672405/143934936-b8b597bf-525d-4125-a2b6-713bff26f93a.png)   
_Another Color Scheme_   
![image](https://user-images.githubusercontent.com/1672405/143934976-0668c1cc-3e24-4f6e-ade7-2333749e76d8.png)

**Comment by harwood-qualia** [comment]
❤️ Happy Holidays! 🎉

**Comment by nazrhyn** [comment]
Confirmed fixed! 🎉

Happy holidays! 🎄
