### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by gssj85** [mallowigi/material-theme-issues#442]
### Describe the bug

Hey can you look at: https://github.com/mallowigi/material-theme-issues/issues/394

I added more details.

### To Reproduce

https://github.com/mallowigi/material-theme-issues/issues/394

### Expected behavior

https://github.com/mallowigi/material-theme-issues/issues/394

### Material Theme Version

https://github.com/mallowigi/material-theme-issues/issues/394

### IDE

PHPStorm

### System Info

```shell
https://github.com/mallowigi/material-theme-issues/issues/394
```

### Logs/Screenshots

```shell
https://github.com/mallowigi/material-theme-issues/issues/394
```

**Comment by mallowigi** [comment]
As I said in the thread, it uses the same value as the tabs height, since they are tabs. Next time please follow the rules when opening an issue.

**Comment by gssj85** [comment]
I think you missed this:

![Screenshot from 2023-12-29 15-25-05](https://github.com/mallowigi/material-theme-issues/assets/66959217/472c18a3-5554-45a0-9228-6e0692fc9556)
