### ISSUE TITLE
[Bug]: Support for Edge's tweaked DevTools interface

### ISSUE THREAD

**Issue by gitpro2005** [mallowigi/material-theme-issues#447]
### Describe the feature

.

### I'm using it for edge, but after the new design, some elements are not being themed, like the tab bar for example. This could be fixed by inspecting the DevTools page (you can access on "devtools://devtools/bundled/devtools_app.html"), finding the classes for the elements that are not themed, and adding them to the style.

.

![image](https://github.com/mallowigi/material-theme-issues/assets/80659357/2c7f2bdf-ef7a-4d9a-9df3-553430b342dc)
.
- ## Inspecting DevTools
.
![image](https://github.com/mallowigi/material-theme-issues/assets/80659357/e3190e82-c8b3-4d42-976a-8aeaf8fb7a69)

### Use Cases

It is actually a fix / improvement for Microsoft Edge DevTools

### Material Theme Version

7.5.0 (Chrome Extension)

### IDE

Other (AppCode, CLion, GoLang...)

**Comment by gitpro2005** [comment]
I should have labeled this issue as [bug], not [feature], but I can't change that...

**Comment by mallowigi** [comment]
wrong repository
