### ISSUE TITLE
[Bug]: Xamarin Language Manager Bug

### ISSUE THREAD

**Issue by Zarpyk** [mallowigi/material-theme-issues#452]
### Describe the bug

https://youtrack.jetbrains.com/issue/RIDER-98767/Bugged-text-selection-on-Localization-Manager

![99feb39228757f81c53b1d8d27ae52d6](https://github.com/mallowigi/material-theme-issues/assets/30746531/cdcc3cca-abe0-4571-84ff-4437a7b15be8)
![2884df75c572ddd8ae68efade3b72b5f](https://github.com/mallowigi/material-theme-issues/assets/30746531/eba33a11-b7de-48ea-ae0f-2f7a0416bcd2)

### To Reproduce

0. Create Xamarin Project and create .resx file
2. Open file with Language Manager
3. Add languages
4. Write text 

### Expected behavior

Show text normally

### Material Theme Version

v8.13.2

### IDE

Rider

### System Info

```shell
JetBrains Rider 2023.3.3
Build #RD-233.14015.60, built on January 18, 2024
Licensed to ****
Subscription is active until September 6, 2024.
For educational use only.
Runtime version: 17.0.9+7-b1087.11 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
.NET Core v7.0.10 x64 (Server GC)
GC: G1 Young Generation, G1 Old Generation
Memory: 4070M
Cores: 12
Registry:
  ide.balloon.shadow.size=0
  editor.focus.mode.color.light=5b595c
  editor.focus.mode.color.dark=5b595c
  editor.config.csharp.support=true
  ide.new.editor.tabs.vertical.borders=true
  ide.animate.toolwindows=true
  ide.experimental.ui=true
  ide.editor.tab.selection.animation=true
Non-Bundled Plugins:
  xamlstyler.rider (3.2312.0.0)
  leetcode-editor (8.9)
  com.tang (1.4.11-IDEA231)
  monokai-pro (1.10)
  me.x150.intellij-code-screenshots (1.4.4)
  com.github.copilot (1.4.8.4188)
  com.jetbrains.rider.android (233.13135.100)
  com.github.camork.fileExpander (2.3)
  com.chrisrm.idea.MaterialThemeUI (8.13.2)
  com.clutcher.comments_highlighter (2024.1.2)
  com.mallowigi (94.1.0)
  mobi.hsz.idea.gitignore (4.5.2)
```

**Comment by Zarpyk** [comment]
This still happens with v9.3.1 and Rider 2024.1.4

```
JetBrains Rider 2024.1.4
Build #RD-241.18034.76, built on June 23, 2024
Licensed to ****
Subscription is active until September 6, 2024.
For educational use only.
Runtime version: 17.0.11+1-b1207.24 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
.NET Core v8.0.1 x64 (Server GC)
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
  ide.balloon.shadow.size=0
  ide.new.editor.tabs.vertical.borders=true
  ide.animate.toolwindows=true
  ide.experimental.ui=true
  ide.editor.tab.selection.animation=true
  ide.new.project.model.index.case.sensitivity=true
Non-Bundled Plugins:
  xamlstyler.rider (3.2404.4.0)
  com.intellij.javafx (1.0.4)
  avalonia-rider (1.3.2)
  com.jetbrains.rider.android (241.18034.76)
  com.chrisrm.idea.MaterialThemeUI (9.3.1)
  com.github.copilot (1.5.12.5909)
  com.mallowigi (97.0.0)
```

**Comment by mallowigi** [comment]
Do you have a project I can reproduce on? I'm not particularly familiar with Resx

**Comment by Zarpyk** [comment]
A simple console project with resx file:
[Localization Manager Bug.zip](https://github.com/user-attachments/files/16215344/Localization.Manager.Bug.zip)

1. Open Rider
2. (Create a simple c# (net 8.0) console project or open the zip project)
3. (Create resx file with right click and name it Language)
4. Double click the file to open the Localization Manager and modify son key

![imagen](https://github.com/user-attachments/assets/13234963-1bc6-468e-99e0-d1b8a0bf0501)
