### ISSUE TITLE
[Bug]: Intellij slow with theme enabled

### ISSUE THREAD

**Issue by sylvaindd** [mallowigi/material-theme-issues#453]
### Describe the bug

When I have a theme from Material Theme enabled my Intellij is super slow, scrolling is not smooth, there is even a delay on typing sometimes.
If i disable the plugin, no issue anymore, everything is smooth again.
Note that changing the theme back to Intellij default without disabling the plugin doesn't fix it.

When I check the activity monitor and I spam scroll on settings, with plugin enabled I see around 20% CPU Usage from "ide.plugins.cl", I don't see this when the plugin is disabled

### To Reproduce

Scrolling on code or in settings is slow for example

### Expected behavior

Should be smooth

### Material Theme Version

8.13.2

### IDE

IntelliJ IDEA

### System Info

```shell
Windows 11
IntelliJ IDEA 2023.3.3 (Ultimate Edition)
Runtime version: 17.0.9+7-b1087.11 amd64

VMOptions :
-Xmx16384m 
-Dsun.java2d.opengl=true

I added the sun.java2d.opengl=true to test after seeing another issue, didn't make any change.
```

**Comment by mallowigi** [comment]
Not going to lie, I don't think I will be investigating performance issues. I already have a lot on my plate already, and performance issues are not easy to pinpoint. As someone using my own plugin all the time, I made amends with performance issues. If you want a smoother experience, I encourage you to try out the Material Theme UI Lite.

If you purchased the plugin and would like to be refunded, please send me an email and I'll ask JetBrains for a refund.

**Comment by sylvaindd** [comment]
Just tried with Material Theme UI Lite, it's note as smooth as without, but way better that  Material Theme UI.
I will use this one, thanks

**Comment by mallowigi** [comment]
Well Material Theme UI Lite is just the color coating, without extra features. Therefore it should be as smooth as without the plugin. If it's not, then I surmise it should be the same with other themes as well. Can you check if that's the case?
