### ISSUE TITLE
[Bug]: centered editor setting not working for big resolutions

### ISSUE THREAD

**Issue by EranNL** [mallowigi/material-theme-issues#456]
### Describe the bug

There is a huge padding in the left bar where the line numbers are
![afbeelding](https://github.com/mallowigi/material-theme-issues/assets/10157169/03111f1c-16be-4bf3-b957-479e2901457d)

### To Reproduce

1. Open IDE
2. Start using a material theme from this plugin

### Expected behavior

I expected that there wouldn't be such a padding

### Material Theme Version

v9.0.0

### IDE

PHPStorm

### System Info

```shell
PhpStorm 2024.1 EAP
Build #PS-241.13688.22, built on February 22, 2024
Licensed to PhpStorm EAP user: ****
Expiration date: March 23, 2024
Runtime version: 17.0.10+8-b1207.1 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
  undo.globalUndoLimit=100
  undo.documentUndoLimit=1000
  ide.balloon.shadow.size=0
  editor.distraction.free.mode=true
  debugger.new.tool.window.layout=true
  run.processes.with.pty=TRUE
  ide.new.editor.tabs.vertical.borders=true
  ide.animate.toolwindows=true
  ide.experimental.ui=true
  ide.editor.tab.selection.animation=true
  terminal.new.ui=false
  eslint.additional.file.extensions=svelte
Non-Bundled Plugins:
  org.intellij.plugins.hcl (241.13688.16)
  com.nasller.CodeGlancePro (1.8.1-SNAPSHOT-2024-02-18T16-09)
  com.jetbrains.space (241.13688.16)
  com.markskelton.one-dark-theme (5.10.0)
  bundled-phpstorm-help (241.13688.22)
  dev.meanmail.plugin.nginx-intellij-plugin (2022.1.1)
  com.github.camork.fileExpander (2.4)
  org.mvnsearch.plugins.justPlugin (0.4.2)
  com.intellij.mermaid (0.0.19+IJ.232)
  net.seesharpsoft.intellij.plugins.csv (3.3.0-241)
  org.jetbrains.plugins.astro (241.13688.16)
  com.github.copilot (1.4.17.4734)
  com.intellij.lang.jsgraphql (241.13688.16)
  izhangzhihao.rainbow.brackets (2024.2.1)
  de.shyim.ideaphpstantoolbox (0.0.7)
  com.kalessil.phpStorm.phpInspectionsEA (5.0.0.0)
  com.chrisrm.idea.MaterialThemeUI (9.0.0)
  ru.adelf.idea.dotenv (2024.1)
  NEON support (0.5.4)
  de.espend.idea.php.annotation (9.4.0)
  fr.adrienbrault.idea.symfony2plugin (2022.1.263)
  dev.blachut.svelte.lang (241.13688.16)
  mdx.js (241.13688.16)
  com.laravel_idea.plugin (8.1.2.241)
  com.mallowigi (95.0.0)
  mobi.hsz.idea.gitignore (4.5.2)
```

**Comment by mallowigi** [comment]
Try to turn off the setting: `Features -> Centered Editor`

Also, can you provide more details of your setup? Are you on Full Screen? Distraction Free Mode?

**Comment by EranNL** [comment]
The centered editor "fixed" it indeed. :) Perhaps an idea to not enable it by default when updating?

**Comment by mallowigi** [comment]
That's why I want to understand why this happens to you. If you can provide me more details about your setup so I can know how to reproduce since it doesn't happen on my computer.

**Comment by mallowigi** [comment]
Also, I didn't ask the obvious: maybe it's not a bug but rather that you have a very big screen?

**Comment by Lumeriol** [comment]
I had the same problem, turning off the Centered Editor fixed it.
For me, I upgraded the plugin from the previous version 8.13, I have IDE 2024.1#5, 2560x1440 resolution on a 27" monitor, I did not modify/adjust settings of Material Theme in any way. I have Windows 11, 4 identical monitors. I use the Atom One Dark/Light theme - I switch between them as needed.

The problem occurred immediately after installing the new version and restarting the IDE.

However, if I reduced the size of the IDE by about one third, everything behaved correctly. But as I expanded to wide, the indentation increased to a disproportionate width, or rather, there is a giant space with line numbers and a fixed size editing window.

**Comment by michaelmeirsman** [comment]
I had same problem with 1980x1024 display, Scale 100%, Windows 10. turning off centered editor did the trick.

**Comment by EranNL** [comment]
@mallowigi I indeed have quite a big screen. 34" (3440x1440). No distraction free mode enabled (I didn't know it existed until you asked me 😛). No zoom. Using MacOS Sonoma 14.4 Beta. Just updated and my code appeared in the middle as can be seen in the picture. Distraction free mode still has it in the middle though, but there it looks good!

**Comment by mallowigi** [comment]
So it looks like that the setting doesn't work well in big resolutions then. I need to find such a setup, if it's not fixable I'll try to revoke the setting for such resolutions

**Comment by mallowigi** [comment]
Can you show a video ?

**Comment by EranNL** [comment]
Sure, but the function does work. It just auto enabled after the update to v9.0.0 causing the confusion.

**Comment by mallowigi** [comment]
If it's a matter of a new setting causing confusion, then it's fine. Either people will discover a new way of working, or they can disable it from the settings.

**Comment by EranNL** [comment]
Still made a video though, so you can see how it looks on bigger screens :)

https://github.com/mallowigi/material-theme-issues/assets/10157169/b0288508-1b5b-4ac2-8372-474ee23e0df3

**Comment by mallowigi** [comment]
Ok so it does exactly what it's supposed to do. Instead of having a huge space on the right, now you have it on both sides. 

So I surmise this is not a bug, just a misconception. Thanks!
