### ISSUE TITLE
[Bug]: Gutter increases in size once I resize the editor window past a certain width 

### ISSUE THREAD

**Issue by WayneDV** [mallowigi/material-theme-issues#458]
### Describe the bug

On a wide screen, when I increase the editor panel's width, the gutter starts to stretch wider too.

Material Theme UI 9.0.0
PhpStorm 2024.1 EAP
Build #PS-241.13688.22, built on February 22, 2024

![Screenshot_20240227_134111](https://github.com/mallowigi/material-theme-issues/assets/3840448/c0ecf0de-2b13-4300-817a-9b630da429dc)

### To Reproduce

1. Maximize PhpStorm on a wide screen
2. Open a file to edit
3. Stretch the width of the editor panel beyond the default width
4. The gutter starts to grow in width and the line numbers move right

### Expected behavior

The gutter width should remains constant, the line numbers should remain in place

### Material Theme Version

v9.0.0.0

### IDE

PHPStorm

### System Info

```shell
PhpStorm 2024.1 EAP
Build #PS-241.13688.22, built on February 22, 2024

Runtime version: 17.0.10+8-b1207.1 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.5.0-21-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 6096M
Cores: 8
Registry:
  ide.balloon.shadow.size=0
  editor.distraction.free.mode=true
  debugger.new.tool.window.layout=true
  run.processes.with.pty=TRUE
  ide.new.editor.tabs.vertical.borders=true
  ide.experimental.ui=true
  ide.editor.tab.selection.animation=true
Non-Bundled Plugins:
  com.vermouthx.xcode-theme (1.6.3)
  com.jetbrains.space (241.13688.16)
  com.tylerthrailkill.intellij.solarized (3.0.0)
  com.arcticicestudio.nord.jetbrains (0.13.0)
  com.wakatime.intellij.plugin (14.3.11)
  com.github.copilot (1.4.17.4734)
  com.github.jk1.ytplugin (2023.1.73)
  com.chrisrm.idea.MaterialThemeUI (9.0.0)
  ru.adelf.idea.dotenv (2024.1)
  com.laravel_idea.plugin (8.1.2.241)
  com.intellij.microservices.ui (241.13688.22)
Current Desktop: KDE
```

**Comment by mallowigi** [comment]
can you show a video ?

**Comment by rafa-suarez-itx** [comment]
Same issue here!

**Comment by dmbaranov** [comment]
Same issue with the latest updates. 

WebStorm 2024.1 EAP (Build #WS-241.14024.30);
Material Theme UI (9.0.0)
macOS Sonoma 14.3.1

UPD. Though it seems like [it's a feature](https://github.com/mallowigi/material-theme-issues/issues/456), not a bug. Just as a feedback, I was pretty sure that something was broken and had to rollback to previous version. Perhaps it makes sense to disable it by default and then mention in a changelog.

But thanks for updating the extension and adding new features nevertheless!

**Comment by mallowigi** [comment]
It should be in the changelog, isn't it?

**Comment by dmbaranov** [comment]
@mallowigi sorry, you're right! Somehow I missed it.

**Comment by ozgurozalp** [comment]
The problem still persists in webstorm v2024.1

**Comment by EM-ismaelgonzalez** [comment]
I have installed the Material Theme UI and fixed this issue by going to `Settings -> Material Theme UI -> Features` then unchecking the **Centered Editor** checkbox.
