### ISSUE TITLE
new material_theme_project_new.xml file changes every time I use intellij.

### ISSUE THREAD

**Issue by greenhull** [mallowigi/material-theme-issues#463]
### Describe the bug

new material_theme_project_new.xml file changes every time I use IntelliJ. This is a problem because I use program on 2 different systems (work and home) and maintain consistency by saving to a source control system (SVN). Thus I have to update this file every time I have to update this file every time I switch systems  (usually a couple of times a day) I have to do an SVN  commit and update  pass on the project. (many times I'm just looking not changing project).  I assume(?) that the file has 2 uses, settings and licensing.  these should be in different files (the licensing one I'll ignore and the settings one gets updated I change material theme options 

### To Reproduce

starting from the same project (on two different systems)  bring up IntelliJ save the projects and look at the material_theme_project_new.xml files on each system they'll be different.

### Expected behavior

the file should remain the same until some material theme option is changed.

### Material Theme Version

v9.0.0

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2024.1 EAP (Ultimate Edition)
Build #IU-241.14024.14, built on February 28, 2024
Licensed to IntelliJ IDEA EAP user: Chester John
Expiration date: March 29, 2024
Runtime version: 17.0.10+8-b1207.1 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
  ide.balloon.shadow.size=0
  editor.distraction.free.mode=true
  debugger.new.tool.window.layout=true
  ide.new.editor.tabs.vertical.borders=true
  ide.animate.toolwindows=true
  ide.experimental.ui=true
  ide.editor.tab.selection.animation=true
  idea.ignore.disabled.plugins=true
Non-Bundled Plugins:
  com.intellij.javafx (1.0.4)
  org.antlr.intellij.plugin (1.23)
  Gradle View (4.0.0)
  com.jetbrains.space (241.14024.14)
  com.godwin.json.parser (1.7.1)
  com.intellij.properties.bundle.editor (241.14024.14)
  org.sylfra.idea.plugins.linessorter (1.0.1)
  com.dubreuia.tool (2.6.3)
  com.zt.json-editor (2.9.1)
  String Manipulation (9.12.0)
  tarn.gradle.dependencies (1.6.2)
  GrepConsole (12.25.0-IJ2023.3)
  com.chylex.intellij.inspectionlens (1.3.2)
  PlantUML integration (7.7.0-IJ2023.2)
  net.seesharpsoft.intellij.plugins.csv (3.3.0-241)
  com.github.platan.gradle-dependencies-formatter (0.6.1)
  com.yiycf.plugins.mavenDependencyHelper (2.5)
  com.gluonhq.plugin.intellij (2.8.6)
  MavenRunHelper (4.27.1-IJ2022.2)
  com.intellij.ml.llm (241.14024.14)
  izhangzhihao.rainbow.brackets (2024.2.1)
  com.chrisrm.idea.MaterialThemeUI (9.0.0)
  org.mallowigi.idea.MaterialThemeUI.HighContrast (2024.1.1)
  com.github.affishaikh.kotlinbuildergenerator (2.0.0)
  GradleDependenciesHelper (1.16)
  org.sonarlint.idea (10.3.0.77475)
  com.mallowigi (95.0.0)
  zielu.gittoolbox (500.1.11+222)
  com.kn.diagrams.generator.generator (2022.2.0)
Kotlin: 241.14024.14-IJ
```

### Logs/Screenshots

```shell
NA
```

**Comment by mallowigi** [comment]
I tried reproducing your issue but I couldn't reproduce.

Can you tell me what changed between uses so that I can pinpoint it?

**Comment by mallowigi** [comment]
If you're using a version control most likely you can determine what changed.
