### ISSUE TITLE
[Bug]: Unexpectedly wide spacing between the 'Project view' and the 'Editor'

### ISSUE THREAD

**Issue by kevin-lee** [mallowigi/material-theme-issues#465]
### Describe the bug

In the latest IntelliJ IDEA EAP (2024.1 Beta), there's unexpectedly wide spacing between the `Project view` and the `Editor` like the following screen shot.
![Screenshot 2024-03-10 at 10 09 41 pm](https://github.com/mallowigi/material-theme-issues/assets/2307335/6b9d9d1d-39ae-46b0-b961-069fcef1100c)

It disappears if I disable Material Theme UI, and I don't have this issue with IntelliJ IDEA 2023.3.

Also the buttons have too much spacing.
![Screenshot 2024-03-10 at 10 16 42 pm](https://github.com/mallowigi/material-theme-issues/assets/2307335/4c5ba6f7-55bf-4547-8652-7adf102737b7)

### To Reproduce

Install IntelliJ IDEA 2024.1 Beta (the current EAP) and run it with Material Theme UI enabled.

### Expected behavior

Not too much spacing

### Material Theme Version

v9.0.0

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2024.1 Beta (Ultimate Edition)
Build #IU-241.14494.17, built on March 6, 2024
Licensed to IntelliJ IDEA EAP user: ...
Expiration date: April 5, 2024
Runtime version: 17.0.10+8-b1207.6 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.6.4
GC: G1 Young Generation, G1 Old Generation
Memory: 3072M
Cores: 10
Metal Rendering is ON
Registry:
  undo.documentUndoLimit=500
  ide.tooltip.initialDelay=507
  ide.balloon.shadow.size=0
  editor.distraction.free.mode=true
  editor.focus.mode.color.light=777777
  editor.focus.mode.color.dark=777777
  debugger.new.tool.window.layout=true
  ide.new.editor.tabs.vertical.borders=true
  ide.animate.toolwindows=true
  ide.experimental.ui=true
  ide.editor.tab.selection.animation=true
  scala.erase.compiler.process.jdk.once=false
Non-Bundled Plugins:
  com.intellij.plugins.expui (0.4)
  com.jetbrains.rust (241.24015.155)
  com.jetbrains.space (241.14494.17)
  org.jetbrains.settingsRepository (241.14494.17)
  com.andrey4623.rainbowcsv (2.0.2)
  com.wakatime.intellij.plugin (14.3.11)
  com.intellij.kubernetes (241.14494.25)
  String Manipulation (9.12.0)
  org.jetbrains.plugins.hocon (2024.1.0)
  GrepConsole (12.25.0-IJ2023.3)
  com.intellij.ml.llm (241.14494.33)
  izhangzhihao.rainbow.brackets (2024.2.1)
  com.chrisrm.idea.MaterialThemeUI (9.0.0)
  mdx.js (241.14494.17)
  com.mallowigi (95.0.0)
  org.intellij.scala (2024.1.576)
Kotlin: 241.14494.17-IJ
```

**Comment by mallowigi** [comment]
Please read the changelog folks. It is described there as a new feature "Centered Editor"

For the buttons, it's the first time I saw that. Please open a separate issue.

**Comment by kevin-lee** [comment]
@mallowigi Thank you. It's fine after turning off `Centered Editor`. It would have been better if the default behavior wasn't changed though.

I've created another ticket for the button margin issue (#470)
