### ISSUE TITLE
[Bug]: Search result matches are not shown in the sidebar

### ISSUE THREAD

**Issue by dmitry-ivanov** [mallowigi/material-theme-issues#467]
### Describe the bug

If you do a text search within the file, matches are not shown in the sidebar.

![search](https://github.com/mallowigi/material-theme-issues/assets/1286821/c39e2503-68c5-464d-9e42-31700d1611fa)

There's a closed issue on JetBrains tracker, but they say it's a third-party problem:
https://youtrack.jetbrains.com/issue/IDEA-343004/Code-search-highlighting-in-the-editor-sidebar-does-not-appear

### To Reproduce

1. Open any text file.
2. Search for a string that has several occurrences in that file.
3. The matches in the text are highlighted (which is correct), but the matches on the sidebar are not highlighted (which is a problem).

### Expected behavior

The matches in the text are highlighted, as well as the matches on the sidebar.

### Material Theme Version

8.13.2

### IDE

PHPStorm

**Comment by AlexV525** [comment]
Hi, I'm the author of that YouTrack issue.
I'm running into the issue when using the Monokai theme, I believe it's happening to all themes provided by the plugin. This significantly degrades the search experience which makes it hard to determine their positions. Would appreciate it if you could help @mallowigi Thanks!

<img width="678" alt="image" src="https://github.com/mallowigi/material-theme-issues/assets/15884415/ffb421b1-4cca-46cb-93fb-ed39080c40de">

**Comment by mallowigi** [comment]
will be available next version

**Comment by dmitry-ivanov** [comment]
@mallowigi I've just noticed that after updating to the latest version of PHPStorm (2024.2.3) and on Material Theme UI (9.5.0) - it doesn't work again.

Could you please take a look when you have a chance for that?

Thank you!

**Comment by dmitry-ivanov** [comment]
> will be available next version

@AlexV525 Has the problem been fixed for you?

**Comment by AlexV525** [comment]
> [@AlexV525](https://github.com/AlexV525) Has the problem been fixed for you?

Yes. I'm using IDEA 2024.3 and it's still working.
