### ISSUE TITLE
[Bug]: Hovering over icons has a different appearance

### ISSUE THREAD

**Issue by Hardel-DW** [mallowigi/material-theme-issues#478]
### Describe the bug

JetBrains, by default, opts for a subtle design with a minimal border-radius for its icons. However, what's being observed here diverges significantly from this norm. The icons exhibit a stark 50% border-radius upon hover, coupled with a distinct color change. This departure from the standard is further compounded by the inconsistency in icon design; some icons are square, completely devoid of any padding or margin, while others include them. This lack of uniformity, alongside the absence of an option to revert or modify these design choices, underscores a notable incoherence in the UI's visual language regarding margin/padding, border-radius, and hover effects.
Any options for deactivating this design change?

![image](https://github.com/mallowigi/material-theme-issues/assets/42413417/3e09df19-539c-45a0-8d27-15831993c134)

### To Reproduce

1. Just Install Material UI

### Expected behavior

There is an option to deactivate this so that it is more consistent with the artistic direction of the new JetBrains interface.

### Material Theme Version

9.1.0

### IDE

WebStorm

### System Info

```shell
WebStorm 2024.1
Build #WS-241.14494.235, built on March 27, 2024
Licensed to Gael Rocher
Subscription is active until April 4, 2025.
For educational use only.
Runtime version: 17.0.10+8-b1207.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4082M
Cores: 24
Registry:
  ide.balloon.shadow.size=0
  ide.new.editor.tabs.vertical.borders=true
  ide.animate.toolwindows=true
  ide.experimental.ui=true
  ide.editor.tab.selection.animation=true
  terminal.new.ui=true
Non-Bundled Plugins:
  com.wakatime.intellij.plugin (14.3.13)
  com.samdark.intellij-visual-studio-code-dark-plus (2.8)
  ru.adelf.idea.dotenv (2024.1)
  com.intellij.ml.llm (241.14494.240)
  org.jetbrains.plugins.astro (241.14494.140)
  com.github.copilot (1.5.1.5332-nightly)
  com.almightyalpaca.intellij.plugins.discord (1.12.0)
  com.intellij.database (241.14494.180)
  com.chrisrm.idea.MaterialThemeUI (9.1.0)
  mdx.js (241.14494.140)
  com.mallowigi (95.0.0)
  mobi.hsz.idea.gitignore (4.5.2)
```

**Comment by mallowigi** [comment]
Can you explain what you mean by lack of uniformity? The selected indicator when hovering over icons is always circular and has always been. 

The only new "regression" I can think of is when hovering over the "tab buttons" (for instance, in the find in files popup), and I've left this for later as there is no simple way to use a different kind of indicator, as all indicators share the same border radius.

There is no option to control the border radius, but if enough people demand for such a feature ill implement it.

**Comment by Hardel-DW** [comment]
![image](https://github.com/mallowigi/material-theme-issues/assets/42413417/f0a92b3d-b185-4bd6-a6b0-92df2b000b60)
Jetbrains uses this kind of design by default with the new 2023 interface. that hovered and active elements have the same design.
Material Design it's different, an active element is square and hovered round.

Just being able to disable some things on Material Design would be nice, personally I prefer the default design with rounded edges and outer margins.

**Comment by mallowigi** [comment]
This is by design, and as I said, this has been for a long time.

On the other hand, there are some elements that are customizable already such as the round notifications or the outline buttons. But those are only available in the premium plan.

I can give such a feature to control the radii of the indicators, probably, but this will also be a premium feature, I'm afraid.

**Comment by Hardel-DW** [comment]
Okay Why not, I have the premium version. But don't worry it's already incredible If you had the time it would be cool. Control margins and radius.

**Comment by mallowigi** [comment]
[Material Theme UI-9.2.0.zip](https://github.com/mallowigi/material-theme-issues/files/14889233/Material.Theme.UI-9.2.0.zip)

In the end I decided to provide a simple fix because I don't feel the necessity to provide that much customization for a simple case. This version introduces a new setting inside the UI Components page to revert the tool windows look to the one provided by JetBrains. 

It's a free setting (for now, until more customization options are available)

**Comment by Hardel-DW** [comment]
You're super quick to respond. Thank ❤️ I love you

**Comment by Hardel-DW** [comment]
I have a last small request, I don't want to disturb you about something else.
