### ISSUE TITLE
[Bug]: Unusual spaciousness

### ISSUE THREAD

**Issue by agiy** [mallowigi/material-theme-issues#479]
### Describe the bug

I don't know what you call this place, but it would be unusually large.
![CleanShot 2024-04-05 at 15 01 21](https://github.com/mallowigi/material-theme-issues/assets/14961989/a2883f6c-0532-4eb0-a35f-c2633d71eb2d)

### To Reproduce

none

### Expected behavior

Normal size

### Material Theme Version

95.0.0

### IDE

PHPStorm

### System Info

```shell
2024.1
sonoma 14.4 1
95.0.0
```

**Comment by wiseneuron** [comment]
I have the same bug. thanks your report.

**Comment by wiseneuron** [comment]
Intellij IDEA 2024.1 have the same issue.

**Comment by JelianRadoev** [comment]
Webstorm 2024.1 - Sonoma 14.4.1 same issue

**Comment by mallowigi** [comment]
Read other open issues please
