### ISSUE TITLE
Dark window bar with IntelliJ Light on macOS light mode in v6.12+

### ISSUE THREAD

**Issue by jessedobbelaere** [mallowigi/material-theme-issues#48]
**Describe the bug**

On version `Material_Theme_UI-6.10.1` or lower, I was using the IntelliJ Light appearance theme. 
When I click the UPDATE button for the plugin and restart my IDE, it gets updated to `Material_Theme_UI-6.12.0` or `6.12.1` I get a dark window bar and tab bar. And no option to revert it back besides uninstalling the Material Theme plugin or downgrading by installing plugin v6.10.1 via `Install Plugin from Disk`. 

All other menu's are in light mode except the window bar and tabs

Note: I disabled `ide.mac.transparentTitleBarAppearance=false` because of a bug in the latest Jetbrains IDE's (https://youtrack.jetbrains.com/issue/IDEA-268182). If I bring it back, there's not much difference. Tabs are still in dark mode. The window bar is back gray but the tabs are not. It's even worse, because there's now white text on light grey tabs making it unreadable. See last screenshot. 

**To Reproduce**

1. Use IntelliJ Light theme for appearance and macOS light mode. 
2. Test on v6.10.1 (no issue) and upgrade to 6.12.0 or 6.12.1 where window bar and tabs bar will be set to dark mode. 

I tested in both PHPStorm, Webstorm and IntelliJ IDEA Ultimate and all three have the same issue after updating. 

**Expected Behavior**

Just like version 6.10.1 and lower did, the IDE should be in light mode when I select IntelliJ Light appearance with macOS light mode.

**Environment**

PhpStorm 2021.3
Build #PS-213.5744.279, built on December 2, 2021
Subscription is active until April 30, 2022.
Runtime version: 11.0.13+7-b1751.19 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
    undo.documentUndoLimit=500
    debugger.watches.in.variables=false
    run.processes.with.pty=TRUE
    ide.mac.transparentTitleBarAppearance=false
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    org.sylfra.idea.plugins.linessorter (1.0.1)
    name.kropp.intellij.makefile (213.5744.224)
    ideanginx9 (0.1.9)
    org.intellij.plugins.hcl (0.7.14)
    org.intellij.plugins.postcss (213.5744.190)
    com.alicannklc.tailwind (1.4.6)
    String Manipulation (8.23.203.000.0)
    mobi.hsz.idea.gitignore (4.3.0)
    net.king2500.plugins.PhpAdvancedAutoComplete (1.1.0)
    de.espend.idea.php.phpunit (6.2)
    com.kalessil.phpStorm.phpInspectionsEA (4.0.7.1)
    de.espend.idea.php.toolbox (6.0.0)
    de.espend.idea.php.annotation (8.0.0)
    fr.adrienbrault.idea.symfony2plugin (0.23.213)
    NEON support (0.5.1)
    de.timo_reymann.intellij-mjml-support (1.20.2)
    izhangzhihao.rainbow.brackets (6.21)
    com.github.inxilpro.intellijalpine (v0.4.2)
    com.chrisrm.idea.MaterialThemeUI (6.12.1)
    me.mbolotov.cypress (1.4.2)
    com.mallowigi (50.2.0)
    ru.adelf.idea.dotenv (2021.3.0.213)

**Screenshots**

![Screenshot 2021-12-20 at 21 56 27@2x](https://user-images.githubusercontent.com/1352979/146833047-3db89118-f3d8-41a3-8d15-b28ca415609c.png)
![Screenshot 2021-12-20 at 21 59 29@2x](https://user-images.githubusercontent.com/1352979/146833055-174cd898-f31b-4237-9231-4aebfb424317.png)
![Screenshot 2021-12-20 at 22 11 30@2x](https://user-images.githubusercontent.com/1352979/146833475-a63e77c8-c4f1-4817-a004-fac2b26956c6.png)

**Comment by mallowigi** [comment]
Hum i think I know why. I remember during the refactor I asked myself why non material themes were all converted to "DarkBundledTheme", even when they are light; but upon testing I couldn't see any difference so I thought it was fine. But I haven't checked that particular scenario.

I will try to reproduce as soon as I can and try to find a fix.

**Comment by jessedobbelaere** [comment]
Thanks @mallowigi, the updated version works perfectly!
