### ISSUE TITLE
[Bug]: Darkening Overlay that comes up when the 'find in files' modal is open applies to all Webstorm tabs

### ISSUE THREAD

**Issue by ianrose2k** [mallowigi/material-theme-issues#485]
### Describe the bug

Webstorm tab overlay is applied to all webstorm tabs when a modal is opened instead of just the tab where the modal was opened.

### To Reproduce

1. Add Material them plugin to webstorm and restart
2. Choose 'Github dark' (not sure if this is relavent)
3. Open 2 separate project windows
4. In one project window, right click on a file directory and click 'Find in files'
5. A modal pops up, and adds an overlay over the background
6. Notice this overlay is applied to the other projects window too, even though it doesnt have any modals open and clicking on the window does not close the search modal on the other window, it just prevents me from making changes to one window while the other window has this modal open

### Expected behavior

Overlay is only applied to the window that the modal was opened on and other project windows are still usable while a different window has the find in files modal open

### Material Theme Version

v9.1.0

### IDE

WebStorm

### System Info

```shell
WebStorm 2024.1 RC
Build #WS-241.14494.180, built on March 22, 2024
Licensed to Retail Pro International, LLC / Ian Rose
Subscription is active until June 26, 2024.
Runtime version: 17.0.10+8-b1207.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 20
Registry:
  ide.balloon.shadow.size=0
  editor.distraction.free.mode=true
  ide.new.editor.tabs.vertical.borders=true
  ide.animate.toolwindows=true
  ide.experimental.ui=true
  ide.editor.tab.selection.animation=true
Non-Bundled Plugins:
  dev.turingcomplete.intellijdevelopertoolsplugins (4.1.1)
  com.gafner.giv (2024.1.14)
  com.intellij.grazie.pro (0.3.294)
  com.intellij.ml.llm (241.14494.189)
  com.chrisrm.idea.MaterialThemeUI (9.1.0)
  org.jetbrains.plugins.docker.gateway (241.14494.189)
  izhangzhihao.rainbow.brackets (2024.2.2-241)
```

**Comment by mallowigi** [comment]
The overlays are applied on the application frame, not the project frame. There is no way to put overlays on a project frame basis. 

Sorry, going to close this.
