### ISSUE TITLE
[Bug]: "Custom Item Line Height" setting set the "customTreeIndentEnabled" property to true

### ISSUE THREAD

**Issue by MrPrimitive** [mallowigi/material-theme-issues#486]
### Describe the bug

Activating the "Custom Item Line Height" sets the "Custom Tree Indent" setting. Activating the "Custom Tree Indent" option has no effect.

The following configuration creates the following setting
![Setting_MUI](https://github.com/mallowigi/material-theme-issues/assets/41343627/bab8ee4d-b68a-4282-ac96-cc04966ba8c4)

```
<option name="projectTreeState">
    <MTProjectTreeConfigState>
        <option name="customLeftTreeIndent" value="4" />
        <option name="customLineHeight" value="18" />
        <option name="customTreeIndentEnabled" value="true" />
    </MTProjectTreeConfigState>
</option>
```

### To Reproduce

"Custom Item Line Height"
1. Go to Settings > Appearance &  Behavior > Material Theme UI > Trees > Spacing
2. Enable "Custom Item Line Height"
3. Click "Apply"
4. The "Custom Tree Indent" will be applied.

"Custom Tree Indent"
1. Go to Settings > Appearance &  Behavior > Material Theme UI > Spacing > Trees
2. Enable "Custom Tree Indent"
3. Click "Apply"
4. Nothing happen

### Expected behavior

The "Custom Item Line Height" set a custom size of tree items
The "Custom Tree Indent" set a custom tree indent

![Setting_MUI](https://github.com/mallowigi/material-theme-issues/assets/41343627/4fbd17d9-c8cc-460d-9732-be923f684191)

```
<option name="projectTreeState">
    <MTProjectTreeConfigState>
        <option name="customLeftTreeIndent" value="4" />
        <option name="customLineHeight" value="18" />
        <option name="customLineHeightEnabled" value="true" />
        <option name="customTreeIndentEnabled" value="true" />
    </MTProjectTreeConfigState>
</option>
```

### Workaround

For fixing this go to the `Material_theme_new.xml` in the `%APPDATA%\Roaming\JetBrains\WebStorm2024.1\options` folder and add in the `projectTreeState` section the option `customTreeIndentEnabled` and set value to `true`.

```
<option name="projectTreeState">
  <MTProjectTreeConfigState>
    <option name="customLineHeight" value="18" />
    <option name="customTreeIndentEnabled" value="true" />
  </MTProjectTreeConfigState>
</option>
```

### Material Theme Version

v9.1.0

### IDE

WebStorm

### System Info

```shell
Windows 10.0
WebStorm 2024.1
com.chrisrm.idea.MaterialThemeUI (9.1.0)
Build #WS-241.14494.235, built on March 27, 2024
```

**Comment by mallowigi** [comment]
Good catch. I'll submit for next version
