### ISSUE TITLE
[Bug]: the Annotate with git blame area's width weird , can not adjust width

### ISSUE THREAD

**Issue by zsmj1994** [mallowigi/material-theme-issues#487]
### Describe the bug

<img width="420" alt="企业微信截图_20240407113239" src="https://github.com/mallowigi/material-theme-issues/assets/17895839/55f12fe1-f5fe-40c2-9383-b5b5ce08d481">

### To Reproduce

upgrade the webstorm to 2024.1 and the plugin version is 9.1.0

### Expected behavior

behavior normal

### Material Theme Version

9.1.0

### IDE

WebStorm

**Comment by zsmj1994** [comment]
![image](https://github.com/mallowigi/material-theme-issues/assets/17895839/7c95a77e-7cb5-4600-936e-3ac948d2722d)

**Comment by shijiekk** [comment]
I had the same problem after I upgraded today.
