### ISSUE TITLE
[Bug]: It is so huge between Repository Tree and code contant. 

### ISSUE THREAD

**Issue by JackieWangDJ** [mallowigi/material-theme-issues#488]
### Describe the bug

![image](https://github.com/mallowigi/material-theme-issues/assets/30018029/ee84dcda-9439-446e-bbb1-ba94a480a091)
It is so huge between Repository Tree and code contant. 

### To Reproduce

open idea 
update this plugin for latest release

### Expected behavior

open idea 
update this plugin for latest release
restart idea

### Material Theme Version

v9.1.0

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2024.1 (Ultimate Edition)
Build #IU-241.14494.240, built on March 28, 2024
Licensed to Sherlock Wang
Subscription is active until July 18, 2024.
For educational use only.
Runtime version: 17.0.10+8-b1207.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4070M
Cores: 16
Registry:
  ide.balloon.shadow.size=0
  editor.distraction.free.mode=true
  ide.new.editor.tabs.vertical.borders=true
  ide.animate.toolwindows=true
  ide.experimental.ui=true
  ide.editor.tab.selection.animation=true
Non-Bundled Plugins:
  com.jetbrains.space (241.14494.150)
  JBLJavaToWeb (1.4.3)
  com.alibabacloud.intellij.cosy (1.2.7)
  coderead.IdeaPlugins.maven (1.2)
  au.com.glassechidna.luanalysis (1.4.0)
  MavenRunHelper (4.28.0-IJ2022.2)
  com.intellij.ml.llm (241.14494.240)
  izhangzhihao.rainbow.brackets (2024.2.2-241)
  com.chrisrm.idea.MaterialThemeUI (9.1.0)
  org.intellij.gitee (2024.1.0)
  com.mallowigi (95.0.0)
  com.baomidou.plugin.idea.mybatisx (1.6.1)
  cn.yiiguxing.plugin.translate (3.5.7)
Kotlin: 241.14494.240-IJ
```

**Comment by ThomasSfflx** [comment]
same here

**Comment by JackieWangDJ** [comment]
Settings > Centered Editor
but i don't know when i enabled this setting.

**Comment by beonic-rufus** [comment]
This is due to Material Theme somehow putting users in Distraction Free mode each time IDE is restarted. I have had this happening since update on IntelliJ Build #IU-241.14494.240, built on March 28, 2024 so it seems it might affect all IDEs. To exit, you will need to go to View > Appearance > Exit Distraction Free Mode each time your IDE is restarted ... very annoying. If you uninstall material UI then this issue does not happen. I've tested this.
