### ISSUE TITLE
The main menu background color with children items

### ISSUE THREAD

**Issue by an2riy** [mallowigi/material-theme-issues#49]
**Describe the bug**
When the plugin is enabled in the main menu all the menu selected items that have children do not have the background color.

**To Reproduce**
Go to **Window -> Active Tool Window** (Hover on it).
No the background color for the selected menu item on the **Active Tool Window**.
![image](https://user-images.githubusercontent.com/8819844/146920678-1ceb2a61-352e-4ec3-875c-84da185d4f99.png)
When the plugin is disabled everything is fine with the **Window -> Active Tool Window** it has the background color:
![image](https://user-images.githubusercontent.com/8819844/146922438-98231f51-9534-42a6-a028-5d4b12d44d10.png)

**Expected Behavior**
Go to **Window -> Active Tool Window** (Hover on it).
The background color for the selected menu item has to be as in the **Restore Default Layout**
![image](https://user-images.githubusercontent.com/8819844/146921390-7a7b9207-cceb-4d1f-b0cd-5bff7c9c07ac.png)

**Environment**
* Ubuntu 20.10, Desktop: ubuntu:GNOME 3.38.3
* PhpStorm 2021.3
Build #PS-213.5744.279, built on December 2, 2021
Licensed to Andrii Dorotiuk
Subscription is active until June 8, 2022.
Runtime version: 11.0.13+7-b1751.19 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.8.0-63-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2944M
Cores: 12
Registry:
    debugger.watches.in.variables=false
    editor.caret.width=1
    run.processes.with.pty=TRUE
    ide.experimental.ui.toolwindow.stripes=true
    ide.balloon.shadow.size=0
Non-Bundled Plugins:
    ski.chrzanow.foldableprojectview (1.1.1)
    pronskiy.elephpant (0.1.1)
    org.elasticsearch4idea (1.7.1-2021.2)
    name.kropp.intellij.makefile (213.5744.224)
    ir.msdehghan.plugins.ansible (0.92)
    io.github.az1a.reminder (0.3)
    indent-rainbow.indent-rainbow (1.7.0)
    com.ultrahob.zerolength.plugin (0.95)
    com.intellij.ideolog (203.0.27.0)
    com.intellij.properties (213.5744.121)
    com.alayouni.ansiHighlight (1.2.4)
    String Manipulation (8.23.203.000.0)
    zielu.gittoolbox (212.8.4)
    mobi.hsz.idea.gitignore (4.3.0)
    de.espend.idea.php.annotation (8.0.0)
    com.kalessil.phpStorm.phpInspectionsUltimate-mp (2021.5)
    fr.adrienbrault.idea.symfony2plugin (0.23.213)
    com.magento.idea.magento2plugin (4.2.1)
    lv.midiana.misc.phpstorm-plugins.deep-keys (2021.07.18.002)
    izhangzhihao.rainbow.brackets (6.21)
    com.chrisrm.idea.MaterialThemeUI (6.12.1)
    com.mallowigi (50.2.0)
    org.jetbrains.plugins.node-remote-interpreter (213.5744.122)
    ru.adelf.idea.dotenv (2021.3.0.213)
* Plugin version: 6.12.1
* Enabled plugins: does not depend on other plugins has been enabled only the one **Material Theme UI** plugin and the issue is present.

**Comment by an2riy** [comment]
The custom them colors: [Custom Theme.zip](https://github.com/mallowigi/material-theme-issues/files/7755051/Custom.Theme.zip)

**Comment by mallowigi** [comment]
fixed
