### ISSUE TITLE
Different tab sizes between console and default tab

### ISSUE THREAD

**Issue by Abdelraman** [mallowigi/material-theme-issues#491]
### Describe the bug

different tab size between the top and console tabs

### To Reproduce

1. open any tab normally for any file
2. try to open the console to with tabs e.g running a script as shown below
![image](https://github.com/mallowigi/material-theme-issues/assets/4821833/e71dbce1-c91b-4a76-ad9c-75863dbbb184)

### Expected behavior

should have the same padding (height)

### Material Theme Version

v9.2

### IDE

PHPStorm

**Comment by mallowigi** [comment]
will be fixed at next release
