### ISSUE TITLE
[Bug]: Language Additions shows as a Severity

### ISSUE THREAD

**Issue by mgroth0** [mallowigi/material-theme-issues#492]
### Describe the bug

Language Additions shows an icon in the part of the editor that tells you whether or not the current file has issues. It doesn't seem this icon can be disabled.

### To Reproduce

1. Disable Language Additions
2. Restart IntelliJ
3. Open file that has no issues
4. Observe check mark. When you hover over it, it says "No problems found"
5. Enable Language Additions
6. Restart IntelliJ
7. Open same file
8. Observe no checkmark, but instead an "ABC" icon that says "X Language Additions"

### Expected behavior

Language Additions should not show this icon

### Material Theme Version

9.2.0

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2024.1 (Ultimate Edition)
Build #IU-241.14494.240, built on March 28, 2024
Runtime version: 17.0.10+8-b1207.12 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4.1
```

### Logs/Screenshots

```shell
I have screenshots. But the GitHub issue template seems to not allow attaching screenshots like the normal issue editor does. When I try to drag in the screenshots nothing happens, and there is no separate control to add them.
```

**Comment by mgroth0** [comment]
<img width="163" alt="tmp" src="https://github.com/mallowigi/material-theme-issues/assets/12831489/d505c151-501c-45b0-8954-3af5d54831b8">
<img width="324" alt="tmp2" src="https://github.com/mallowigi/material-theme-issues/assets/12831489/2cc1002e-8c02-456f-b151-64a01f2efdee">

**Comment by mgroth0** [comment]
Two main problems here:
1. The Language Addition feature should work more transparently. Users don't need this information
2. The check mark is information that users do need to quickly verify a file has no issues, and Language Additions prevents that checkmark. This issue is made more severe because I suppose the checkmark would still show on files that do not have any extra highlighting from Language Additions. As a result, the check mark users expect would show unpredictably on certain files, which could lead to some confusion.

**Comment by mallowigi** [comment]
I am aware of this issue and this issue exists since the creation of the feature. I tried to find a workaround that doesn't classify the language addition as a severity. In the past there was a toggle named "Enforce Language Additions" but this would create a lot of "fake errors" in the editor. This solution is quieter but it still detects the additions as severities in the "Problems" tool window.

I'm letting this open but this will probably not be fixed for a long time - unless someone chimes in and propose a solution that works :)

**Comment by mgroth0** [comment]
I know that this is probably something for JetBrains to fix in their plugin API, but in the meantime I do appreciate you keeping this open. Maybe we can bounce ideas around here and eventually come up with a workaround.

If I understand correctly, one of the important methods involved here is `TrafficLightRenderer.incErrorCount`([link](https://github.com/JetBrains/intellij-community/blob/0b32e284a1db96a3ad4aaf35857497a570f4fd7c/platform/lang-impl/src/com/intellij/codeInsight/daemon/impl/TrafficLightRenderer.java#L201)). I think that as long as this function returns before incrementing the error count at the bottom, we might be good.

**Comment by mallowigi** [comment]
I wasn't aware of that extension point, this might be a clue to pursue. I'll try to investigate, thanks.

**Comment by mallowigi** [comment]
@mgroth0 I've implemented what you suggested. Let's see if it works.
