### ISSUE TITLE
[Bug]: Huge Gap in Gutter in Editor Window when on Full Screen

### ISSUE THREAD

**Issue by craigmain** [mallowigi/material-theme-issues#493]
### Describe the bug

There is a huge gutter in the margin in the editor.
The editor should be aligned left, but there is a gap as the screen is widened.

![image](https://github.com/mallowigi/material-theme-issues/assets/137081829/0c0c42bf-aeae-46e4-a8d2-a34ea4c507d9)

### To Reproduce

1. Install Latest Version of Intelij and Material UI
2. Open an Editor Window.

There is huge unwanted gutter.

### Expected behavior

There is no gutter.

### Material Theme Version

v9.1.0

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2024.1 (Ultimate Edition)
Build #IU-241.14494.240, built on March 28, 2024
Licensed to Craig Main
Subscription is active until April 30, 2024.
Runtime version: 17.0.10+8-b1207.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 8096M
Cores: 16
Registry:
  ide.balloon.shadow.size=0
  editor.distraction.free.mode=true
  editor.focus.mode.color.light=415967
  editor.focus.mode.color.dark=415967
  ide.new.editor.tabs.vertical.borders=true
  ide.animate.toolwindows=true
  ide.experimental.ui=true
  ide.editor.tab.selection.animation=true
Non-Bundled Plugins:
  com.jetbrains.space (241.14494.150)
  IdeaVIM (2.10.2)
  org.jetbrains.jumpToLine (0.1.15)
  String Manipulation (9.12.0)
  PlantUML integration (7.8.1-IJ2023.2)
  com.intellij.ml.llm (241.14494.240)
  com.github.copilot (1.5.2.5345)
  com.haulmont.jpab (241.14494.158)
  izhangzhihao.rainbow.brackets (2024.2.2-241)
  com.chrisrm.idea.MaterialThemeUI (9.1.0)
  SequenceDiagram (3.0.8)
  com.dmarcotte.handlebars (241.14494.150)
  com.mallowigi (95.0.0)
  zielu.gittoolbox (500.2.3+233)
  aws.toolkit (2.17-241)
Kotlin: 241.14494.240-IJ
```

**Comment by craigmain** [comment]
I have tried this with a new installation of intelij and material UI and the problem is present as soon a material UI is installed and an editor opened.

**Comment by craigmain** [comment]
This looks like it's aleady fixed in the latest version.

**Comment by berdikslis** [comment]
Uncheck the checkbox in Material Theme UI > Features > `Centered Editor`.
