### ISSUE TITLE
[Bug]: Toolbar is obscured

### ISSUE THREAD

**Issue by jornInitor** [mallowigi/material-theme-issues#495]
### Describe the bug

After upgrading to the latest version, I found that the top toolbar of the editor could not be fully displayed, and part of it was blocked.
![image](https://github.com/mallowigi/material-theme-issues/assets/23353657/5ac21529-774b-4604-a382-4f95fbda7599)

### To Reproduce

1.open editor

### Expected behavior

The toolbar can be fully displayed

### Material Theme Version

v9.2.0

### IDE

Other (AppCode, CLion, GoLang...)

### System Info

```shell
windows 11
```

**Comment by mallowigi** [comment]
This looks like you're using a scaled IDE. What value of "zoom" are you using?
