### ISSUE TITLE
[SOLVED]: Broken color schemes after update 

### ISSUE THREAD

**Issue by bcorcoran** [mallowigi/material-theme-issues#496]
### Describe the bug

It appears my material theme ui did not migrate properly after updating to 2024.1/new material ui version.

I was using Palenight before the update and now it appears syntax highlighting is broken for only this theme. I had made some minor customizations to the directory colors, but nothing else. Does not appear to be a nice way to reset the theme to stock, so lots of stuff is unhighlighted.

It doesn't matter if it's in a php file or vue file or any other type of file. It is not applying styles correctly and there appears to be no way to reset. I've tried uninstalling and reinstalling the plugin and it is pulling the config from somewhere.

### To Reproduce

1. Update to latest phpstorm and material theme ui plugin.
2. See that existing theme is broken.

### Expected behavior

1. Theme should not be broken after update

### Material Theme Version

9.2.0

### IDE

PHPStorm

### System Info

```shell
phpstorm 2024.1, macos
```

**Comment by mallowigi** [comment]
The migration doesn't migrate the color scheme, only the material theme settings. The issue might be related to https://github.com/mallowigi/material-theme-issues/issues/377, can you check if that fixes your issue?

**Comment by mallowigi** [comment]
Also, can you please post screenshots of what you are referring to? Thanks.

**Comment by bcorcoran** [comment]
![Screenshot 2024-04-09 at 12 57 53](https://github.com/mallowigi/material-theme-issues/assets/313697/845f1e31-c534-4e07-a26a-633d0ee59ee5)

![Screenshot 2024-04-09 at 11 25 26](https://github.com/mallowigi/material-theme-issues/assets/313697/4e755c1a-27b6-4526-8b25-90b09233039f)

I tried the steps in the mentioned issue and they did not appear to fix anything. I also tried to reset the color scheme to defaults and it had no effect other than resetting font sizes/line heights. The syntax highlighting is still broken for only Palenight.

BTW, I noticed most of the themes are named "<Theme Name> (Material)" but Palenight is listed as Material Palenight. Is this correct?

**Comment by bcorcoran** [comment]
Another wrinkle: 

It appears fine for a moment when it is forced to re-render, but then everything goes gray again. Again, it only happens on this theme, so I'm doubtful that it is another plugin. That said, I am in the process of disabling plugins to see if any of them actually are the culprit.

**Comment by joshuabaker** [comment]
I’m also seeing the same thing with the Night Owl theme — Large swathes of code are greyed out. For me, Palenight actually works.

Is there a way to rerun the migration or reset Material defaults?

**Comment by joshuabaker** [comment]
Just did a full IDE reset, reinstalled the plugin, and it’s working again. Rather nuclear, but something was definitely conflicting somewhere. I don’t tend to stray from defaults, so I would speculate that something’s not quite right in the migration util.

**Comment by bcorcoran** [comment]
> Just did a full IDE reset, reinstalled the plugin, and it’s working again. Rather nuclear, but something was definitely conflicting somewhere. I don’t tend to stray from defaults, so I would speculate that something’s not quite right in the migration util.

I was afraid this was the solution. I will do the same; don't have any more time to spend on this.

edit: Confirmed, **File -> Manage IDE Settings -> Restore Default Settings...** works. Take a screenshot of any important settings/your plugin list before you do it.

**Comment by mallowigi** [comment]
Someone contacted me with the exact same issue - color scheme being jumbled.

We tried everything but nothing worked. In the end we figured it out by removing the Material color schemes prefixed by"_@user" in the colors directory that you can find here:

https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs

Doing so when the IDE is closed would remove the broken color schemes and restore to the factory defaults

**Comment by harpality** [comment]
@mallowigi Thanks! I was experiencing the same exact issue as @bcorcoran with palenight and this worked for me.

**Comment by mallowigi** [comment]
It appears that many other people are experiencing this issue, and it is not only with the Material theme.

https://youtrack.jetbrains.com/issue/IDEA-350915/Color-scheme-broken
https://youtrack.jetbrains.com/issue/IDEA-350656/Color-Scheme-no-longer-works-in-2024.1

<blockquote><img src="static/favicon.ico?3c05e1a5b709165a5c4e825adf27273a?3c05e1a5b709165a5c4e825adf27273a" width="48" align="right"></blockquote>
<blockquote><img src="static/favicon.ico?3c05e1a5b709165a5c4e825adf27273a?3c05e1a5b709165a5c4e825adf27273a" width="48" align="right"></blockquote>
