### ISSUE TITLE
[Bug]: pycharm was upgraded to 2024.1, this theme (Oceanic Theme) has a problem, it used to show color now shows gray

### ISSUE THREAD

**Issue by hermitguo** [mallowigi/material-theme-issues#497]
### Describe the bug

pycharm was upgraded to 2024.1, this theme has a problem, it used to show color now shows gray.
![pycharm-faq](https://github.com/mallowigi/material-theme-issues/assets/14124888/be19fc8f-4bbe-482e-8f90-688ec1299f71)

### To Reproduce

Select **Oceanic Theme**. The py file shows the color code, and then the flash code turns gray, which is not the case in all previous versions of pycharm, only 2024.1 will appear.

### Expected behavior

Want to display color code as before using pycharm2023.3.

### Material Theme Version

V.9.2.0

### IDE

PyCharm

### System Info

```shell
* OS:ubuntu22.04 
* pycharm2024.1
* Plugin:Material Theme UI 9.2.0
```

**Comment by mallowigi** [comment]
Duplicate. Please check other issues before opening
