### ISSUE TITLE
[Bug]: different sizing between form elements

### ISSUE THREAD

**Issue by Abdelraman** [mallowigi/material-theme-issues#498]
### Describe the bug

open any jetbrain product, go to settings and you will find different sizes for the form field as in the pic
![image](https://github.com/mallowigi/material-theme-issues/assets/4821833/81f3d085-6bd3-41c0-ae5d-c0b5c7ab3c93)

### To Reproduce

1. open phpstorm for example
2. click ctrl+alt+s to open the settings and check the spacing between the form fields

### Expected behavior

the spacing should be consistent throughout the whole theme

### Material Theme Version

v9.2

### IDE

PHPStorm

**Comment by mallowigi** [comment]
After taking a look, I found out that this issue is related to the Layout Issues on scaled IDEs. As this is a very difficult task to handle, I'll rather close it, sorry.
