### ISSUE TITLE
[Bug]: different border radius for buttons and icons

### ISSUE THREAD

**Issue by Abdelraman** [mallowigi/material-theme-issues#499]
### Describe the bug

Some icons have a fully rounded borders and other has oval shape icon, which make it not consistent and sometimes annoying, wish to have some option to return back to what version 8 was to be rectangular with a slight border radius as the normal Jetbrain LaF, since the fully rounded border will never adjust to icon and drop down spacing

![image](https://github.com/mallowigi/material-theme-issues/assets/4821833/e2f45dbc-d32d-4f7f-ace0-8a21affbf831)
![image](https://github.com/mallowigi/material-theme-issues/assets/4821833/54507b79-2f78-4153-a6f3-e062e74a2d91)
![image](https://github.com/mallowigi/material-theme-issues/assets/4821833/278d724f-df5e-45a7-acb3-bd017a7e1317)
![image](https://github.com/mallowigi/material-theme-issues/assets/4821833/cabee3fe-c66c-4899-89e3-17453c9932d0)

### To Reproduce

1. open any jetbrain product
2. navigate through the buttons and check how the border being applied to different elements

### Expected behavior

to have an option to use either the oval thingy or the rectangular with slight border as the default LaF

### Material Theme Version

v9.2

### IDE

PHPStorm

**Comment by mallowigi** [comment]
I fully intend to leave rounded buttons as it is, except for the "tabs" which should not be rounded. However the rest of the action buttons will remain rounded.

In the future I could add a setting to control the radius though.

**Comment by mallowigi** [comment]
Will be available next version
