### ISSUE TITLE
[Feature]: Improved centered editor with Distraction Free Mode

### ISSUE THREAD

**Issue by ldreux** [mallowigi/material-theme-issues#500]
### Describe the feature

When centered editor is active, center the text in the full window and not only in the editor zone to avoid the code move to left or right when the developer open or resize tool windows.

### Use Cases

As a developer working in zen mode, I prefer to work without any tool window opened. Sometimes, I need to navigate in the tree or open a database so I open the Project / Database tool window, and close theme some times later.

With centered editor active, the code move to the left or to the right at the tool window opening and closing. It's a distraction in opposition of the zen mode concept.

I changed the window mode for tools window to Undock to avoid this behavior but sometimes I need to let dialog tools opened when I code.

### Material Theme Version

v9.2.0

### IDE

Other (AppCode, CLion, GoLang...)

**Comment by mallowigi** [comment]
Impossible. If you want to achieve such a feat simply run the action "Undock tool windows"

**Comment by mallowigi** [comment]
FYI this is consistent to how VSCode implemented centered editors as well

**Comment by mallowigi** [comment]
Just want to point out something: this is not something I implemented, I'm just reusing what zen mode and distraction free mode already did, but more conveniently. Hence why this feature is included in the free mode.

Maybe if in the future they are exposing endpoints for further customization, like for example to control the width of the center column, or disabling it for certain projects or file types, etc. But currently it's just bare bones. Maybe one day they'll open that mode for everyone too, like VSC did.
