### ISSUE TITLE
How to change color

### ISSUE THREAD

**Issue by changshunxu520** [mallowigi/material-theme-issues#503]
### Describe the bug

When I use Project Title Bar Application Frame 
Colorize Title Bar(New UI only)\Colorize Left Tool Window(New UI only) ....
Item shows a color，But I don’t like this color, how can I change it?
![Snipaste_2024-04-26_15-19-25](https://github.com/mallowigi/material-theme-issues/assets/16171624/90da158d-194b-4938-aa8f-9bccaa62679c)
![Snipaste_2024-04-26_15-22-03](https://github.com/mallowigi/material-theme-issues/assets/16171624/498ac7bf-8953-4789-a831-d66315eaa152)

### To Reproduce

nothing to offer

### Expected behavior

nothing to offer

### Material Theme Version

V9.0.0

### IDE

IntelliJ IDEA, WebStorm, DataGrip

**Comment by mallowigi** [comment]
Please use the discussions tab to ask questions
