### ISSUE TITLE
[Feature]: revert a new appearance of the sliders

### ISSUE THREAD

**Issue by hurvajs77** [mallowigi/material-theme-issues#504]
### Describe the feature

Revert a new look of the sliders... It's horrible, ugly and totally unfriendly... 🥲🤮. Or at least display the scrollbar value. If I wanna set precise value, I'm fucked.
<img width="847" alt="image" src="https://github.com/mallowigi/material-theme-issues/assets/5896950/34c46a27-3417-4734-814c-abd7c4ebda9e">

### Use Cases

always and everywhere

### Material Theme Version

9.2.1

### IDE

IntelliJ IDEA, WebStorm, PHPStorm, Rider, PyCharm, DataGrip

### System Info

```shell
JetBrains Rider 2024.1.1

Build #RD-241.14494.325, built on April 16, 2024

Licensed to xxxxxx
You have a perpetual fallback license for this version.
Subscription is active until xxxxxx

Runtime version: 17.0.10+8-b1207.12 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

.NET Core v8.0.1 ARM64 (Server GC)
```

**Comment by mallowigi** [comment]
No, sorry.
