### ISSUE TITLE
[Bug]: UI/UX of WebStorm severely impacted by enabling plugin

### ISSUE THREAD

**Issue by RavenHursT** [mallowigi/material-theme-issues#508]
### Describe the bug

Enabling this plugin, or your other "Atom Material Icons" plugin, causes severe UI/UX performance problems.

Details can be found here in JetBrains' issue tracker where the bug was first introduced: 

https://youtrack.jetbrains.com/issue/WEB-66851/Keystrokes-in-latest-ver-of-WebStorm-SEVERELY-delayed#focus=Comments-27-9785255.0-0

### To Reproduce

See JetBrains issue for details: https://youtrack.jetbrains.com/issue/WEB-66851/Keystrokes-in-latest-ver-of-WebStorm-SEVERELY-delayed#focus=Comments-27-9785255.0-0

### Expected behavior

Shouldn't impact IDE performance

### Material Theme Version

v9.2.1

### IDE

WebStorm

### System Info

```shell
WebStorm 2024.1.2
Build #WS-241.15989.105, built on April 23, 2024
Runtime version: 17.0.10+1-b1207.14 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 19088M
Cores: 16
Metal Rendering is ON
Registry:
  ide.balloon.shadow.size=0
  debugger.new.tool.window.layout=true
  ide.intellij.laf.enable.animation=true
  ide.new.editor.tabs.vertical.borders=true
  ide.animate.toolwindows=true
  ide.experimental.ui=true
  ide.editor.tab.selection.animation=true
Non-Bundled Plugins:
  ru.adelf.idea.dotenv (2024.1)
  com.github.copilot (1.5.2.5345)
  mobi.hsz.idea.gitignore (4.5.3)
  izhangzhihao.rainbow.brackets (2024.2.3-241)
  com.chrisrm.idea.MaterialThemeUI (9.2.1)
  zielu.gittoolbox (500.2.7+233)
```

### Logs/Screenshots

```shell
See linked ticket
```

**Comment by RavenHursT** [comment]
Looks seemingly related: https://github.com/mallowigi/a-file-icon-idea/issues/449#issuecomment-2096548467

**Comment by mallowigi** [comment]
can you provide a repository? I have heard many people complaining about performance issues but I am not able to reproduce (and I'm using my plugin every day with projects with lots of files)

**Comment by RavenHursT** [comment]
So.. I take it that's means you're not fixing this? 🤔

I was going to look into providing reproduction steps.. just didn't have time this week.

**Comment by mallowigi** [comment]
No, I am not able to reproduce, even using other peoples' setup.

There is another issue open in the atom plugin regarding performance, please use this thread, maybe there will be developments on how to find the culprit.

**Comment by RavenHursT** [comment]
@mallowigi you're talking about, https://github.com/mallowigi/a-file-icon-idea/issues/449 ?

**Comment by mallowigi** [comment]
Yes
