### ISSUE TITLE
[Feature]: Enlarge spacing in case custom spacing

### ISSUE THREAD

**Issue by hurvajs77** [mallowigi/material-theme-issues#513]
### Describe the feature

I use custom spacing settings for the most elements, file tree and compact items. That's great correctly, but when I'm entering into Presentation Mode, the spacing isn't reflect font size change and the most of controls, tree are ugly. 

Normal view and files explorer:
![image](https://github.com/mallowigi/material-theme-issues/assets/5896950/cd150bdd-cc4a-4bc7-8d7c-18c19f54202c)

Normal view and controls (it looks OK except controls for sliders, I'm OK with that)
![image](https://github.com/mallowigi/material-theme-issues/assets/5896950/f3f7e920-8d9c-4d5d-a03c-cd606cd3c18a)

**But there is a problem...**
Presentation mode with file explorer:
![image](https://github.com/mallowigi/material-theme-issues/assets/5896950/8d69021e-5388-4214-ae8a-84d034a1d5b4)

and controls in presentation view:
![image](https://github.com/mallowigi/material-theme-issues/assets/5896950/a50ab846-e250-4bb6-b4ef-eee276b07b84)

and last one, presentation mode with:
![image](https://github.com/mallowigi/material-theme-issues/assets/5896950/8e7b1c87-f0b9-49eb-aa49-4bde98031a78)

### Material Theme Version

v9.2.1

### IDE

WebStorm, PHPStorm, Rider, PyCharm, DataGrip

### System Info

```shell
* macOS
* Material Theme plugin v9.2.1
* WebStorm v2024.1.2 (Build #WS-241.15989.105, built on April 23, 2024)
  - generally the same result is in the most JetBrains IDEs
```

**Comment by mallowigi** [comment]
There are a few issues regarding different scales when using the plugin (see [https://github.com/mallowigi/material-theme-issues/issues/381](https://github.com/mallowigi/material-theme-issues/copy_sidebar_url)). I suppose this is one of them.

I'll get to it eventually, but know that as this would require major changes to the plugin structure, this will not happen in the near future, as I have other priorities and my time working on the plugin is scarce.

I'll close this as duplicate.
