### ISSUE TITLE
[Bug]: Matherial darker theme keywords inside blocks color bug 

### ISSUE THREAD

**Issue by AlexandrDobrovolskiy** [mallowigi/material-theme-issues#514]
### Describe the bug

All keywords inside code blocks are highlighted as unused (grey) on Material Darker theme 
<img width="975" alt="image" src="https://github.com/mallowigi/material-theme-issues/assets/23122290/8a56d0e3-292c-484c-9ba0-a1f782fa8924">
<img width="784" alt="image" src="https://github.com/mallowigi/material-theme-issues/assets/23122290/09422b18-8242-4777-a67d-a1b951db9cd6">

### To Reproduce

1. Set Material darker theme 
2. Open any js file
3. 1st scope level keywords color is correct but all keywords (like `const` or `return`) are same color as comments 

### Expected behavior

All keywords color correct

### Material Theme Version

v9.2.1

### IDE

WebStorm

### System Info

```shell
WebStorm 2024.1.2
Build #WS-241.15989.105, built on April 23, 2024
Licensed to Alexandr Dobrovolskiy
Subscription is active until December 27, 2024.
Runtime version: 17.0.10+1-b1207.14 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.2.1
GC: G1 Young Generation, G1 Old Generation
Memory: 8064M
Cores: 10
Metal Rendering is ON
Registry:
  ide.balloon.shadow.size=0
  ide.new.editor.tabs.vertical.borders=true
  ide.animate.toolwindows=true
  ide.editor.tab.selection.animation=true
Non-Bundled Plugins:
  ru.adelf.idea.dotenv (2024.1)
  com.intellij.ml.llm (241.15989.156)
  com.chrisrm.idea.MaterialThemeUI (9.2.1)
  com.mallowigi (96.0.0)

Apple M1 Max
MacOS 14.2.1 (23C71)
```

### Logs/Screenshots

```shell
Couldn't append a screenshot in this field please check the description
```

**Comment by mallowigi** [comment]
Looks similar to this: https://github.com/mallowigi/material-theme-issues/issues/377

Please check the solutions described there

**Comment by AlexandrDobrovolskiy** [comment]
@mallowigi I have no duplicated color schemes 
tried change/restart/import settings nothing helped yet

**Comment by mallowigi** [comment]
Try to delete the color schemes from the file system directly: find your config directory and delete the color schemes that start with "@user_" (do this when the ide is closed)
