### ISSUE TITLE
[Bug]: Centered editor does not work with .rs (rust) files.

### ISSUE THREAD

**Issue by MihaelBercic** [mallowigi/material-theme-issues#515]
### Describe the bug

While the centered editor does work with other files such as typescript and javascript, it does not work with rust files (.rs).

### To Reproduce

1. Enable centered feature
2. Open .rs file
3. Open .ts file
4. See the difference.

### Expected behavior

The expected behaviour would be centered code.

### Material Theme Version

v9.0.0

### IDE

Other (AppCode, CLion, GoLang...)

### System Info

```shell
RustRover 2024.1 EAP
Build #RR-241.15989.180, built on May 6, 2024
Licensed to RustRover EAP user: {USER}
Expiration date: July 5, 2024
Runtime version: 17.0.10+1-b1207.14 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Metal Rendering is ON
Registry:
  ide.balloon.shadow.size=0
  editor.distraction.free.mode=true
  documentation.show.toolbar=true
  ide.new.editor.tabs.vertical.borders=true
  ide.animate.toolwindows=true
  ide.experimental.ui=true
  ide.editor.tab.selection.animation=true
  transferSettings.vscode.onlyCargoToml=true
  llm.ai.assistant.toolwindow.activation.on.start=false
  org.toml.json.schema=false
  terminal.new.ui=true
Non-Bundled Plugins:
  com.chrisrm.idea.MaterialThemeUI (9.2.1)
  com.mallowigi (96.0.0)
```

**Comment by mallowigi** [comment]
Are rust files centered when you toggle the native "Zen Mode"?

**Comment by MihaelBercic** [comment]
> Are rust files centered when you toggle the native "Zen Mode"?

No sir, they are not.

**Comment by mallowigi** [comment]
There you have it. Please open an issue in JetBrains YouTrack
