### ISSUE TITLE
[Bug]: (Rider) Text does not fit in NuGet search bar

### ISSUE THREAD

**Issue by jorgeparavicini** [mallowigi/material-theme-issues#519]
### Describe the bug

When searching for something in the NuGet search bar in Rider the text does not fit and the bottom gets cut.
![image](https://github.com/mallowigi/material-theme-issues/assets/24812622/31ddbebe-97f5-4cf2-8199-09eb86a2fdb0)

### To Reproduce

1. Install Rider
2. Install Material Theme UI
3. Use the GitHub Dark theme
4. Got to NuGet tab
5. Search for something

### Expected behavior

Have a search bar with the text fully visible

### Material Theme Version

v9.3.1

### IDE

Rider

### System Info

```shell
JetBrains Rider 2024.1.2
Build #RD-241.15989.179, built on May 6, 2024
Runtime version: 17.0.10+1-b1207.14 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.5
.NET Core v8.0.1 ARM64 (Server GC)
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 12
Metal Rendering is ON
Registry:
  ide.balloon.shadow.size=0
  ide.new.editor.tabs.vertical.borders=true
  ide.animate.toolwindows=true
  ide.experimental.ui=true
  ide.editor.tab.selection.animation=true
  ide.new.project.model.index.case.sensitivity=true
Non-Bundled Plugins:
  com.intellij.resharper.HeapAllocationsViewer (2024.1.0)
  org.intellij.plugins.hcl (241.15989.49)
  verify-rider (2024.1.0-eap01)
  com.intellij.plugins.riderkeymap (201.6251.22)
  eu.gillissen.rider.usersecrets (1.2.0)
  Key Promoter X (2024.1.0)
  com.intellij.resharper.StructuredLogging (2024.1.0.323-eap01)
  ru.adelf.idea.dotenv (2024.1)
  com.intellij.ml.llm (241.15989.195)
  com.chrisrm.idea.MaterialThemeUI (9.2.1)
  com.github.copilot (1.5.4.5571)
  com.mallowigi (97.0.0)
  com.intellij.resharper.azure (3.50.0.1773-2024.1)
```

**Comment by mallowigi** [comment]
Sorry, Rider is not easy to debug. And since this is a very minor issue, I'd rather not invest time and effort on this. You can still see the contents.

**Comment by matkoch** [comment]
I can't give an ETA, but I filed this in our issue tracker:

https://youtrack.jetbrains.com/issue/RIDER-125636

Fingers crossed someone can take a look at it eventually 🤞
