### ISSUE TITLE
[Bug]: Add `./.idea/material_theme_project_new.xml` file to `./.idea/.gitignore`

### ISSUE THREAD

**Issue by mykolasolodukha** [mallowigi/material-theme-issues#521]
### Describe the bug

The file `material_theme_project_new.xml` keeps getting added to Git. It has the `userId` parameter, which might not be exactly what one wants to share in e.g. an open source project.

### To Reproduce

Migrate.

### Expected behavior

The `material_theme_project_new.xml` file should be added to `./.idea/.gitignore`, so that it's safely ignored by the VCS.

### Material Theme Version

v9.3.1

### IDE

IntelliJ IDEA

**Comment by mallowigi** [comment]
The plugin cannot adds itself to a gitignore file. This is something that must be done manually by developers.
