### ISSUE TITLE
[Bug]: "Reset" buttons on "Custom Theme" and child "Light Custom theme" views have no apparent effect

### ISSUE THREAD

**Issue by Lootwig** [mallowigi/material-theme-issues#523]
### Describe the bug

After interacting with the custom theme tab but closing the settings dialog without applying any changes, the settings dialog now flags a custom theme as "configured" after merely _visiting_ the tab, and pops up a modal.

On both tabs, clicking the "Reset" button in the corner does not have any effect on this.

### To Reproduce

1. Using a non-custom theme, visit the custom theme settings tab and change some values
2. Leave dialog without applying theme
3. Open settings again, visit custom theme tab, note "apply" button becomes active
4. Hit reset

### Expected behavior

- Merely having opened the tab should not create a prompt when making changes elsewhere
- "Reset" should include resetting whatever leftover data counts as having configured a custom theme

### Material Theme Version

9.3.1

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2024.1.2 (Ultimate Edition)
Build #IU-241.17011.79, built on May 22, 2024
Licensed to David Schneider
You have a perpetual fallback license for this version.
Subscription is active until September 28, 2025.
Runtime version: 17.0.11+1-b1207.24 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 24
Registry:
  ide.balloon.shadow.size=0
  ide.new.editor.tabs.vertical.borders=true
  ide.animate.toolwindows=true
  ide.experimental.ui=true
  ide.editor.tab.selection.animation=true
  terminal.new.ui=true
  eslint.additional.file.extensions=svelte
Non-Bundled Plugins:
  net.prestalife.svirtual (1.5.3)
  de.nordgedanken.auto_hotkey (0.10.4)
  org.antlr.intellij.plugin (1.23.1)
  com.jetbrains.space (241.17011.48)
  com.intellij.aqua (241.17011.127)
  net.ashald.envfile (3.4.2)
  com.intellij.ml.llm (241.17011.2)
  com.mallowigi (97.0.0)
  mobi.hsz.idea.gitignore (4.5.3)
  dev.blachut.svelte.lang (241.17011.2)
  org.jetbrains.android (241.17011.79)
  com.chrisrm.idea.MaterialThemeUI (9.3.1)
  zielu.gittoolbox (500.2.9+233)
Kotlin: 241.17011.79-IJ
```

### Logs/Screenshots

```shell
https://github.com/mallowigi/material-theme-issues/assets/39827040/366c480a-7bae-44f2-a62e-b79a7dbef377
```

**Comment by mallowigi** [comment]
Thanks for reporting. If I understood correctly, the problem is that after you change the custom theme, upon clicking Cancel you are not restored to the values before the changes, and also when pressing reset.

I've managed to fix the first issue, so now you'll be able to undo your changes by pressing cancel. However I couldn't make the Reset button do the same, as this breaks a lot of functionalities. 

The fix will be available on the next release.
