### ISSUE TITLE
[Bug]: Notifications from Material Theme UI plugin are shown in Japanese

### ISSUE THREAD

**Issue by jreznot** [mallowigi/material-theme-issues#526]
### Describe the bug

Hi, please take a look at the bug we discovered in the last EAP versions

[IJPL-156716](https://youtrack.jetbrains.com/issue/IJPL-156716)

### To Reproduce

1. Install Material theme UI plugin in IntelliJ IDEA 2024.2 EAP
2. Restart
3. Observe notifications in Japanese

### Expected behavior

English locale should be used.

API `com.intellij.DynamicBundle#getLocale` enables plugins to access the Locale used by user

### Material Theme Version

9.4.0

### IDE

IntelliJ IDEA

**Comment by jreznot** [comment]
![image](https://github.com/mallowigi/material-theme-issues/assets/1066152/85da6d21-a197-4acc-8b81-9083f1b9201b)

**Comment by mallowigi** [comment]
Umm, do you have the japanese plugin installed?

**Comment by jreznot** [comment]
Since 2024.2 JetBrains IDEs have ZH, JA, KO locales bundled with IDEs

**Comment by mallowigi** [comment]
![CleanShot 2024-06-21 at 21 58 52@2x](https://github.com/mallowigi/material-theme-issues/assets/5015756/a241f8fd-cc41-4650-ae10-4a3a3bd6ed50)

Oh wow. I need to fix that ASAP...

**Comment by jreznot** [comment]
API `com.intellij.DynamicBundle#getLocale` enables plugins to access the Locale used by user

**Comment by mallowigi** [comment]
I've disabled support for 2024.2 EAP. I don't have the time at the moment to handle the new API. Thanks for reporting.

**Comment by jreznot** [comment]
We would be glad if you had time before the release to change it, it will happen aprox in the end of July

**Comment by xsy420** [comment]
temporally fix:
1. unzip the material-theme-jetbrains-9.4.0-instrmented.jar
2. change the *_ja.properties file in message dir to *.properies file
3. in the material-theme-jetbrains-9.4.0-instrmented directory, run
```shell
jar -cvf ../material-theme-jetbrains-9.4.0-instrmented.jar *
```
4. replace the material-theme-jetbrains-9.4.0-instrmented.jar
