### ISSUE TITLE
collapse from bottom 

### ISSUE THREAD

**Issue by Igor2122** [mallowigi/material-theme-issues#527]
### Describe the feature

we have the option to collapse code blocks from top which is very useFull
it will be also nice to be able to do the same bottom up

i find myself manytimes scrolling code from bottom up and wishing i had an option to collapse blocks this way 
plz look into this :) 

<img width="1381" alt="Screenshot 2024-07-03 at 7 38 39" src="https://github.com/AtomMaterialUI/material-theme-issues/assets/28155685/9885e495-19f8-42e5-9b38-d27f7ff511fc">

### Material Theme Version

v.7.0

### IDE

WebStorm

**Comment by mallowigi** [comment]
It's already available natively on the IDE:

![CleanShot 2024-07-03 at 15 23 47](https://github.com/AtomMaterialUI/material-theme-issues/assets/5015756/c0fc5449-ef55-4f0b-9d32-fef2b60e9abf)
