### ISSUE TITLE
[Bug]: Issues with side panels and menu bar

### ISSUE THREAD

**Issue by drew887** [mallowigi/material-theme-issues#528]
### Describe the bug

For some reason the side panels and menu bar are stuck being weird colours. The actual code window and highlighting seems fine its just the side panel and menu bar are always the wrong colour when selecting a theme. 

I've tried with auto reset on and off and strangely what colour it gets stuck on is different based on what project I have open. I've tried nuking the .idea folder after closing the ide and reopening but the issue remains and is the same colour so I'm not sure what/where else project specific config could be for the plugin.  

The issue is also not limited to one ide, I have Phpstorm, Goland, Pycharm, Rider, and CLion for my work and they all have the same issue present. The colour they get stuck on is also the same per project. This also happened before updating phpstorm to `2024.1.4 Build #PS-241.18034.69`, but is still present after updating to that version. (I didn't get the version before updating today assuming that the update would hopefully fix the issue) 

I have had this issue happen once before, right after I upgraded to the paid version of the plugin, however that time was fixed by simply enabling the auto reset color scheme option, which this time seems to have not fixed it :shrug: 

### To Reproduce

I am not sure how to reproduce, all I did was open the ide today and the issue is present. Was fine yesterday, it's just today that it's all wonky.  Opening any project old or new on this machine causes the symptoms. 

### Expected behavior

Colours change with the selected theme 

### Material Theme Version

9.3.1

### IDE

PHPStorm, Rider, PyCharm, Other (AppCode, CLion, GoLang...)

### System Info

```shell
PhpStorm 2024.1.4
Build #PS-241.18034.69, built on June 21, 2024
Licensed to Andrew Mcdonald
Subscription is active until July 26, 2024.
Runtime version: 17.0.11+1-b1207.24 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.0-25-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 4000M
Cores: 20
Registry:
  ide.balloon.shadow.size=0
  debugger.watches.in.variables=false
  debugger.new.tool.window.layout=true
  run.processes.with.pty=TRUE
  ide.new.editor.tabs.vertical.borders=true
  ide.experimental.ui=true
  ide.editor.tab.selection.animation=true
Non-Bundled Plugins:
  org.toml.lang (241.17011.8)
  com.jetbrains.darkPurpleTheme (1.3)
  IdeaVIM (2.13.1)
  com.arcticicestudio.nord.jetbrains (0.13.0)
  dev.thull.polar (1.0.5)
  com.intellij.kubernetes (241.18034.4)
  com.chrisrm.idea.MaterialThemeUI (9.3.1)
  com.mallowigi (97.0.0)
Current Desktop: i3
```

### Logs/Screenshots

Here's volcano on an example project in phpstorm
![volcano but blue](https://github.com/AtomMaterialUI/material-theme-issues/assets/2347730/7cb86d73-7c7d-442e-86c0-2118d8bb4a16)

Here's volcano on a private project (certain details blocked out with red to hide work related stuff)
![PHPSTORM-material-volcano_PRIVATE_PROJECT_stuck-blue](https://github.com/AtomMaterialUI/material-theme-issues/assets/2347730/23023379-29f0-465e-b4bd-9dd912978355)
And here's that same project but swapped to material sandy beach
![PHPSTORM-material-sandy-beach_PRIVATE_PROJECT_stuck-lavender](https://github.com/AtomMaterialUI/material-theme-issues/assets/2347730/a0f703fe-ad30-4a50-9758-9d37e9e4c548)

**Comment by mallowigi** [comment]
Is it happening on the latest version or is it in all versions?

**Comment by drew887** [comment]
It was present on the version I had before 2024.1.4, and it is still present now in 2024.1.4 for all the tools that I use:

- Clion
- PHPStorm
- Goland
- Rider
- Pycharm

I don't have the version I was on before 2024.1.4 as I foolishly assumed the issue was caused by me being out of date, it was only after it was still present post updating that I thought to grab version numbers for a bug report.

**Comment by mallowigi** [comment]
I see you're using Linux. It could be an issue with the Linux build. Can you turn off the "Colorize Title Bar" and see if it reproduces?

**Comment by drew887** [comment]
Hey that worked! With all 4 options off it now looks correct. Thank you so much!

EDIT: Confirmed it works with all 5 of the ide's I use as long as those the colorize options are off

![PHPSTORM-volcano-working](https://github.com/user-attachments/assets/4351eb2e-da66-49bb-9c60-a716155c40d3)

**Comment by mallowigi** [comment]
Yeah, that's what I thought... This issue happened in the past, and I fixed it, but it looks like they changed the selectors again or something, and of course, just in Linux.

I'll try to reproduce the issue myself as soon as I can find a Linux machine

**Comment by mallowigi** [comment]
I am on Ubuntu right now, 2024.1 and I am not able to reproduce...

**Comment by drew887** [comment]
I don't know what to tell ya there, I'm on Ubuntu as well, 2024.1.4 and toggling the Colorize options on and off consistently brings back and then fixes this issue.

##### Off, looks correct
![colorize-off-working](https://github.com/user-attachments/assets/9c9b1077-d57f-4cce-b585-4d1286f1087f)

##### On, broken
![colorize-on-not-working](https://github.com/user-attachments/assets/cbaff01b-ade3-4df6-8808-7b5cd867c312)

**Comment by mallowigi** [comment]
Could it be some other setting? Can you try with factory defaults and tell me if it reproduces? IF you're using JetBrains Toolbox, you can switch the configuration folder easily as it sets a property in the vmoptions.
