### ISSUE TITLE
[Bug]: WS-233.15325.18 

### ISSUE THREAD

**Issue by NsdHSO** [mallowigi/material-theme-issues#529]
### Describe the bug

Plugin 'Material Theme UI' (version '9.3.1') is not compatible with the current version of the IDE, because it requires build 241.13688.10 or newer but the current build is WS-233.15325.18

### To Reproduce

1. Update WS to latest version 
2. And you will see all your staff will be gone

### Expected behavior

I want to have latest feature from WS but to not lose the config of material theme

### Material Theme Version

9.3.1

### IDE

WebStorm

### System Info

```shell
WebStorm 2023.3.7
Build #WS-233.15325.18, built on June 4, 2024
Runtime version: 17.0.10+1-b1087.23 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.5
GC: G1 Young Generation, G1 Old Generation
Memory: 4048M
Cores: 12
Metal Rendering is ON
```

**Comment by mallowigi** [comment]
How did you install 9.3.1 on Webstorm 2023 ?

**Comment by NsdHSO** [comment]
> How did you install 9.3.1 on Webstorm 2023 ?
I do not know :)))

maybe can be the first time when I installed webstorm on this MAC?

**Comment by NsdHSO** [comment]
I solve this issue:
1. Download latest version of webstorm 
2. Installed 
3. Replace.

But is strange @mallowigi because I update every when webstorm update something

**Comment by mallowigi** [comment]
The version 9.3.1 should not be available for these versions of the IDE.
