### ISSUE TITLE
[Bug]: Project Title Bar Widget settings don't have any effect

### ISSUE THREAD

**Issue by phalverson** [mallowigi/material-theme-issues#533]
### Describe the bug

When the Intellij "New UI" is active, a control labelled "Project Title Bar Widget" appears in the center of the uppermost window service, regardless of whether the "Enable Project Title Bar" setting is checked or unchecked.

Further, selecting any of the "Change title to ..." items on the pull down has no effect on the control text.

![Screen Shot 2024-08-01 at 4 37 30 PM](https://github.com/user-attachments/assets/d0487c53-bee3-4101-9afb-b08b5e23d573)
![Screen Shot 2024-08-01 at 4 35 21 PM](https://github.com/user-attachments/assets/808e0cb2-6ac8-4a1b-96bd-eb8fd69628f4)
![Screen Shot 2024-08-01 at 4 43 09 PM](https://github.com/user-attachments/assets/a56620cf-f1ec-42a6-8624-5db69fb639ff)

### To Reproduce

1. Open preferences/settings
2. Verify "Enable Project Title Bar" setting is unchecked
3. Click on title bar widget
4. Select any of the "Change title to ..." items

### Expected behavior

title bar shouldn't appear unless setting is checked.
title bar text should change based on project context and title bar content selection.

### Material Theme Version

v9.3.1

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2024.1.4 (Ultimate Edition)
Build #IU-241.18034.62, built on June 20, 2024
Licensed to Peter Halverson
Subscription is active until August 6, 2024.
Runtime version: 17.0.11+1-b1207.24 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.7.5
Jenkins Plugin 0.13.20-2023.2
GC: G1 Young Generation, G1 Old Generation
Memory: 3000M
Cores: 10
Metal Rendering is ON
Registry:
  ide.balloon.shadow.size=0
  debugger.watches.in.variables=false
  ide.new.editor.tabs.vertical.borders=true
  light.edit.file.open.enabled=false
  ide.animate.toolwindows=true
  ide.experimental.ui=true
  ide.editor.tab.selection.animation=true
Non-Bundled Plugins:
  com.jetbrains.plugins.ini4idea (241.18034.82)
  org.logtalk (1.0.15)
  org.intellij.plugins.hcl (241.17890.8)
  aws.toolkit.core (3.20-241)
  org.elasticsearch4idea (2024.1.2-241)
  com.andrewbrookins.wrap_to_column (1.8.0)
  org.jetbrains.settingsRepository (241.15989.9)
  com.perl5 (2024.1)
  com.intellij.plugins.watcher (241.14494.150)
  com.github.mikesafonov.jenkins-linter-idea-plugin (0.6.0)
  com.intellij.ideolog (222.3.2.0)
  com.markskelton.one-dark-theme (5.11.0)
  name.kropp.intellij.makefile (241.14494.150)
  ir.msdehghan.plugins.ansible (0.92)
  dev.meanmail.plugin.nginx-intellij-plugin (2024.3)
  org.jetbrains.plugins.go (241.17011.2)
  Pythonid (241.18034.62)
  com.intellij.python.django (241.18034.55)
  Jenkins Control Plugin (0.13.20-2023.2)
  pro.bashsupport (4.2.2.241)
  org.asciidoctor.intellij.asciidoc (0.42.2)
  JUnit4-Parallel-Runner (1.5)
  net.seesharpsoft.intellij.plugins.csv (3.3.0-241)
  com.intellij.ml.llm (241.18034.12)
  com.dmarcotte.handlebars (241.14494.150)
  mobi.hsz.idea.gitignore (4.5.3)
  org.sonarlint.idea (10.7.0.78874)
  me.aristotll.python.typing.adder (1.1)
  com.chrisrm.idea.MaterialThemeUI (9.3.1)
  ru.meanmail.plugin.django_command_runner (2022.1)
  ru.adelf.idea.dotenv (2024.1)
  zielu.gittoolbox (500.2.12+233)
  aws.toolkit (3.20-241)
  artsiomch.cmake (241.1.1)
Kotlin: 241.18034.62-IJ
```

### Logs/Screenshots

```shell
didn't see anything in the IDEA log
```

**Comment by mallowigi** [comment]
It's not a bug, it's written in the settings:
![CleanShot 2024-08-03 at 22 22 01](https://github.com/user-attachments/assets/49cbdc58-d69f-4c11-b9e0-fcbb00fd8362)

The Project Title Widget is not controllable by the settings, but by the "Customize Toolbar". 

And the dropdown options are replacing the text that is shown there - but only if you had selected "Customize Text", otherwise it would always go back to the hardcoded default text.

Agreed, this should probably be affecting the value independently of the checkbox, or be disabled if the option is unchecked.

EDIT: Actually it's not the case, it automatically enables the "customize text" upon click, so I'm not sure what you're experiencing.

**Comment by xc1112** [comment]
Display the project icon and the project title. If either of them is closed, the project title bar will become invalid
