### ISSUE TITLE
[Bug]: New rounded tabs option is missing

### ISSUE THREAD

**Issue by apb-hello-world** [mallowigi/material-theme-issues#540]
### Describe the bug

The latest update says you can turn on rounded tab buttons (similar to Chrome) in Material Theme UI -> UI Components, but the setting appears to be missing.

### To Reproduce

1. Go to settings
2. Go to Appears & Behavior
3. Go to Material Theme UI
4. Go to UI Components
5. Expand all the options

### Expected behavior

There should be a setting to turn this feature on and off.

### Material Theme Version

9.5.0

### IDE

WebStorm

### System Info

```shell
WebStorm 2024.2.1
Build #WS-242.21829.149, built on August 29, 2024
Licensed to [removed]
Subscription is active until April 11, 2025.
Runtime version: 21.0.3+13-b509.11 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 11.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4054M
Cores: 20
Registry:
  ide.balloon.shadow.size=0
  editor.distraction.free.mode=true
  editor.focus.mode.color.light=464b5d
  editor.focus.mode.color.dark=464b5d
  suggest.all.run.configurations.from.context=true
  ide.new.editor.tabs.vertical.borders=true
  ide.animate.toolwindows=true
  ide.experimental.ui=true
  ide.editor.tab.selection.animation=true
  i18n.locale=
Non-Bundled Plugins:
  Batch Scripts Support (1.0.13)
  labs.hardhacker.theme.jetbrains (0.2.6)
  com.villains.intelij.plugin.trashpandatheme (1.6)
  com.dubreuia.tool (2.6.4)
  com.jetbrains.space (242.21829.142)
  com.jinsihou.react.snippets (1.1.1)
  com.markskelton.one-dark-theme (5.11.0)
  com.bluewaitor.tsReact (1.4.0)
  com.intellij.plugin.adernov.powershell (2.7.0)
  ru.adelf.idea.dotenv (2024.2.1)
  com.intellij.ml.llm (242.21829.196)
  org.jetbrains.plugins.gitlab (242.21829.162)
  org.jetbrains.plugins.github (242.21829.162)
  org.intellij.prisma (242.21829.3)
  com.chrisrm.idea.MaterialThemeUI (9.5.0)
  com.mallowigi (97.0.0)
  com.github.hugohomesquita.htmxjetbrains (0.0.10)
```

**Comment by mallowigi** [comment]
I can reproduce, I might have reverted the change by mistake.

In any case this feature needs rework, I'm not really content with it at the current state. 

Sorry for the troubles

**Comment by mallowigi** [comment]
[Material Theme UI-9.5.1.zip](https://github.com/user-attachments/files/16968833/Material.Theme.UI-9.5.1.zip)

Here, have at it. 

I can't upload new versions for now as I need to figure out what to do in accordance to new marketplace rules...

**Comment by mallowigi** [comment]
I just checked now, and the option is there, but on the Tabs Section
