### ISSUE TITLE
[Bug]: Material Theme UI is in Japanese language!

### ISSUE THREAD

**Issue by Lukasss93** [mallowigi/material-theme-issues#541]
### Describe the bug

![immagine](https://github.com/user-attachments/assets/a3540ec3-4585-44ce-8323-51e1a827c92d)

![immagine](https://github.com/user-attachments/assets/2c3dca63-cb80-4e9f-a0b4-9a68e96762c5)

### To Reproduce

1. Open settings
2. Go to Material Theme UI settings

### Expected behavior

English language

### Material Theme Version

9.5.0

### IDE

PHPStorm

### System Info

```shell
PhpStorm 2024.2.1
Build #PS-242.21829.154, built on August 29, 2024
Runtime version: 21.0.3+13-b509.11 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 11.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4096M
Cores: 16
Registry:
  ide.balloon.shadow.size=0
  debugger.watches.in.variables=false
  vcs.log.index.enable=true
  run.processes.with.pty=TRUE
  ide.new.editor.tabs.vertical.borders=true
  ide.animate.toolwindows=true
  ide.ui.new.file.chooser=true
  ide.editor.tab.selection.animation=true
  i18n.locale=
Non-Bundled Plugins:
  com.chrisrm.idea.MaterialThemeUI (9.5.0)


(It happens on ubuntu too)
```

### Logs/Screenshots

```shell
See the "Describe the bug" section.
```

**Comment by stevium** [comment]
Same here with Rider and Intelij on MacOs

**Comment by mallowigi** [comment]
I can't reproduce, can you share your plugins ?

**Comment by Lukasss93** [comment]
> I can't reproduce, can you share your plugins ?

PhpStorm 2024.2.1
Build #PS-242.21829.154, built on August 29, 2024
Licensed to [REDACTED]
Subscription is active until [REDACTED].
Runtime version: 21.0.3+13-b509.11 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 11.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4096M
Cores: 16

<details>
<summary>Registry</summary>

- ide.balloon.shadow.size=0
- debugger.watches.in.variables=false
- vcs.log.index.enable=true
- run.processes.with.pty=TRUE
- ide.new.editor.tabs.vertical.borders=true
- ide.animate.toolwindows=true
- ide.ui.new.file.chooser=true
- ide.editor.tab.selection.animation=true
- i18n.locale=
- terminal.new.ui=true
- vue.language.server.default.version=2.1.6
- eslint.additional.file.extensions=svelte

</details>

<details>
<summary>Non-Bundled Plugins</summary>

- com.intellij.datagen (242.20224.159)
- com.intellij.classic.ui (242.20224.159)
- com.github.patou.gitmoji (2.1.0)
- in.thekalinga.snippet.intellij (6.1.0)
- com.github.leomillon.uuidgenerator (4.5.1)
- de.lostmekka.important-files-idea-plugin (0.0.5)
- net.sjrx.intellij.plugins.systemdunitfiles (223.240911.249)
- io.github.orangain.prettyjsonlog (0.4.0)
- com.marcherdiego.json.visualizer (1.0.0)
- com.nasller.CodeGlancePro (1.9.0)
- cn.memoryzy.json (1.6.0)
- com.jetbrains.ide.streamdeck (2024.2.0)
- com.andrey4623.rainbowcsv (2.0.2)
- com.github.mokkapps.codesnapintellijextension (1.0.4)
- quokka.js (1.0.454)
- com.mroche.JsonHelper (1.3.2)
- org.OverEngineer.InlineProblems (0.5.3)
- com.vladislav-og.color-palette-generator (1.2)
- com.intellij.ideolog (242.21829.162)
- de.ehmkah.projects.imgdiff (1.11.0)
- com.intellij.properties (242.20224.155)
- com.wix.sasslint (1.1.3)
- digital.pedda.loremIpsum (1.1)
- String Manipulation (9.14.1)
- dev.meanmail.plugin.nginx-intellij-plugin (2024.3)
- com.intellij.mermaid (0.0.22+IJ.232)
- org.jetbrains.plugins.gitlab (242.21829.162)
- org.jetbrains.plugins.github (242.21829.162)
- com.github.yunabraska.githubworkflowplugin (2024.2.0)
- Gitflow-Fix (0.7.13)
- com.laravel_idea.tailwind (1.4.2)
- com.github.aleksandrsl.intellijbrowserslist (1.0.2)
- dev.blachut.svelte.lang (242.21829.3)
- com.rxliuli.vite-jetbrains-plugin (0.2.2)
- de.espend.idea.vuejs (1.0.0)
- tv.twelvetone.intellij.plugins.intellivue (1.2.14)
- mdx.js (242.20224.159)
- com.github.copilot (1.5.21.6667)
- com.github.shiraji.findpullrequest (2.0.4)
- dmitriy.molchanov.commit-prefix-plugin (1.4.1)
- mobi.hsz.idea.gitignore (4.5.3)
- com.intellij.microservices.ui (242.21829.14)
- com.intellij.plugins.html.instantEditing (242.20224.155)
- izhangzhihao.rainbow.brackets (2024.2.6-241)
- com.locale_sphere.plugin (1.0.2.232)
- com.kalessil.phpStorm.phpInspectionsEA (5.0.0.0)
- com.chrisrm.idea.MaterialThemeUI (9.5.0)
- com.github.lppedd.idea-return-highlighter (0.8.3)
- org.mallowigi.focusmode (3.0.0)
- lv.midiana.misc.phpstorm-plugins.deep-keys (2022.08.03.001)
- com.clutcher.comments_highlighter (2024.2.3)
- cn.yiiguxing.plugin.translate (3.6.4)
- ru.adelf.idea.dotenv (2024.2.1)
- io.github.freeApplications.intellij-plugins (1.3.0)
- com.mallowigi.colorHighlighter (18.0.0)
- de.espend.idea.php.toolbox (6.2.0)
- de.espend.idea.php.annotation (11.0.3)
- org.endpointdeps.EndpointDependencies (1.3)
- com.laravel_idea.plugin (8.2.5.242)
- com.mallowigi (97.0.0)
- zielu.gittoolbox (500.2.15+242)
- dev.ekvedaras.laravelquery (4.0.4)

</details>

**Comment by Lukasss93** [comment]
Disabling all plugins except Material Theme and Classic UI solves the problem (temporarily).
I will try to find out what the "malicious" plugin is by enabling a few plugins at a time.

I will let you know.

**Comment by Lukasss93** [comment]
Found!
The plugin that “breaks” the language of Material Theme is:

Focus Mode 2
Author: AtomMaterial
Namespace: org.mallowigi.focusmode (3.0.0)
Link: https://plugins.jetbrains.com/plugin/21237-focus-mode-2

Disabled (for now).

**Comment by mallowigi** [comment]
thanks a lot! I kinda archived this project (Focus Mode 2) but if it causes trouble I'll try to fix it.

**Comment by Lukasss93** [comment]
> thanks a lot! I kinda archived this project (Focus Mode 2) but if it causes trouble I'll try to fix it.

I use Focus Mode 2 a lot!
It would be nice if it could be fixed ❤️

**Comment by mallowigi** [comment]
If you're interested in taking the ownership, be my guest. Because i won't update it anymore.

**Comment by mallowigi** [comment]
Fixed. Let's hope JetBrains will approve the release.
