### ISSUE TITLE
[Bug]: cannot show images when offline

### ISSUE THREAD

**Issue by bestv5** [mallowigi/material-theme-issues#546]
### Describe the bug

Images cannot be displayed in offline environments 

![image](https://github.com/user-attachments/assets/80e3fc29-6960-4158-bb30-1879b2781f62)

### To Reproduce

1. offline environments 
2. open idea settings

### Expected behavior

Images can be displayed

### Material Theme Version

V9.5.0

### IDE

IntelliJ IDEA

### System Info

```shell
win10
```

**Comment by mallowigi** [comment]
Of course, images are fetched online.
