### ISSUE TITLE
Console Font Settings are lost after switching themes and reverting

### ISSUE THREAD

**Issue by Manish-Giri** [mallowigi/material-theme-issues#59]
**Describe the bug**

Console Font settings are lost/overwritten every time you switch between themes and revert to your original theme.

**To Reproduce**

1. Set any desired Color Scheme and Console Font settings (Settings > Editor > Color Scheme > Console Font): Font, Size, Line Height
2. Check the "Use console  font instead of the default" option
3. Click "OK"
4. Close any terminal windows if open.
5. Switch between 4 or 5 different themes (Tools > Material Theme > Material Theme Chooser)
6. Revert to the original theme that you had at the beginning, and open a new terminal window
7. All console font settings (font, size, line height) have been overridden and replaced with some other settings. Even though "Console Font Settings" in Step 1 still shows the same settings you had selected and saved.

The only way to bring back the original saved settings is to restart the IDE.

**Expected Behavior**

Console Font Settings should always remain the same if you switch between themes and revert to the original theme.

**Environment**

**Screenshots**

#### Expected (as per my saved console font settings - Cascadia Code PL, Size: 11, Line Height: 1.0)
![exp](https://user-images.githubusercontent.com/11348778/149701163-8deadf00-c929-40d4-8b62-1ecffe90ec9f.png)

#### Actual (messed up settings) 
![act](https://user-images.githubusercontent.com/11348778/149701207-dd16fb67-8c51-428e-b8d6-d562aed109fb.png)

**Comment by mallowigi** [comment]
Hi, do you have this option enabled? https://material-theme.com/docs/what-s-new/#use-editor-default-font

**Comment by mallowigi** [comment]
Just for context, this option will override the editor font (afaik only the editor font, not the console font but I'm not sure), and once activated, everytime you switch to another color scheme, it will automatically pick up the font you set up in the `Color Scheme > Font` settings, thus overriding the color scheme's custom font. Maybe that's the cause of your problem.

On a side-note I just realized that this feature documentation is missing, surprisingly.

**Comment by marktripney** [comment]
On a related note... I've noticed that, only recently, Material Theme UI (paid) seems to continually revert to a scheme's default font. I typically use Monokai Pro (Material), and I _keep_ getting Menlo every time I launch WebStorm. I've just used the 'Use Editor Default Font' feature @mallowigi mentions above (thanks!), which works... but I still get a flash of Menlo on startup before it switches to my Editor Default.

(I'm on Material Theme UI 6.12.2, and WebStorm 2021.3.1.)

**Comment by Manish-Giri** [comment]
@mallowigi Hi, thank you for responding. I don't have that option enabled. I only ever use 2-3 themes from the whole list (GitHub Dark, Moonlight, Deep Ocean) so I don't mind setting the color scheme setting for each theme individually, rather than setting a global default override.

Either way, that option controls only the Editor font settings, as you pointed out, and not the console font settings. In my case, only the console font settings are affected, and if I recall correctly, there isn't even a global console font override option available anywhere that I might have selected accidentally.

**Comment by dtrunk90** [comment]
I'm affected too. Everytime I close and re-open IntelliJ CE 2021.3.2 the console font is set back to default (JetBrains Mono). With the plugin disabled the custom console font persists. So this seems to be a bug related to Material Theme UI. Reference: https://intellij-support.jetbrains.com/hc/en-us/community/posts/4671807401490

**Comment by Manish-Giri** [comment]
Since this is a JetBrains issue, to all those who are affected - please add a comment to this issue I had created on YouTrack - https://youtrack.jetbrains.com/issue/IDEA-288640
