### ISSUE TITLE
Activation impossible in Android Studio Bumblebee

### ISSUE THREAD

**Issue by ThexXTURBOXx** [mallowigi/material-theme-issues#63]
**Describe the bug**
Upon clicking the "Activate License" button in Android Studio 2021.1.1 Bumblebee, no activation window appears when closing the settings.

**To Reproduce**
1. Update to Android Studio 2021.1.1 Bumblebee
2. Open the Settings
3. Navigate to `Appearance & Behavior -> Material Theme UI`
4. Click the `Activate License` button
5. Close the Settings
6. Nothing happens

**Expected Behavior**
A license activation window should open

**Environment**
Android Studio Bumblebee | 2021.1.1 RC 1
Build #AI-211.7628.21.2111.8005941, built on December 16, 2021
Runtime version: 11.0.11+9-b60-7590822 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 8
Registry: external.system.auto.import.disabled=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.mallowigi (36.0), lermitage.intellij.extra.icons (1.69.3.203), net.vektah.codeglance (1.5.4), com.almightyalpaca.intellij.plugins.discord (1.8.0), mobi.hsz.idea.gitignore (4.1.0), Dart (211.7798), com.localizely.flutter-intl (1.17.1-2020.3), some.awesome (1.14), org.jetbrains.kotlin (211-1.6.10-release-923-AS7442.40), io.flutter (63.2.2), com.developerphil.adbidea (1.6.4), com.chrisrm.idea.MaterialThemeUI (6.7.2), izhangzhihao.rainbow.brackets (6.21)

**Screenshots**
It is also important to note that the `Register` button is missing in the `Help` menu (it should be there where the red ellipse is) - which is why I think that the activation window is not even implemented in Android Studio (or has been removed):

![grafik](https://user-images.githubusercontent.com/12763829/151073725-749587af-7e32-43f5-966b-299b96460b6d.png)

**Comment by dsa28s** [comment]
@ThexXTURBOXx Hello, I had the same issue, so I looked it up.

Install [Jetbrains Marketplace Licensing Support](https://plugins.jetbrains.com/plugin/13407-jetbrains-marketplace-licensing-support) plugin, and restart android studio.
After that, you can try again.

![Screen Shot 2022-01-26 at 12 28 56 PM](https://user-images.githubusercontent.com/10934461/151099263-747a3763-b251-486e-b455-e641c0de879d.png)

**Comment by mallowigi** [comment]
Thanks, I didn't know about this.

**Comment by ThexXTURBOXx** [comment]
@dsa28s Thank you very much for the hint! It worked without problems after installing the plugin.
Maybe, it would be worth specifying the licensing plugin as required dependency then? I don't know :)
Anyways, this issue is kinda "fixed" now. Thank you very much :)

@mallowigi You can close this issue at your own will (if you want to leave it open for now, it's up to you)

**Comment by mallowigi** [comment]
I'll leave that open to not forget to add it in the doc.
