### ISSUE TITLE
[Bug]: Editor Font Size resets after restarting Rider

### ISSUE THREAD

**Issue by eka** [mallowigi/material-theme-issues#75]
### Describe the bug

Summary
Changing the Font size will be reset next time I open Rider again.

I opened a bug with Jetbrains but disabling Material Theme fixes the problem, hence I'm here now.

Here is the link to the bug report with all the detailed data, please take it from there

https://youtrack.jetbrains.com/issue/RIDER-74252

### To Reproduce

Steps to reproduce (if needed)
First step
Change Editor Font Size

Second step
Restart Rider

### Expected behavior

Expected behavior
Keep Editor font size to the one I set previously

Actual behavior
Editor Font is reset to default every time Rider is restarted

### Material Theme Version

6.13.0

### IDE

Rider

### System Info

```shell
https://youtrack.jetbrains.com/issue/RIDER-74252
```

### Logs/Screenshots

```shell
https://youtrack.jetbrains.com/issue/RIDER-74252
```

**Comment by mallowigi** [comment]
Before I check this, please check if you're not using the "Use Default Editor Font" setting. This have the effect of overriding your current font with the font defined in `Color Scheme > Font`

**Comment by eka** [comment]
hi, 

It wasn't set 

![image](https://user-images.githubusercontent.com/157223/153610540-76737ef6-6d2e-4ea6-8041-96614c6cc57e.png)

Tried setting and unsetting and still happens.

**Comment by mallowigi** [comment]
I tried on Mac and Linux and it doesn't reproduce. If it still happens on your end, can you connect to Slack so we can pinpoint this issue more precisely? Thanks.
