### ISSUE TITLE
[Bug]: Solid box background in checkboxs/arrows

### ISSUE THREAD

**Issue by ackmanx** [mallowigi/material-theme-issues#84]
### Describe the bug

It looks like there is some graphically glitches in the attached screenshots.

### To Reproduce

Open the Git panel or commit modal

### Expected behavior

There should be no awkward background for the git panel changes. 

There should be either a checkbox in the commit modal for files, or, a solid color that matches the accent color and not an unrelated color.

### Material Theme Version

6.13.0

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2021.3.2 (Ultimate Edition)
Build #IU-213.6777.52, built on January 27, 2022
Licensed to Eric Majerus
Subscription is active until April 1, 2022.
Runtime version: 11.0.13+7-b1751.25 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.0.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
    ide.balloon.shadow.size=0
    ide.images.show.chessboard=true

Non-Bundled Plugins:
    some.awesome (1.14)
    ski.chrzanow.foldableprojectview (1.1.1)
    com.samdark.intellij-visual-studio-code-dark-plus (2.5)
    net.ashald.envfile (3.2.2)
    mobi.hsz.idea.gitignore (4.3.0)
    intellij.prettierJS (213.6461.6)
    com.deadlock.scsyntax (213.5744.190)
    com.chrisrm.idea.MaterialThemeUI (6.13.0)
    ru.adelf.idea.dotenv (2022.1)

Kotlin: 213-1.6.10-release-944-IJ6461.79
```

### Logs/Screenshots
<img width="355" alt="Screen Shot 2022-02-18 at 17 48 53" src="https://user-images.githubusercontent.com/7490057/154776162-449964b3-fe0f-4dca-a431-7916da358a45.png">
<img width="524" alt="Screen Shot 2022-02-18 at 17 50 24" src="https://user-images.githubusercontent.com/7490057/154776164-18d5438d-be0b-4838-bb1d-f523a49f6e44.png">
<img width="336" alt="Screen Shot 2022-02-18 at 17 50 32" src="https://user-images.githubusercontent.com/7490057/154776166-ec8a8801-6f04-4dce-bbfc-3d54c4128258.png">
<img width="602" alt="Screen Shot 2022-02-18 at 17 51 04" src="https://user-images.githubusercontent.com/7490057/154776167-c83dfef9-74d8-4e80-92fd-5929f2b10242.png">

**Comment by mallowigi** [comment]
What is the theme ?

**Comment by ackmanx** [comment]
It says "Github (Material)"

**Comment by ackmanx** [comment]
Also does it with Atom One light theme

**Comment by mallowigi** [comment]
Is it still happening as of latest versions? I can't reproduce on Mac
