### ISSUE TITLE
[Bug]: struct fileds‘ type cannot be aligned

### ISSUE THREAD

**Issue by bestgopher** [mallowigi/material-theme-issues#85]
### Describe the bug

This picture is a screenshot from goland.The two field types underlined in red cannot align with the other three.
<img width="355" alt="image" src="https://user-images.githubusercontent.com/36840497/155068486-55e358aa-e50a-4a03-a03c-d9b2bc48bb1e.png">
But viewing it through vim is aligned.
<img width="546" alt="image" src="https://user-images.githubusercontent.com/36840497/155068743-6bceeb1f-53c1-4bf0-92b0-b0e339604c49.png">

### To Reproduce

goland version: 2021.3.3
Using all themes provided by **material ui** plugin can reporduce this bug.

### Expected behavior

align!!

### Material Theme Version

6.9.1

### IDE

Other (AppCode, CLion, GoLang...)

### System Info

```shell
GoLand 2021.3.3
Build #GO-213.6777.51, built on January 27, 2022
Licensed to *****
Subscription is active until *****
For non-commercial open source development only.
Runtime version: 11.0.13+7-b1751.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6.2
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
    suggest.all.run.configurations.from.context=true
    ide.completion.variant.limit=500
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    com.yoheimuta.intellij.plugin.protolint (1.0.1)
    com.tabnine.TabNine (0.5.18)
    com.markskelton.one-dark-theme (5.5.0)
    com.github.copilot (1.0.2)
    cn.jxzhang.plugin.json-formatter (1.4)
    club.nutsoft.Github3Theme (1.1.9)
    Statistic (4.1.7)
    PlantUML integration (5.5.1)
    com.chrisrm.idea.MaterialThemeUI (6.9.1)
```

**Comment by mallowigi** [comment]
does it happen with other color schemes ? (Darcula for ex)

**Comment by bestgopher** [comment]
Thank you for your reply. 
I found out that the cause of this "bug" was that I had ligatures enabled. When I turn off the ligature it is correct.
disable:
![image](https://user-images.githubusercontent.com/36840497/155118444-1adf660a-a353-4293-a866-ffeefa15fd28.png)
enable:
![image](https://user-images.githubusercontent.com/36840497/155118520-adbc311e-d97d-4f4a-a732-0d728a235fa5.png)
I don't know how to cause this bug, but I don't have this trouble now.

**Comment by mallowigi** [comment]
oh right, the fl issue. Cool so it's not a bug then.

**Comment by bestgopher** [comment]
<img width="675" alt="image" src="https://user-images.githubusercontent.com/36840497/155291381-bad9426a-6f9f-4d66-bbf8-7fc049cf7b03.png">
I don't know if this bug is caused by themes. Can you reproduce？

**Comment by mallowigi** [comment]
Yes, And this is not related to the plugin at all, but rather to the font. You should read about ligatures: https://practicaltypography.com/ligatures-in-programming-fonts-hell-no.html

Long story short, ligatures tend to replace "fi" and "fl" with their ligatured counterpart. As a result, the editor displays one character instead of two, making things uneven.

It's not a big deal IMO, I use ligatures every day and it doesnt bother me the slightest.

**Comment by bestgopher** [comment]
Thank you for your patience.
