### ISSUE TITLE
[Feature]: Possibility to evaluate the entire path in the regex instead of only the file name.

### ISSUE THREAD

**Issue by yackinn** [mallowigi/material-theme-issues#89]
### Describe the feature

Possibility to evaluate the entire path in the regex instead of the file name.

nestjs/src/app.module.ts
angular/src/app.module.ts

These files should have different icons.

### Use Cases

As stated above

### Material Theme Version

6.13.0

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2021.3.2 (Ultimate Edition)
Build #IU-213.6777.52, built on January 28, 2022
Licensed to adesso SE / Yannick Boetzkes
You have a perpetual fallback license for this version.
Subscription is active until February 11, 2023.
Runtime version: 11.0.13+7-b1751.25 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.2.1
GC: G1 Young Generation, G1 Old Generation
Memory: 3000M
Cores: 10
Registry:
    documentation.show.toolbar=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    socrates.tabshifter (0.30)
    ideanginx9 (0.1.9)
    com.jetbrains.plugins.ini4idea (213.5744.190)
    com.intellij.plugins.xwinkeymap (211.4961.30)
    com.intellij.plugins.gnomekeymap (213.4250.391)
    org.jetbrains.kotlin (213-1.6.10-release-961-IJ6777.52)
    com.intellij.apacheConfig (213.5744.190)
    com.jetbrains.php (213.6777.58)
    com.jetbrains.twig (213.5744.224)
    mdx.js (1.0.213)
    de.timo_reymann.intellij-mjml-support (2.0.0)
    com.github.iguissouma.nxconsole (0.38.0)
    com.github.etkachev.nxwebstorm (0.9.2)
    com.dmarcotte.handlebars (213.5744.190)
    mobi.hsz.idea.gitignore (4.3.0)
    com.ppolivka.plugin.gitcleaner (1.1.4)
    com.mallowigi (54.1.0)
    aws.toolkit (1.38-213)
    ru.adelf.idea.dotenv (2022.1)
    com.chrisrm.idea.MaterialThemeUI (6.13.0)

Kotlin: 213-1.6.10-release-961-IJ6777.52
```

**Comment by mallowigi** [comment]
It's something I'm planning to study on but even so I don't think your use is right. I am a NestJS developer myself and I'm never using "nestjs" as a project name, or even directory name. It's not realistic. Moreover, having NestJS and Angular in the same project is also rarely a thing.

Therefore what I'm doing right now is to disable the Angular associations in order to use Nest icons. In the future I'm also planning to have Project Associations, but it's not for now.

**Comment by mallowigi** [comment]
Also, wrong repository

**Comment by yackinn** [comment]
> It's something I'm planning to study on but even so I don't think your use is right. I am a NestJS developer myself and I'm never using "nestjs" as a project name, or even directory name. It's not realistic. Moreover, having NestJS and Angular in the same project is also rarely a thing.
> 
> Therefore what I'm doing right now is to disable the Angular associations in order to use Nest icons. In the future I'm also planning to have Project Associations, but it's not for now.

The naming is just for illustration purposes.
In a real project it's more like backend/api and ui

Having Nestjs and Angular inside of a monorepo is pretty common these days I assume.

If we disable the Angular associations the Angular modules would have Nestjs icons. That's also not ideal.

**Comment by mallowigi** [comment]
If it's a monorepo it's even harder as the per project settings won't be able to apply :/

**Comment by yackinn** [comment]
That's correct. That's why I was asking for being able to evaluate the entire path instead of just the file name.
