### ISSUE TITLE
[Bug]: File type selection menu has artifact on side of selected item.

### ISSUE THREAD

**Issue by tom-ricci** [mallowigi/material-theme-issues#95]
### Describe the bug

When trying to create a new file with the file selection menu, there is an artifact on the side of the topmost item in the list. For example, in Java:
![image](https://user-images.githubusercontent.com/79022795/157938926-1922fbd3-70c0-4ce8-aa9c-2c33413cc22c.png)
(Artifact is on the left side of the Class option.)

This also happens in menus with scrollbars, but on both sides instead of just the left:
![image](https://user-images.githubusercontent.com/79022795/157939654-14b7a4e8-9285-4cd9-b89c-9a99fb10a413.png)
(Artifact is on the left and right sides of the Interface option.)
It also changes from the topmost item to whatever item is currently selected when the menu is scrolled. In this case I had the Interface option selected while scrolling the scrollbar, so that's why the artifact is there instead of at the top.

### To Reproduce

1. Right click on the project tab
2. Hover over new
3. Click on a file type which has support for IntelliJ's custom file picker (like Java files, Kotlin files, or Typescript files)
4. Sob as you try to figure out what happened and end up attempting to remake material theme from scratch to solve this issue, then realize you don't have the time for that and go to https://github.com/mallowigi/material-theme-issues/issues/new?template=bug_report.yml

### Expected behavior

For there to be no artifact on the sides of these buttons.

*Also, more of a feature request than a bug, but instead of fixing the artifact and making the buttons in the menu round, could they be square instead? The file-chooser menus more closely represent dropdowns than normal menus, and by that logic their buttons should follow the dropdown style, which uses square corners on each button rather than rounded ones.*

### Material Theme Version

v6.14.1

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2021.3.2 (Ultimate Edition)
Build #IU-213.6777.52, built on January 27, 2022
Licensed to Thomas Ricci
Subscription is active until March 5, 2023.
For educational use only.
Runtime version: 11.0.13+7-b1751.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 750M
Cores: 12
Registry:
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    com.intellij.plugins.xwinkeymap (211.4961.30)
    com.intellij.plugins.gnomekeymap (213.4250.391)
    org.jetbrains.kotlin (213-1.6.10-release-961-IJ6777.52)
    mobi.hsz.idea.gitignore (4.3.0)
    com.demonwav.minecraft-dev (2021.3-1.5.18)
    com.intellij.tailwindcss (213.6777.38)
    com.chrisrm.idea.MaterialThemeUI (6.14.1)

Kotlin: 213-1.6.10-release-961-IJ6777.52
```

**Comment by mallowigi** [comment]
I noticed it too. But I've already released two hotfixes this week. I'll try to fix it for a future release.
