### ISSUE TITLE
[Feature]: Student discounts

### ISSUE THREAD

**Issue by ThexXTURBOXx** [mallowigi/material-theme-issues#96]
### Describe the feature

A small follow-up for my original issue (https://github.com/ChrisRM/material-theme-jetbrains/issues/1746):
It seems to be possible now to specify discounts directly in the JetBrains plugin page as seen in the example of the Extra Icons plugin down below.
This would be very convenient for all users and you to offer these discounts :)

### Use Cases

Students and other people that are eligible for discounts: They can just apply via the plugin page
@mallowigi: No more emails asking for discounts/codes

### Examples/Mockups

From https://plugins.jetbrains.com/plugin/11058-extra-icons/pricing#edition=personal:
![grafik](https://user-images.githubusercontent.com/12763829/158018155-d3ee95a5-e6cb-43f8-af7a-88e8db23a697.png)

### Material Theme Version

6.14.1

### IDE

IntelliJ IDEA

**Comment by mallowigi** [comment]
Isn't it already the case? 🤔

**Comment by ThexXTURBOXx** [comment]
Oh, it looks like, the buttons are not shown if you already own a license for the plugin.
In that case, I am not able to check if it is the case, I am sorry!
