### ISSUE TITLE
[Bug]: Autocomplete line height has changed and is not configurable

### ISSUE THREAD

**Issue by SVillette** [mallowigi/material-theme-issues#98]
### Describe the bug

Since v6.14.0, the autocomplete popup has a different line height and I could not find any way to configure it.

### To Reproduce

I'm currently using Atom One Dark theme

### Expected behavior

The autocomplete line height should be configurable 

### Material Theme Version

v6.14.1

### IDE

PHPStorm

### System Info

```shell
PhpStorm 2021.3.2
Build #PS-213.6777.58, built on January 31, 2022
Runtime version: 11.0.13+7-b1751.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.11.0-49-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 1984M
Cores: 8
Registry:
    run.processes.with.pty=TRUE
    ide.experimental.ui.toolwindow.stripes=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    name.kropp.intellij.makefile (213.5744.224)
    com.intellij.ideolog (203.0.27.0)
    String Manipulation (9.4.0)
    Key Promoter X (2021.3)
    mobi.hsz.idea.gitignore (4.3.0)
    ru.adelf.idea.dotenv (2022.1)
    de.espend.idea.php.toolbox (6.0.0)
    de.espend.idea.php.annotation (8.0.0)
    fr.adrienbrault.idea.symfony2plugin (0.23.213)
    com.dmarcotte.handlebars (213.5744.190)
    com.chrisrm.idea.MaterialThemeUI (6.14.1)
    com.mallowigi (54.1.0)

Current Desktop: KDE
```

### Logs/Screenshots

![image](https://user-images.githubusercontent.com/17042730/158159554-46570776-c23d-4ff1-aca2-d1b3c42ed896.png)

**Comment by mallowigi** [comment]
Try to use the List Items Height from the Compact Tab

**Comment by SVillette** [comment]
I tought it was for the items in the project view.

Thank you and sorry for the inconveniance.
