### ISSUE TITLE
[Feature]: Button/menu styles

### ISSUE THREAD

**Issue by tom-ricci** [mallowigi/material-theme-issues#99]
### Describe the feature

A possible toggle to switch between the current rounded/shaded and original square/flat buttons, file selectors, menu items, etc.

### Use Cases

While this is just graphical so there aren't really any specific uses, it would clean some things up:
* Would make transparent scrollbar in the project tab look better, as when it covers the currently selected item the roundness of the item on the side of the scrollbar is hard to see and makes the button look weird
* Would also make the sharp indicator style in the project menu look sharper
* Would make buttons which have no margin in between them (for example push, linked below) look more like one button with multiple sections rather than two buttons pushed weirdly together
* Would make buttons consistent with other items like documentation popovers and intellisense menus
* Would make item selections in the project tab consistent with the currently selected line, so instead of the selected line being square and the selected file being round they would look similar

### Examples/Mockups

For example, square buttons would fix the current issue with the push button:
![image](https://user-images.githubusercontent.com/79022795/158386273-8e95fa9a-80b1-4a49-8dbd-766364d248ec.png)
![image](https://user-images.githubusercontent.com/79022795/158386118-f2fa57bc-acad-4c02-951b-2b573274c585.png)

### Material Theme Version

v6.14.1

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2021.3.2 (Ultimate Edition)
Build #IU-213.6777.52, built on January 27, 2022
Licensed to Thomas Ricci
Subscription is active until March 5, 2023.
For educational use only.
Runtime version: 11.0.13+7-b1751.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 750M
Cores: 12
Registry:
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    com.intellij.plugins.xwinkeymap (211.4961.30)
    com.intellij.plugins.gnomekeymap (213.4250.391)
    org.jetbrains.kotlin (213-1.6.10-release-961-IJ6777.52)
    mobi.hsz.idea.gitignore (4.3.0)
    com.demonwav.minecraft-dev (2021.3-1.5.18)
    com.intellij.tailwindcss (213.6777.38)
    com.chrisrm.idea.MaterialThemeUI (6.14.1)

Kotlin: 213-1.6.10-release-961-IJ6777.52
```

**Comment by mallowigi** [comment]
I thought about this and considered keeping the old ui as a setting, but I ultimately decided that it was time to ditch it as this is what the material design library did.

That's why I tried to st least provide options such as compact fields and list items height.

If the buttons are the issue, I can try to add a setting to control the button radius, but I'd really rather not keep the old ui as much as possible.

**Comment by tom-ricci** [comment]
Ah, ok!

**Comment by mallowigi** [comment]
I'll try to see if I can reinsert the old UI for the next EAP. I can understand that not everyone are pleased with the changes.

**Comment by mallowigi** [comment]
Even though I am the one that implemented it, in all honesty I'm happy with the new buttons and selected items design, but the text fields and comboboxes were better before, that's why I'm considering a comeback.

**Comment by tom-ricci** [comment]
Yeah, the buttons and designs for selected items do look nice but they feel out of place for an IDE, kinda like how in most designs animating everything looks weird even though the individual animated components look good.

**Comment by mallowigi** [comment]
Added a setting. Closing.

**Comment by tom-ricci** [comment]
tysm! Also, not to keep nagging but could the old style reset the project tab item background to a square taking up the whole space instead of the new one? :sweat_smile: 
![image](https://user-images.githubusercontent.com/79022795/159139714-d2fd5590-817d-48f3-a726-466002098796.png)

**Comment by mallowigi** [comment]
Hmm... so the old tree painters are not part of the old design setting?

**Comment by tom-ricci** [comment]
Unless there's something I'm missing, no. I reinstalled the plugin to check if something was weird with my install, but there was no change.
